### ISSUE TITLE
Cutechess GUI crash after selecting unknown variant in database window

### ISSUE THREAD

**Issue by gbtami** [cutechess/cutechess#102]
I'v imported my fics games from pgn. It imported all variant games too without any error message, but after selecting a suicide game it crashed with segmentation error.

**Comment by ilaripih** [comment]
Could you paste one of those problematic suicide games here, or attach as a PGN?

**Comment by gbtami** [comment]
[Event "FICS unrated suicide game"]
[Site "FICS freechess.org"]
[FICSGamesDBGameNo "384069627"]
[White "gbtami"]
[Black "stayalive"]
[WhiteElo "1530"]
[BlackElo "2811"]
[WhiteRD "na"]
[BlackRD "na"]
[BlackIsComp "Yes"]
[TimeControl "180+0"]
[Date "2015.12.09"]
[Time "17:19:00"]
[WhiteClock "0:03:00.000"]
[BlackClock "0:03:00.000"]
[Variant "suicide"]
[PlyCount "10"]
[Result "0-1"]

1. c3 e5 2. Qa4 e4 3. Qxa7 Rxa7 4. Na3 Rxa3 5. bxa3 Bxa3 {White resigns} 0-1


[Event "FICS unrated suicide game"]
[Site "FICS freechess.org"]
[FICSGamesDBGameNo "384055639"]
[White "gbtami"]
[Black "masheen"]
[WhiteElo "1530"]
[BlackElo "2647"]
[WhiteRD "na"]
[BlackRD "na"]
[BlackIsComp "Yes"]
[TimeControl "300+0"]
[Date "2015.12.09"]
[Time "11:00:00"]
[WhiteClock "0:05:00.000"]
[BlackClock "0:05:00.000"]
[Variant "suicide"]
[PlyCount "6"]
[Result "0-1"]

1. g3 c5 2. Bg2 b5 3. Bxa8 Bb7 {White resigns} 0-1

**Comment by ilaripih** [comment]
Fixed. Now an error message is shown when an incompatible game is selected.
