### ISSUE TITLE
Missing dependancy under Windows

### ISSUE THREAD

**Issue by mcostalba** [cutechess/cutechess#104]
With latest setup I got another missing dependancy:

https://snag.gy/dC7qSx.jpg

After googling a bit...you probably compiled under Windows 10 with MSVC 2015: https://support.microsoft.com/en-us/kb/2999226

**Comment by ilaripih** [comment]
Correct. Once I've fixed the current bugs and am ready to deploy version 0.9.1, I'll include vcredist_x64.exe in the Windows installer, so that all needed MSVC libraries are installed automatically.

**Comment by ilaripih** [comment]
The 0.9.1 installer includes and executes vcredist_x64.exe.
