### ISSUE TITLE
Show tournament results also for two-player tournaments

### ISSUE THREAD

**Issue by elcabesa** [cutechess/cutechess#105]
up to now the report of the current tournament between 2 engine is:

ELO difference: 46.60 +/- 153.85
156 games played of 64000

we don't even know who is playing and who is stronger.

it would be better to have the same output of cli program:

Score of vajolet2 2.3.5 vs vajolet2 2.3.4: 8 - 6 - 12  [0.538] 26
ELO difference: 26.78 +/- 100.67

**Comment by ilaripih** [comment]
Stupid bug due to insufficient testing. I've fixed it here: https://github.com/cutechess/cutechess/commit/8fd78d54523f887f8f354d839a814353120ff6ea

To avoid duplicate reports I'll leave the 0.9.0 bugs open until 0.9.1 has been deployed.
