### ISSUE TITLE
Double-click to add new player to tournament

### ISSUE THREAD

**Issue by elcabesa** [cutechess/cutechess#106]
when adding player to a new tournament it would be nice to be able to select more than one engine from the list and also add an engine by double-click

2 request with one issue:
multiple engine selection
double click selection

**Comment by ilaripih** [comment]
It is possible to add multiple engines at the same time by using CONTROL+click or SHIFT+click or just highlighting a bunch of engines with the mouse.

Adding one engine via double-clicking is a good idea.
