### ISSUE TITLE
return error code to indicate SPRT conclusion

### ISSUE THREAD

**Issue by lucasart** [cutechess/cutechess#11]
I would like the cutechess-cli executable to return an error code, so it can be used in a shell script to automate chained SPRT tests.

Error code would indicate if we accept H0, H1, or if SPRT did not conclude (eg. user pressed Ctrl+C, an engine crashed, or max nb of games reached).

A typical use for me is to do a two step SPRT test to prefilter at fast TC and validate at longer TC, similar to what is done in the Stockfish framework.

**Comment by ilaripih** [comment]
Stuff is finally happening in CuteChess development, thanks to the annual CuteChess Hackathon! Anyway, we decided that it would be correct to add different return codes for failure states:

* User interrupted cutechess-cli with CTRL+C (use default SIGINT exit code 130)
* An engine couldn't be started
* An engine crashed and the "-recover" option wasn't enabled

However, adding exit codes for states where there's no failure (eg. SPRT results) conflicts with the idea that processes should exit with 0 on success.

**Comment by lucasart** [comment]
understood. closing.
