### ISSUE TITLE
Label players' colors more clearly

### ISSUE THREAD

**Issue by elcabesa** [cutechess/cutechess#110]
whatching a game it's difficult to understand who is white and black.

**Comment by ilaripih** [comment]
White is always on the left and black on the right. Would it help if it said "White" over the white player's name and "Black" over the black player's name?

**Comment by elcabesa** [comment]
I think it oculd help :)

**Comment by ilaripih** [comment]
I'll have to think about this. Most chess GUIs are just using the "white on the left, black on the right" convention. But I like what PyChess has done with the little white or black analog clock next to the player name.

**Comment by ilaripih** [comment]
Thanks @alwey !
