### ISSUE TITLE
Default book depth to 1 full move is a poor choice

### ISSUE THREAD

**Issue by mcostalba** [cutechess/cutechess#115]
After selecting a polyglot book in tournament dialog I have always to manually set full moves to 10 (arbitrary high number) because the default is 1 full move

I suggest to default to "unlimited" that is also more convenient than forcing the user to set a very high number to mean he wants to use the book fully.

**Comment by mcostalba** [comment]
While there, access mode "ram or disk" is really geeky :-) are you sure you need to expose that implementation related option to the user that very possibly does not understand what it means (I don't btw).

**Comment by ilaripih** [comment]
I've increased default opening book depth to the more sensible 10 full moves. But that default is used only if you've never opened Cute Chess' Settings dialog where you can set your own default on the "Games" tab.

And I've added tooltip texts for the "Ram" and "Disk" access modes. Most people should use the default "Ram" mode but there are some who are using huge books that don't fit in memory.
