### ISSUE TITLE
when switching to tab with only PGN data, scroll to last move

### ISSUE THREAD

**Issue by ilaripih** [cutechess/cutechess#118]
When a tab containing only PGN data (no ChessGame object) is activated, GameViewer and MoveList should scroll to the last move just like we do with ChessGame objects.

Things would be different if we actually used the main window for opening and browsing PGN games; then we'd obviously want to show the starting position.

**Comment by zhu-jz** [comment]
After one tournament finishes, if switching the game tabs,  it is actually the starting position of each game shown while the cursor of the move list is on the last move, is it normal? thx

**Comment by ilaripih** [comment]
That's actually exactly what this issue about. So it will be fixed soon.

**Comment by ilaripih** [comment]
Done.
