### ISSUE TITLE
Incorrect resume (concurrency) after a paused match

### ISSUE THREAD

**Issue by pb00068** [cutechess/cutechess#120]
If I want to pause an ongoing SPRT-Test, then (on windows OS) I can press CTRL-S on the according command prompt window so that cute-chess (cutechess-cli 0.8.2 Using Qt version 5.6.0) isn't starting new games anymore until I press CTRL-S again.
This is very useful if I need my computer necessarily for other CPU-intensive-tasks like compiling where without pausing the SPRT-Test the cpu's would starve and falsify the outcome of the test.
The problem is, when pressing CTRL-S again, then cute-chess is starting almost the double of games it actually should. 
For instance I have set concurrency to 6, but after resuming with CTRL-S cutechess starts 
11 games all at once:
...
Started game 8418 of 60000 (base vs new)
Started game 8419 of 60000 (new vs base)
Started game 8420 of 60000 (base vs new)
Started game 8422 of 60000 (base vs new)
Started game 8421 of 60000 (new vs base)
Started game 8423 of 60000 (new vs base)
Started game 8426 of 60000 (base vs new)
Started game 8424 of 60000 (base vs new)
Started game 8425 of 60000 (new vs base)
Started game 8428 of 60000 (base vs new)
Started game 8427 of 60000 (new vs base)
Finished game 8426 (base vs new): 1/2-1/2 {Draw by 3-fold repetition}
Score of new vs base: 1180 - 1113 - 6125  [0.504] 8418
Finished game 8426 (base vs new): 1/2-1/2 {Draw by 3-fold repetition}
Score of new vs base: 1180 - 1113 - 6125  [0.504] 8418
Finished game 8418 (base vs new): 1/2-1/2 {Draw by adjudication}
Score of new vs base: 1180 - 1113 - 6126  [0.504] 8419
Finished game 8428 (base vs new): 1/2-1/2 {Draw by adjudication}
Score of new vs base: 1180 - 1113 - 6127  [0.504] 8420
Finished game 8419 (new vs base): 1/2-1/2 {Draw by adjudication}
Score of new vs base: 1180 - 1113 - 6128  [0.504] 8421
Finished game 8427 (new vs base): 1-0 {White wins by adjudication}
Score of new vs base: 1181 - 1113 - 6128  [0.504] 8422
Finished game 8425 (new vs base): 1-0 {White wins by adjudication}
Score of new vs base: 1182 - 1113 - 6128  [0.504] 8423
Started game 8429 of 60000 (new vs base)
Finished game 8421 (new vs base): 1/2-1/2 {Draw by adjudication}
Score of new vs base: 1182 - 1113 - 6129  [0.504] 8424
Started game 8430 of 60000 (base vs new)
Terminating process of engine base(20)
Terminating process of engine new(22)
Terminating process of engine new(23)
Terminating process of engine base(19)
Finished game 8424 (base vs new): 0-1 {Black wins by adjudication}
Score of new vs base: 1183 - 1113 - 6129  [0.504] 8425
Started game 8431 of 60000 (new vs base)
Warning: EngineProcess: pipe reader was terminated
TerminatinWarning: EngineProcess: pipe reader was terminated
g process of engine new(15)
Terminating process of engine bWarning: EngineProcess: pipe reader was terminated
ase(16)
Warning: EngineProcess: pipe reader was terminated
Terminating process of engine new(14)
Finished game 8422 (base vs new): 1-0 {White wins by adjudication}
Score of new vs base: 1183 - 1114 - 6129  [0.504] 8426
Started game 8432 of 60000 (base vs new)
...

This obviously is not ideal as my computer only has 8 cores, so the CPU will be overloaded until the next 3 games aren't finished.

**Comment by ilaripih** [comment]
I think you ran into this bug, which is fixed: https://github.com/cutechess/cutechess/issues/91

Can you try installing the latest version of Cute Chess: https://github.com/cutechess/cutechess/releases/download/gui-0.9.1/cutechess_setup.exe
The package installs both the Cute Chess GUI and cutechess-cli.

**Comment by pb00068** [comment]
@ilaripih I can confirm that this bug is fixed by #91 
Thank you and sorry for the noise!
