### ISSUE TITLE
Cannot start Komodo 9.x

### ISSUE THREAD

**Issue by ilaripih** [cutechess/cutechess#126]
It was reported at Talkchess.com that Cute Chess GUI 0.9.2 cannot start Komodo 9.x process. There's nothing in Engine Debug widget and this error message is shown to the user:

`Terminating process of engine komodo-9(1)`

**Comment by ilaripih** [comment]
Here's a Windows 64-bit executable of Cute Chess 0.9.2 that opens a console and outputs any warnings and debug info there. The executable should be copied in the Cute Chess installation folder where all the dll dependencies are.

[cutechess_with_console_win64.zip](https://github.com/cutechess/cutechess/files/460900/cutechess_with_console_win64.zip)

**Comment by mcostalba** [comment]
Crash reproducible with [Rybka 2.3.2](http://www.rybkachess.com/index.php?auswahl=Demo+version), just start a new human game against Rybkav2.3.2a.mp.x64.exe and try to play some moves.

The console version does not helps (nothing is shown)

**Comment by ilaripih** [comment]
The Rybka issue may not be connected to this (Komodo 9.x does not crash Cute Chess), so I opened a new issue about it.

**Comment by ilaripih** [comment]
Based on gdb's output, it looks like Komodo crashes with SEGFAULT:

```
[Thread debugging using libthread_db enabled] 
Using host libthread_db library "/usr/lib/libthread_db.so.1". 
process 20231 is executing new program: /home/tobias/chess/engines/Komodo/komodo-9_11b14c11/Linux/komodo-9.02-linux 
[Thread debugging using libthread_db enabled] 
Using host libthread_db library "/usr/lib/libthread_db.so.1". 
[New Thread 0x7fffe1977700 (LWP 20232)] 

Thread 2.1 "komodo-9.02-lin" received signal SIGSEGV, Segmentation fault. 
[Switching to Thread 0x7ffff7fc0600 (LWP 20231)] 
0x00007ffff71f9b64 in fclose@@GLIBC_2.2.5 () from /usr/lib/libc.so.6 
(gdb) Engine Komodo 9.02 64-bit(0) failed to respond to ping 
Terminating process of engine Komodo 9.02 64-bit(0) 
quit
```

**Comment by ilaripih** [comment]
I confirmed that Komodo crashes, but that's because Cute Chess sends "setoption" commands to Komodo that it shouldn't send. Options of type "button" shouldn't ever be sent automatically.

**Comment by ilaripih** [comment]
The "button" options were the culprit. Fixed.
