### ISSUE TITLE
Request for status bar/pane that acts as a dashboard of UCI info items

### ISSUE THREAD

**Issue by kervinck** [cutechess/cutechess#136]
[ Split-off from issue #135, because this is really a separate feature suggestion ]

CuteChess GUI 0.9.2 doesn't have a status pane now, but I think it might be useful to have one, acting like a "dashboard" that can show things such as Mnps, ponder move, TB hits, hashfull, search progress (currmove, currmovenumber), or whatever the user wants. In CuteChess-style of course infinitely configurable by dragging and clicking around :-) :-)

Many GUI's have some similar status area, usually as a horizontal bar with indicators next to each other (but never configurable).

Such an area can then also clear up the need for horizontal space in the evaluation tabs, as for many indicators coming from UCI info-strings only the most recent is really relevant. Specifically the "nodes" column is meaningless (in my view), but Mnps, hashfull, pondermove, are important (to me).

**Comment by ilaripih** [comment]
Discussion can be continued at issue #74. I'm closing this one as a duplicate.
