### ISSUE TITLE
"Scores from white perspective" should not be per-engine

### ISSUE THREAD

**Issue by mcostalba** [cutechess/cutechess#150]
IMO it is a tournament/game setting not an engine setting, because makes no sense for engines in the same tournament to have a different set: the resulting move list difficult to understand and unnecessarily odd. Moreover you need to adjust each engine setting before the tournament (!)

While there, I'd suggest to leave the default as white perspective because it is the most used and common.

**Comment by ilaripih** [comment]
Actually I should disable that option completely for UCI engines - it's meant for Xboard engines that report scores from white's perspective. For some reason the Xboard protocol doesn't dictate the point of view for engine scores, which is a serious oversight.

**Comment by ilaripih** [comment]
Okay, it's less confusing now. Later there will be a separate global setting for this.

**Comment by ilaripih** [comment]
I created a new issue about the global setting: https://github.com/cutechess/cutechess/issues/162
