### ISSUE TITLE
Confirmation for closing active tournament game

### ISSUE THREAD

**Issue by elcabesa** [cutechess/cutechess#157]
when playing a tournament with more than one concurrent game you can follow a game selecting it from the upper tab.
if you accidentally press the red X in the tab you close the tab and the game ends with a disconnection.
I thinnk this is unwanted, maybe you can disable it for tournament or popup a confirmation window. ( possibile without stopping the tournament)

thank you

**Comment by ilaripih** [comment]
I still think it should be possible to force an end to a tournament game, but there should be a confirmation dialog where the user could choose a result for the game or cancel the stoppage.

**Comment by ilaripih** [comment]
There's now a confirmation dialog. Choosing a result for the game may come later if it's needed.
