### ISSUE TITLE
Assert at line 164 in gui/src/movelist.cpp

### ISSUE THREAD

**Issue by zd3nik** [cutechess/cutechess#16]
When I run an engine tournament I hit the assert in movelist.cpp at line 164 after the first game finishes:

  Q_ASSERT(moveNum >= 0 && moveNum < m_moveCount);

m_moveCount is 0 when this happens.  I haven't debugged it to figure out exactly what's going on, but I suspect it's trying to select the last move of the previous game after it has already reset the position to SARTPOS for the next game.

To work around it I've added this before the assert:

  if (m_moveCount <= 0)
    return;

**Comment by ilaripih** [comment]
Thanks for the report! MoveList::selectChosenMove() is called by a timer with a 50 millisecond delay, so a new game could start before the timer from the previous game fires. I think the proper way to fix this is to stop the timer in MoveList::setGame() with:

`m_selectionTimer->stop();`

**Comment by ilaripih** [comment]
I managed to reproduce the issue easily and committed a fix. Thanks for reporting this!

**Comment by zd3nik** [comment]
Excellent.  Thanks!
