### ISSUE TITLE
cannot parse "[-]" in Crazyhouse FEN

### ISSUE THREAD

**Issue by ilaripih** [cutechess/cutechess#163]
`Chess::Board::setFenString` fails when it's given a Crazyhouse FEN like this:
`rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[-] w KQkq -`

The `[-]` means that there are no hand pieces.

**Comment by mcostalba** [comment]
Incredible!

Why [-] and not simply [] ?  

Crazyhouse....crazy protocol :-)

**Comment by ilaripih** [comment]
I'd prefer to drop the brackets completely if there are no hand pieces. But whoever made the first PGN implementation of Crazyhouse got to define the de facto standard.
