### ISSUE TITLE
In tournament results some names are missing

### ISSUE THREAD

**Issue by mcostalba** [cutechess/cutechess#164]
In tournament results some names are missing (the rank 0 is SF)

https://snag.gy/cuBJXp.jpg

**Comment by ilaripih** [comment]
Is there a way to reproduce this or is it completely random when this happend? The tournament type seems to be Gauntlet?

**Comment by mcostalba** [comment]
Yes it it is gauntlet. I am sorry I can't try again now, I am away from my
pc.

**Comment by ilaripih** [comment]
I fixed one place in the code where the names could've been set to empty but I'm not sure if it fixes this issue because I couldn't reproduce it.

**Comment by mcostalba** [comment]
Thanks I will check this. I have done nothing strange, just selected the
engines all in one go with ctrl + mouse click, only the last selected one
got the name.

**Comment by ilaripih** [comment]
Did you find a way to reproduce the problem with the latest master?

**Comment by mcostalba** [comment]
@ilaripih I will test this week-end when i'll come back home...

**Comment by mcostalba** [comment]
I have retested this morning but i can't reproduce the bug anymore. Sorry, I have tested for about 10 times starting and stoppin a tournament but withouth any result.

**Comment by ilaripih** [comment]
That sounds like my previous commit may have fixed it. I'm closing this issue, but please re-open if you encounter the bug again.
