### ISSUE TITLE
Cute Chess doesn't detect all uci options from the Carballo chess engine

### ISSUE THREAD

**Issue by insanetesterftw** [cutechess/cutechess#179]
Carballo is a Java chess engine (https://github.com/albertoruibal/carballo/).

This is its UCI output:

> uci
> id name Carballo Chess Engine v1.6
> id author Alberto Alonso Ruibal
> option name Hash type spin default 64 min 16 max 1024
> option name Ponder type check default true
> option name OwnBook type check default true
> option name UCI_Chess960 type check default false
> option name Evaluator type combo default complete var simplified var complete var experimental
> option name Contempt Factor type spin default 90 min -200 max 200
> option name Elo type spin default 2100 min 500 max 2100
> uciok

Cute Chess only detects the following:

> option name Hash type spin default 64 min 16 max 1024
> option name OwnBook type check default true
> option name Evaluator type combo default complete var simplified var complete var experimental
> option name Contempt Factor type spin default 90 min -200 max 200
> option name Elo type spin default 2100 min 500 max 2100

**Comment by ilaripih** [comment]
By "detecting" do you mean showing the option in the Engine Configuration dialog? And is this a problem? Ponder and UCI_Chess960 are not supposed to be user-configurable engine options; they just tell the GUI what capabilities the engine has.

**Comment by insanetesterftw** [comment]
> By "detecting" do you mean showing the option in the Engine Configuration dialog? 

Yes.

> Ponder and UCI_Chess960 are not supposed to be user-configurable engine options; they just tell the GUI what capabilities the engine has.

Then it isn't a problem. My mistake. I'm sorry. Thank you.

**Comment by insanetesterftw** [comment]
I now realize that I didn't say which versions I was using. Here they are:

Windows 7 (64bit)
Cute Chess GUI 0.9.4
Carballo 1.6 (https://github.com/albertoruibal/carballo/)
Carballo 1.7

**Comment by ilaripih** [comment]
No apologies needed, the UCI protocol is quite unclear about these things. Anyway, Cute Chess handles the Pondering and UCI_Chess960 options behind the scenes. If UCI_Chess960 is sent by the engine, then Cute Chess will allow the engine to play the "fischerandom" variant. And if Pondering is sent, then Cute Chess will ask the engine to ponder if "thinking on opponent's time" is checked.

I'm closing this issue.
