### ISSUE TITLE
cutechess-cli adjudication with TB doesn't take 50-move rule into account

### ISSUE THREAD

**Issue by Prcuvu** [cutechess/cutechess#181]
When it reaches a TB position which is a draw under 50-move rule but a win without the rule, cutechess-cli always adjudicates to a win.

Edit: cutechess still uses Gaviota TB, seems more necessary to switch to syzygy.

Reference:
* http://tcec.chessdom.com/archive.php?se=9&rapid&ga=312
* http://tcec.chessdom.com/archive.php?se=9&sf&ga=17
* #68

**Comment by ilaripih** [comment]
Syzygy solves this and there's a unit test for the TCEC position in question.
