### ISSUE TITLE
Usage of a winboard engine through Wb2Uci adapter not functional

### ISSUE THREAD

**Issue by alg4032** [cutechess/cutechess#182]
I'm trying to get the old Chessmaster engine (King323.exe) working in cutechess.

Unfortunately it doesn't support xboard protocol 2 so the "setboard" command which I want to make use of is not available.

So what I tried was to use the Wb2Uci adapter. There are two files "Wb2Uci.exe" and "Wb2Uci.eng" in the same folder as the engine. Wb2Uci.exe is included as the engine in cutechess and Wb2Uci.eng is obligatory and must be in the same folder as Wb2Uci.exe.

This method works with Fritz GUI or when Wb2Uci.exe is started directly in the command line:
> uci
> id name The King 3.23
> id author Johan de Koning
> option name Hash type spin default 2 min 0 max 256
> option name Ponder type check default false
> uciok
> isready
> readyok

In cutechess however the "isready" command produces an error (match started with "cutechess -debug"):
> 65 >chessmaster(0): uci
> 521 <chessmaster(0): uciok
> 521 >chessmaster(0): isready
> 521 <chessmaster(0): info string Error starting engine.

The error can be reproduced in the command line mode if the file Wb2Uci.eng is deleted or renamed.
The cutechess executable, the engine and both files Wb2Uci.exe and Wb2Uci.eng are all in the same folder.

Is there a reason why additional files that are necessary for an engine to work (Wb2Uci.eng in this case) are not recognized when the engine is started through cutechess? Maybe there's a workaround?

**Comment by ilaripih** [comment]
I think the issue is with the working directory which cutechess sets by default to the system's temporary directory. Can you try setting the engine's working directory to the engine's folder, eg. `dir=C:\engines\chessmaster`.

**Comment by alg4032** [comment]
Defining a working directory for the engine solved the problem, thanks.

**Comment by ilaripih** [comment]
That's good to hear, thanks for the info.
