### ISSUE TITLE
"live" pgn

### ISSUE THREAD

**Issue by reppolice** [cutechess/cutechess#184]
Hi, I have the feeling the answer may be hiding right in front of my eyes, but I can't seem to find the option for "flushing" pgnout, ie. maintaining a live file. Is it an undocumented feature?

**Comment by ilaripih** [comment]
PGN is not a suitable format for streaming live games because the tags will change as the game progresses. So Cute Chess will only save the PGN when a game is finished. But of course you can manually save a game in progress with the Game -> Save menu option.

**Comment by ilaripih** [comment]
We have plans for a live game/tournament broadcasting feature which would make a live PGN output feature redundant. That's why I'm closing this.

**Comment by ddugovic** [comment]
I understand the project maintainers won't officially support this feature.

I'm trying to [broadcast engine-engine blitz matches on Lichess](https://lichess.org/broadcast/sunsetter-stockfish-55-challenge/A6MckskJ) so if someone smart could provide some guidance on how to DIY this (it sounds very challenging to do) I'd appreciate it. :-(

**Comment by mtvec** [comment]
A "Live PGN" format (supposedly produced by DGT boards) is [natively supported by Lichess](https://lichess.org/page/broadcasts). I understand PGN might not be the optimal format for broadcasts but it seems to be used nonetheless. It would be very nice to be able to stream matches from cute chess to Lichess so could this feature be reconsidered?
