### ISSUE TITLE
Fix outstanding issues from Coverity scan

### ISSUE THREAD

**Issue by artoj** [cutechess/cutechess#187]
Outstanding issues from Coverity scan on December 3rd, 2016: https://scan.coverity.com/projects/cutechess-cutechess/view_defects

**Comment by artoj** [comment]
I tried to modify the analyzing configuration so that it would ignore *.moc and moc_* but apparently it's not working correctly. I marked findings in those files as "Ignore".

**Comment by ilaripih** [comment]
I've fixed the issues, except for the issues in QCustomPlot. If the current QCustomPlot version still has defects we should report them upstream.

**Comment by ilaripih** [comment]
I fixed the last remaining defect in Cute Chess code and reported the QCustomPlot defects to the QCustomPlot support email.

**Comment by 0zymandia2** [comment]
So, are we waiting on a reply from QCustomPlot support? 

I notice that the "Realtime engine statistics" enhancement, only affects the GUI. Sorry to be a bother, but I really look forward to the new cli version.

**Comment by ilaripih** [comment]
No, we're not waiting for that. Actually I could release the new cli already because the pending changes only affect the GUI. Which OS do you use?

**Comment by 0zymandia2** [comment]
Win64 (7 & 8)

**Comment by artoj** [comment]
I'll close this as the issues affecting our code were fixed.

**Comment by ilaripih** [comment]
I updated the `coverity_scan` branch. QCustomPlot has also updated since the last scan so interesting to see what happens now.
