### ISSUE TITLE
CLI engine match repeat opening N times

### ISSUE THREAD

**Issue by ddugovic** [cutechess/cutechess#188]
Currently documentation suggests:
`-repeat		Play each opening twice so that both players get to play it on both sides`

I suggest enabling an opening to be repeated N times, which may be useful if using an opening book and selecting openings randomly:
`-repeat [N]		Play each opening twice (or N times) so that both players get to play it on both sides`

**Comment by alwey** [comment]
This is about controlling the  sequence of game setups - also related: #95

**Comment by ilaripih** [comment]
Now only the GUI part is left.
