### ISSUE TITLE
Pondering

### ISSUE THREAD

**Issue by mcostalba** [cutechess/cutechess#19]
Feature request: add pondering support.

For engine vs engine it is the latest 'big' feature missing.

**Comment by ilaripih** [comment]
I agree that this should be the next major feature. It's quite easy to implement for Xboard but for UCI the implementation must be considered carefully because of the asynchronous nature of things.

**Comment by ilaripih** [comment]
Done, but possibly not rock solid yet. As I expected, almost all the changes are to the UciEngine class. Hopefully we'll receive some feedback about how this works.
