### ISSUE TITLE
GUI crash on mate by pawn promotion

### ISSUE THREAD

**Issue by alwey** [cutechess/cutechess#202]
Setup new game (standard chess, human players) and enter the setup position
`rnbkqb1r/pppP1ppp/8/8/2PN4/1P6/P2PQPPP/RNB1KB1R w KQ - 0 1`

White has the chance to promote the Pawn on d7. If they do so, promotion to Queen will be checkmate. The GUI crashes after clicking on the Queen symbol. If converting to Rook, Bishop or Knight, then there is no mate and the GUI does not crash.

**Comment by alwey** [comment]
Swapping `stopAnimation` and `cancelUserMove` in `OnGameFinished` seems to help.

```
--- a/projects/gui/src/boardview/boardscene.cpp
+++ b/projects/gui/src/boardview/boardscene.cpp
@@ -349,8 +349,8 @@ void BoardScene::onGameFinished(ChessGame* game, Chess::Result result)
 {
        Q_UNUSED(game);
 
-       stopAnimation();
        cancelUserMove();
+       stopAnimation();
 
        auto text = new QGraphicsTextItem(result.toShortString(), m_squares);
        auto font = text->font();

```

**Comment by ilaripih** [comment]
Thanks for the bug report. The proposed fix prevents crashing but also cancels the whole promotion move in the GUI, which we don't want. Since `PieceChooser` will destroy itself after the piece has been chosen, it's safest to just set the `m_chooser` pointer to `nullptr`.
