### ISSUE TITLE
fails to compile on arm platform

### ISSUE THREAD

**Issue by flok99** [cutechess/cutechess#204]
Trying to build cutechess-cli on the raspberry pi fails with:

gcc -c -pipe -std=c99 -O2 -fPIC -Wall -W -D_REENTRANT -DLIB_EXPORT= -DZ_PREFIX -DNDEBUG -DQT_NO_DEBUG -DQT_CORE_LIB -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I. -Isrc -Icomponents/json/src -I3rdparty/fathom/src -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I.moc -o .obj/tbprobe.o 3rdparty/fathom/src/tbprobe.c
3rdparty/fathom/src/tbprobe.c:33:23: fatal error: x86intrin.h: No such file or directory
 #include <x86intrin.h>
                       ^
compilation terminated.

Removing that include fixes the problem, at least for arm/rpi2.

**Comment by ilaripih** [comment]
Thanks for the report. Obviously we should include `x86intrin.h` only on x86 platforms.

**Comment by ilaripih** [comment]
Fixed.
