### ISSUE TITLE
Option to adjust piece animation speed

### ISSUE THREAD

**Issue by Nordlandia** [cutechess/cutechess#207]
In my experience current piece animation speed adds an delay between moves. 

In fritz gui there is a slider for this. 

I always play with piece animation off. 

Discuss :)

![fritz1](https://cloud.githubusercontent.com/assets/26534454/24088789/1c8de5be-0d2f-11e7-8249-92ce90461700.png)

**Comment by ilaripih** [comment]
The animation should not add any delay because if the next move is made by an engine before the previous move's animation is finished, the animation skips immediately to the end.

But I agree that there should be an option to turn piece animation completely off.

**Comment by Nordlandia** [comment]
Moreover there should be an option to autosave engine games. 

I have to manually save each casual engine game.

**Comment by ilaripih** [comment]
That sounds good. Could you please open a new issue about it?
