### ISSUE TITLE
Autosaving single engine games

### ISSUE THREAD

**Issue by Nordlandia** [cutechess/cutechess#208]
Playing single engine games without saving it as .pgn (after game is finished) makes it impossible to restore game data, if you closes the gui. 

It should be an option to autosave to "Game Database" or desired directory. 

It's just a suggestion.

Cheers :)

**Comment by alwey** [comment]
+1 for this enhancement

DefaultPGNFile _string_ (save to this file if set)

Somehow related to #210 (suggestion: show a Warning Dialog if no output file is given for a tournament and DefaultPGNFile is not set)

**Comment by Nordlandia** [comment]
Yes, they are closely related. 

Approximately how long until next cutechess release at this point?

https://github.com/cutechess/cutechess/milestones

**Comment by alwey** [comment]
problem is part (or duplicate) of #147

**Comment by alwey** [comment]
@Nordlandia : The authors have shown their long-term dedication to this project. I assume that no updates can be expected when in conflict with real-life requirements.

**Comment by ilaripih** [comment]
@alwey I think at this point we could consider you as one of the authors, you've contributed so much to this project. As for me and Arto, yes we're very busy but we'll still have our annual Cute Chess hackathon in July. I'd like to do a release before it, but if I don't, we'll definitely release a new version during the hackathon.

**Comment by alwey** [comment]
@ilaripih: I feel honoured. Regarding a release, I also think that a minor (beta) release 0.9.x is interesting before the Hackathon. Actually, I have some code lying here for some months, e.g. `ShatranjBoard` and `CourierBoard `, among others. I should also work on a "final" _Losing Chess_ version (PR 200), the beta version of which has been tested by the Multi-Variant Stockfish/Fishtest developers fore some time.
