### ISSUE TITLE
Configurable default PGN output file for tournament games

### ISSUE THREAD

**Issue by fsmosca** [cutechess/cutechess#210]
![image](https://cloud.githubusercontent.com/assets/22366935/26037032/61b84e12-391d-11e7-9578-9f4a25d80530.png)

**Comment by alwey** [comment]
suggestion: show a Warning Dialog if no output file is given for a tournament and DefaultPGNFile is not set.

**Comment by ilaripih** [comment]
We're going to add an option for default PGN output file to SettingsDialog's Tournament tab. I believe it would solve the problem, and it would not needlessly annoy those who don't want to save all tournament games to disk.

**Comment by ilaripih** [comment]
Done by @alwey

**Comment by rwbc** [comment]
Does this really work for tournament games?

I have specified a default pgn, but it seems no games of tournaments in case I forgot to specify a pgn file in the tournament
dialogue is saved there.

according line from my cutechess.ini
```
[games]
default_pgn_output_file=C:/test.pgn
```
