### ISSUE TITLE
Weird Evaluation History plot after a game

### ISSUE THREAD

**Issue by fsmosca** [cutechess/cutechess#212]
![image](https://cloud.githubusercontent.com/assets/22366935/25776677/b5531664-32f7-11e7-8d33-2a7653c7eb17.png)

**Comment by ilaripih** [comment]
I think this is fixed now. Please re-open the issue if it occurs again with the latest code. There's still a separate bug relating to the `EvalHistory` widget: https://github.com/cutechess/cutechess/issues/233
