### ISSUE TITLE
Request: Release GUI and cli for windows

### ISSUE THREAD

**Issue by fsmosca** [cutechess/cutechess#216]
It has been a long time since the windows release and there are a lot of changes too. Perhaps it is better to release a new versions for GUI and cli. This would allow the program to be tested by those people who are on windows OS.

**Comment by sandermvdb** [comment]
Really looking forward to a new version as well!

**Comment by Nordlandia** [comment]
Last updated 4 months ago

Look forward to new version.

**Comment by 0zymandia2** [comment]
That's the date from the last patch, but the last release is more than [8 months old](https://github.com/cutechess/cutechess/releases), and doesn't include such important changes as 6-men adjudication.
Mid February, it looked like a [done deal](https://github.com/cutechess/cutechess/issues/187#issuecomment-279730567), but since then we've got radio silence.

**Comment by Nordlandia** [comment]
Do new version support manual adjudication?

#211

**Comment by ppigazzini** [comment]
@fsmosca [here](https://github.com/ddugovic/Stockfish/wiki/How-To-build-cutechess-with-Qt-5-static) the instructions to build yourself cutechess for windows & linux: very easy.

**Comment by ppigazzini** [comment]
@fsmosca windows 64 bit fresh compile:
[cutechess.zip](https://github.com/cutechess/cutechess/files/1034309/cutechess.zip)
[virustotal link](https://www.virustotal.com/en/file/008ddd40bfe566d7e412da89ac84d183b44c646cbebd1d9296000b998eee1578/analysis/1495987949/)(recheck yourself)

**Comment by fsmosca** [comment]
@ppigazzini 

>here the instructions to build yourself cutechess for windows & linux (with Qt5 static): very easy. Never thoroughly tested the GUI version, though.

Thanks for the hint. But I am not compiling this thing anymore as my main pc where I compile things died a week ago.

From time to time there are people asking latest compile from here.
http://www.talkchess.com/forum/viewtopic.php?topic_view=threads&p=716648&t=61501

**Comment by fsmosca** [comment]
@ppigazzini 
> windows 64 bit GUI & cli fresh compile:
170528-cutechess.zip
virustotal link (double check yourself)

Could you also compile the 32bits?

**Comment by fsmosca** [comment]
@Nordlandia 

>Do new version support manual adjudication?

No, not yet implemented, probably implemented later.

**Comment by ppigazzini** [comment]
@fsmosca windows 32 bit GUI & cli fresh compile:
[170528-cutechess-32bit.zip](https://github.com/cutechess/cutechess/files/1034575/170528-cutechess-32bit.zip)

[virustotal link](https://www.virustotal.com/en/file/6610cb20845f2ca71c68cb9a4a240c727af4cc25cb743b7f6e8a2682940e0c82/analysis/1496011981/) (there is one alarm by Invincea)

**Comment by fsmosca** [comment]
Closing this issue now, thanks again to ppigazzini for providing windows compiles after 1883 commits.
