### ISSUE TITLE
False PV in TCEC

### ISSUE THREAD

**Issue by mstembera** [cutechess/cutechess#22]
Issue described and examples given here.
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/gHBayWju9z4

**Comment by ilaripih** [comment]
Official CuteChess does not do anything with the PVs given by engines. PV support was added to the TCEC fork of CuteChess: https://github.com/jeremybernstein/cutechess

I checked it, and their implementation seems correct: it takes the PV given by the engine and converts the moves into SAN format. It would be easy to tell if there's a bug in CuteChess if I could see the original PVs.

**Comment by mstembera** [comment]
@ilaripih 
Thank you for investigating!  I wanted to open an issue for Jeremys TCEC version but the Issues option seems to be missing there.  If you know how to contact him please do or let me know how.  Feel free to close this or leave it open as you see fit.  Thanks again!

**Comment by jeremybernstein** [comment]
Thanks, message received. I enabled issues on my fork, as well.

**Comment by mstembera** [comment]
@jeremybernstein 
Great.  Thank you!

**Comment by ilaripih** [comment]
I think I'm still going to make sure that CuteChess parses the pv moves correctly, but if I can't find a bug there I'll close this issue.

**Comment by ilaripih** [comment]
I added a new unit test just to make sure that CuteChess correctly parses both the chosen move and the PV move in the first example. Doesn't look like there's a bug.

My guess is that there's also no bug in the TCEC version of CuteChess - the simplest explanation is that sometimes an engine changes its mind at the last second and sends the move without sending a new PV.

**Comment by mstembera** [comment]
In the example you give should it not just show a 1 move PV with the correct move?  (Also there are several different engines doing this.)  Thanks.
