### ISSUE TITLE
ELO error margins

### ISSUE THREAD

**Issue by FabioGobbato** [cutechess/cutechess#23]
With every ELO score printed by cutechess would be useful to have also the ELO error margins.

**Comment by mstembera** [comment]
I was about to kindly ask for the same thing when I noticed this already being opened.  Thanks Fisherman

**Comment by ilaripih** [comment]
Done. The implementation should be pretty good for matches between two engines but for tournaments with many players I still recommend using something like BayesELO.

**Comment by mstembera** [comment]
Thank you for this non trivial patch!  Looking forward to the next release version.
