### ISSUE TITLE
Use qUtf8Printable() instead of qPrintable() for logging

### ISSUE THREAD

**Issue by artoj** [cutechess/cutechess#237]
As per Qt documentation:

> Note: qDebug(), qInfo(), qWarning(), qCritical(), qFatal() expect %s arguments to be UTF-8 encoded, while qPrintable() converts to local 8-bit encoding. Therefore qUtf8Printable() should be used for logging strings instead of qPrintable().

**Comment by ilaripih** [comment]
Done
