### ISSUE TITLE
Compile v1.0.0 for windows 32bit

### ISSUE THREAD

**Issue by fsmosca** [cutechess/cutechess#238]

**Comment by ppigazzini** [comment]
Windows 32 bit static build

[cutechess-v1.0.0-win32bit.zip](https://github.com/cutechess/cutechess/files/1220336/cutechess-v1.0.0-win32bit.zip)

VirusTotal checks:
[cutechess](https://www.virustotal.com/#/file/fd1905783b2ae6b617e34d29d38d5d0498a4790e7f3bd0fc173699c87eb3e468/detection)
[cutechess-cli](https://www.virustotal.com/#/file/1d907c893e700db9c87c51806736f12124b469801d9e6e93c52f66fc3231827f/detection)

Built with msys2 using this script:

  ```bash
  #!/bin/bash
  # http://stackoverflow.com/a/34001073/1583123

  # update and install packages
  pacman -S --noconfirm unzip make mingw-w64-i686-gcc mingw-w64-i686-jasper mingw-w64-i686-qt5-static

  # build cutechess-cli and cutechess
  wget https://github.com/cutechess/cutechess/archive/gui-1.0.0.zip
  unzip gui-1.0.0.zip
  cd cutechess-gui-1.0.0
  make -j 4
  strip projects/cli/cutechess-cli.exe
  strip projects/gui/cutechess.exe
  ```

**Comment by fsmosca** [comment]
Thank you @ppigazzini .
Closes #238

**Comment by ilaripih** [comment]
Awesome, thanks!

**Comment by ppigazzini** [comment]
@ilaripih I create and closed two issues to document how to build a static version of cutechess on Windows (#206) and on Linux (#259) (this is useful in projects as [Multi Variant Fishtest](https://github.com/ianfab/fishtest)). That content should be written in the Wiki, though. Can you change the Wiki permission?

**Comment by ilaripih** [comment]
@ppigazzini I enabled wiki edits for 3rd parties. Can you please make the needed wiki changes?

**Comment by Nordlandia** [comment]
Is it difficult to compile 64-bit version of windows? 

CuteChess GUI 64-bit.

**Comment by ppigazzini** [comment]
@ilaripih wiki page updated

@Nordlandia it's easy, check the [wiki page](https://github.com/cutechess/cutechess/wiki/Making-a-release#windows). Please remember that cutechess 32 bit works fine also on Windows 64 bit.

Here the Windows 64 bit static build:
[cutechess-win-64bit.zip](https://github.com/cutechess/cutechess/files/1229594/cutechess-win-64bit.zip)

VirusTotal checks:
[cutechess](https://www.virustotal.com/#/file/50649168567ba329f587dadb31286e6e78fff0c560f53d311f726e9ae5d7551e/detection)
[cutechess-cli](https://www.virustotal.com/#/file/386a44b692f46486b994c1b4f9bd494994dc411ef73db07eae2165935e618caf/detection)

**Comment by Nordlandia** [comment]
@ppigazzini many thanks :)

**Comment by Nordlandia** [comment]
Where are cutechess compiles located once completed?

**Comment by ppigazzini** [comment]
Updated the [wiki](https://github.com/cutechess/cutechess/wiki/Making-a-release#windows) page with some information about the MSYS2 path, added some information on how to launch the scripts.

**Comment by ppigazzini** [comment]
@ilaripih here the updated build scripts for Windows and Linux:
https://github.com/ianfab/fishtest/wiki/Build-cutechess-with-Qt5-static

If you enable (at least temporary) the wiki edits for 3rd parties I will glad to make the update.
