### ISSUE TITLE
The engines and variantions of chess game

### ISSUE THREAD

**Issue by sovaz1997** [cutechess/cutechess#254]
Hello! I would like to see in future versions of cutechess-cli/gui variations of chess game (atomic, horde, antichess, etc.) with support for engines (so that you can make tournaments and play with the engines in chess variations). Thank you!

**Comment by ianfab** [comment]
Cutechess already supports quite a lot of chess variants, see, e.g., [this list](https://github.com/cutechess/cutechess/blob/d50212b56ea66cb5590655f1ffec11395378ce21/projects/cli/res/doc/help.txt#L12-L43).

**Comment by sovaz1997** [comment]
Is there a description of UCI and FEN for these chess games?

**Comment by sovaz1997** [comment]
Checked Stockfish with chess variations, everything works. I think the topic can be closed.

**Comment by ianfab** [comment]
@sovaz1997 I do not know whether there is a documentation for the FENs from cutechess's side, but we have a [brief documentation on FEN extensions supported by multi-variant Stockfish](https://github.com/ddugovic/Stockfish/wiki/FEN-extensions). As you already found out, cutechess and Stockfish are compatible in this regard.
