### ISSUE TITLE
cutechess for Android

### ISSUE THREAD

**Issue by Alexei1981** [cutechess/cutechess#278]
It would be nice to port this program to
android (source code to remake). This
level of programs is not enough on the
android.

**Comment by Nordlandia** [comment]
Very good suggestion.

**Comment by Alexei1981** [comment]
Hi. I was able to compile cutechess on
android and I tried to run it through the
terminal, but the exit code-11 error got
out. I used gcc-7.2 and Qt-5.8.I
understand that a dynamic library is
needed to run?

**Comment by Alexei1981** [comment]
I was able to compile cutechess on
android and run through the terminal.
The program does not fit on the screen,
you need to make all the options be
displayed separately, through the menu.
Here are the screenshots.

**Comment by ilaripih** [comment]
I don't see any screenshots
