### ISSUE TITLE
Time forfeits with fixed time per move

### ISSUE THREAD

**Issue by joergoster** [cutechess/cutechess#281]
Does it make sense to check for time forfeits in fixed time per move mode?
For example
```
[FEN "1B2R3/8/8/8/7r/8/8/3K2k1 w - -"]
[PlyCount "2"]
[SetUp "1"]
[Termination "time forfeit"]
[TimeControl "0.25/move"]

1. Ke2 {+0.97/18 0.25s} Ra4 {-0.86/17 0.25s, White loses on time} 0-1
```
I was trying to use 250 ms per move with cutechess-cli. Just like in fixed depth ('go depth') and fixed nodes ('go nodes') situation, it doesn't seem appropriate to check for time-forfeits with 'go movetime'.

**Comment by ilaripih** [comment]
It may not be appropriate in all situations. But you can use the `timemargin` engine option to make sure there are no time forfeits if the engine uses a little bit too much time.

**Comment by joergoster** [comment]
Yes, I know. I consider this more a question of design. It was a big surprise for me to see the time-forfeit message here. ;-)
All three modes, fixed nodes, fixed depth and fixed search time, are totally independent of time management, imho.

Do you also check if the engine is overstepping the searched depth or nodes in fixed depth or fixed nodes mode? If no, then it seems illogical to do it with fixed search time.

**Comment by alwey** [comment]
There is a qualitiative difference between search depth and nodes count on one hand and time per move on the other: It is easy for the UI to check plausibility of time limits but /wrt node count and depth it has to rely on the engines.

**Comment by joergoster** [comment]
@alwey But only because it is possible to check for one case doesn't necessarily mean it is useful to do so.

**Comment by Nordlandia** [comment]
@alwey good to have you back 🙂

**Comment by alwey** [comment]
@joergoster In my opinion, checking for timing problems is useful indeed. This allows users to observe problems of either an engine or of cutechess or the testing platform. As mentioned. the parameter `timemargin` will allow some adjustment of testing conditions.  I can barely imagine a use case that would require an extra overhead per move.

**Comment by Disservin** [comment]
@joergoster I just came across this issue when writing my own tournament manager and it looks like to me at least that even stockfish uses (much) more time than given under certain scenarios. 
My command was `go movetime 100` and the last info line stockfish reported before bestmove was sent was 
`info depth 22 seldepth 24 multipv 1 score cp 12 nodes 82626 nps 581873 hashfull 38 tbhits 0 time 142 pv g3g4 e5f6 g4f4 f7e6 e3c5 f6d8 c5a7 d8e7 a7d4 e7h4 f4e3 h4g5 e3d3 g5d8 d4e3 e6e5 f2f3 d8e7 d3c3 e5f6 c3c4 f6e6` ... 40ms higher! Im not sure where this big time difference comes from because it surely cant be from my side.

**Comment by joergoster** [comment]
Hi @Disservin , this is just a guess, but when SF checks time in `MainThread::check_time()`, there is a `callsCnt` variable still set to 1024. This was sufficient with HCE, but with NNUE, eval takes a bit longer in general. So reducing this to say 512 or even 256 should result in finer granularity at very short move times.
