### ISSUE TITLE
Support Ministers Chess

### ISSUE THREAD

**Issue by Nordlandia** [cutechess/cutechess#291]
Chess on a 9x9 Board using 36 pieces instead of the standard 32. The 9x9 board is symmetrical. Each players gets 1 additional pawn and 2 "Ministers" which replace the Queen and move in the same manner as the Queen.

Square e5 is the ultimate center and 2Qs may present some interesting positions/imbalances on the board, despite Viktor Kortschnoi acknowledged that 2Qs tend to be redundant with many pieces present. 

Shares some similarities to Modern Chess.

https://boardgamegeek.com/boardgame/27643/ministers-chess

**Comment by alwey** [comment]
I see _Ministers Chess_ is a trademarked game. I would rather implement _Modern Chess_ by Gabriel Maura, of Puerto Rico. This game was introduced in 1968, and became popular in the Spanish speaking countries in Central America, South America and Europe.

I do prefer original (older) and free variants to proprietary and slightly modified games.

**Comment by alwey** [comment]
The closest variant to Ministers Chess that I found is _Chancellor Chess_ by Benjamin R. Foster, introduced in 1887. It is played on a 9x9 board. Each side has a Queen on the d-file and a Chancellor (R+N) on the f-file. I just implemented this variant.

Using the FEN setup edit field one could enter different starting positions, e.g. with two Queens.

Default FEN "rnbqkcnbr/ppppppppp/9/9/9/9/9/PPPPPPPPP/RNBQKCNBR w KQkq - 0 1" 
![cha2](https://user-images.githubusercontent.com/6425738/32421594-8c950cae-c29a-11e7-88eb-8c1bbe0addeb.png)

Using FEN "rnbqkqnbr/ppppppppp/9/9/9/9/9/PPPPPPPPP/RNBQKQNBR w KQkq - 0 1"![xm2](https://user-images.githubusercontent.com/6425738/32421600-9d3cf8d2-c29a-11e7-99aa-87b589b261dd.png)

**Comment by Nordlandia** [comment]
@alwey nice find. 

Btw i wounder how much more light-square bishop is worth than dark-square on 9x9 board?

**Comment by alwey** [comment]
@Nordlandia  The playing strength of the bishops could be tested with engine help. Set up the sides differently and let them play a series of games. I attached a modification for the _Sjaak II_ `variants.txt` file to the PR #300 so the engine can play these variants.

**Comment by alwey** [comment]
@Nordlandia :  I  suggest using the set-up with two Queens depicted above and not cheating by promoting any pawns to Chancellor. Then ChancellorBoard (variant string `chancellor`) which is already part of recent master versions should suit your needs. What we should avoid is using a trademark, since trademarks have to be defended to stay valid.
https://en.wikipedia.org/wiki/Trademark#Enforcing_rights

So I would like to ask you to close the issue.
