### ISSUE TITLE
Setting: Reversed color

### ISSUE THREAD

**Issue by Ipmanchess** [cutechess/cutechess#297]
Request: To make it possible to play with reversed color in eng-eng games with Cutechess 1.0 Gui!
"Play each opening twice so that both players get to play it on both sides"

Now i try it with Round=2 ,but uses different openings..

Kind regards,
Ipman.

**Comment by Ipmanchess** [comment]
Okay i get it solved with the help on TCEC chat..
Reversed color games works now perfect with PGN & EPD files ,only when you put Plies high enough!
With BIN book it doesn't work ,even i put Depth higher..only first two games are reversed color ,but the next games not anymore?
I think the problem here is that with BIN the first 3games using same opening,and from the 4th games it changes..but of course the following games have all different openings?
Maybe you can check this out!

Thanks..
Ipman.

**Comment by alwey** [comment]
Confirmed, this is a bug. The problem with repeating book moves from polyglot books was introduced by my commit on 2017-08-24  "_new optional parameter n for -repeat, new option -noswap to not swap sides of paired engines_". This is disappointing, sorry.

**Comment by alwey** [comment]
@Ipmanchess : Thank you for reporting this problem.

**Comment by Ipmanchess** [comment]
@alwey: is my pleasure..and if i'm right you have already a fix for it!
Is it then possible to get a new Cutechess Gui 1.0.1 .exe for windows ;)

Thank you,
Ipman.

**Comment by ilaripih** [comment]
Thanks for the fix @alwey and thanks for reporting the bug @Ipmanchess!
You're right, it's soon time for another release. Just a couple of bugs to fix first...
