### ISSUE TITLE
unbuffered output

### ISSUE THREAD

**Issue by jdart1** [cutechess/cutechess#299]
Would be nice to have an option for unbuffered output in cutechess-cli. I have a tool that monitors the logs and it has to wait for the output buffer to fill.

**Comment by ilaripih** [comment]
cutechess-cli should already have unbuffered output: https://github.com/cutechess/cutechess/blob/master/projects/cli/src/main.cpp#L658

Maybe your tool is buffering its input?

**Comment by jdart1** [comment]
I just do redirection (stderr and stdout) into a file from the shell, and that seems to be buffered.

**Comment by ilaripih** [comment]
Which OS do you use?

**Comment by jdart1** [comment]
Primarily Linux.

**Comment by jdart1** [comment]
I think the shell is buffering the output. It is possible to use unbuffer (part of expect-dev package) to prevent this. So closing this issue.
