### ISSUE TITLE
Some bugs detected

### ISSUE THREAD

**Issue by lahwaacz** [cutechess/cutechess#3]
1) Castling should not be done by dragging king over rook, but by moving the king two squares towards a rook.
2) Also please add some option in menu to disable the dots showing possible moves - it's kind of annoying...
3) When adding engine using the "Add Engine" dialog and everything in "Basic" tab is empty, clicking on "Advanced" tab causes Cutechess to crash with http://pastebin.com/QXz5kKqq

**Comment by ilaripih** [comment]
A setting to enable/disable the dots is now a part of another issue, so I'm closing this one.
