### ISSUE TITLE
Usage of obsolete Qt functions

### ISSUE THREAD

**Issue by ilaripih** [cutechess/cutechess#30]
We're using these obsolete Qt functions in quite a few places: http://doc.qt.io/qt-5/qtalgorithms-obsolete.html
They can and should be easily replaced with std counterparts.

**Comment by ilaripih** [comment]
Also, Qt now has a Q_UNREACHABLE macro which is a better way to flag unreachable branches than qFatal("Unreachable").

**Comment by artoj** [comment]
I think we should enable c++11 while we transition to those std counterparts and document c++11 as requirement.

**Comment by ilaripih** [comment]
Yes, I think C++11 is the way to go. Are there any mainstream Linux distributions that don't ship a C++11 enabled GCC compiler in their standard repositories? And Clang probably handles C++11 just fine?

**Comment by ilaripih** [comment]
I just added C++11 as a requirement, was easy enough.

**Comment by artoj** [comment]
GCC / LLVM seems pretty good. Debian stable has GCC 4.9 by default which has full support for C++11: [GCC C++11 support table](https://gcc.gnu.org/projects/cxx-status.html#cxx11)

For MS VC++ you need 2015 to use all the features of C++11: [MSVC C++11 support table](https://msdn.microsoft.com/en-us/library/hh567368.aspx)

We can make the jump now and start using C++11.

**Comment by ilaripih** [comment]
At least all Travis CI builds (both GCC and Clang) are fine, and my Windows/MinGW tests also worked fine. I'm interested in using at least the following C++11 features:

* New signals and slots syntax where it makes sense: http://doc.qt.io/qt-5/signalsandslots.html
* Lambda expressions for short slot functions, for cases where we would've previously created a private slot that is only used in a single connection.
* The "auto" type, which will save us a lot of typing

**Comment by ilaripih** [comment]
Obsolete <QtAlgorithms> functions are now gone.

**Comment by artoj** [comment]
Visual C++ 2013 seems to support auto and lambda expressions.

Given that we don't have so many unit tests I think C++11 should be primarily used in new code and older code updated for the parts where it makes sense such as one-liner slots and such.

**Comment by ilaripih** [comment]
I've been thinking of putting more effort into having decent unit test coverage at least in the library code. If I do non-trivial changes to old code, I'll make sure that change is covered by a unit test, or at least test it thoroughly manually.

**Comment by artoj** [comment]
OS X builds fine too. There seems to be regression in LLVM that results in warnings in our code. They are false positives. More info: https://llvm.org/bugs/show_bug.cgi?id=26396

**Comment by rwst** [comment]
> The "auto" type, which will save us a lot of typing

I also recommend range-based loops.

There is clang-modernize that can do this (and more) automagically. I transcribed the https://github.com/pynac/pynac repo to C++11 with this. I may have a look if you agree. Expect monster patches.

**Comment by ilaripih** [comment]
I actually used range-based loops in a couple of places, they're great. But we like small incremental changes, not monster patches. And I don't know how tools like clang-modernize cope with Qt's C++ extensions.
