### ISSUE TITLE
Provide qmake with static compiling capability

### ISSUE THREAD

**Issue by fsmosca** [cutechess/cutechess#302]
The readme told:

> $ qmake
> $ make

 I am successful with those commands, but the outputs i.e cutechess-cli and cutechess-gui is not usable by other user outside of my computer.

Perhaps that qmake will be equipped with static options, the goal is to share the cutechess-cli in one file and cutechess-gui in one file too.

**Comment by ppigazzini** [comment]
@fsmosca the [wiki](https://github.com/cutechess/cutechess/wiki/Making-a-release) has the instructions to build a static version for Windows and Linux. The static builds are used successfully in [Multi Variant Fishtest](http://35.161.250.236:6543/tests) with several CPU/OS

**Comment by fsmosca** [comment]
I knew the wiki, I just wonder if qmake can be revised, considering that I already have QT and mingw installed in my computer.

**Comment by ppigazzini** [comment]
The cutechess's codebase, without any change in cutechess's configuration/code, can be used to make either a dynamic build (e.g. with the [cutechess's windows_setup.iss](https://github.com/cutechess/cutechess/blob/master/dist/windows_setup.iss), where QT5 is configured to build dynamically) or a static build (e.g. following the wiki instruction).

To make a cutechess static build:
* on [Windows](https://github.com/cutechess/cutechess/wiki/Making-a-release#cutechess-64-bit), using MSYS2 MinGW-w64, is installed a static version of QT5 with the package *mingw-w64-x86_64-qt5-static*
* on [Linux](https://github.com/cutechess/cutechess/wiki/Making-a-release#gnulinux) is built a static version of QT5 from the source code (this step requires some time)

So, IMO, you need to change/update your QT5 framework to be able to make a static build.

Personally, when building a binary to be distributed, I prefer to start a brand new virtual machine, starting the bash script, checking the binary with VirusTotal.

**Comment by fsmosca** [comment]
So I need QT static, and this can be found in MYSYS2.
Thank you.
