### ISSUE TITLE
MSYS2 doesn't download latest master

### ISSUE THREAD

**Issue by Nordlandia** [cutechess/cutechess#306]
I update msys2.exe  and mingw64.exe with "pacman -Syuu" command. 

After updating packages i then execute make_cute.sh (text command) in MSYS2 64-bit console. 

C:\msys64\home\USERNAMEl\cutechess\projects\gui = old version.

**Comment by ppigazzini** [comment]
@Nordlandia Have you used the command `bash make_cute.sh` ?
I have just built successfully cutechess with a clean install of MSYS2 according the wiki instruction, here the zipfile [cutechess-win-64bit.zip](https://github.com/cutechess/cutechess/files/1485107/cutechess-win-64bit.zip) and the [Virustotal report](https://www.virustotal.com/#/file/98d1e0cfbc501e500cf6293cf10dd07b91a72e77771f1da4b7e81fea7a391448/detection)

**Comment by Nordlandia** [comment]
Thank. Worked on one of my machines now.
