### ISSUE TITLE
Copyright request

### ISSUE THREAD

**Issue by marcocalignano** [cutechess/cutechess#307]
Hi, 
I took your implementation of the Sequential Probability Ratio Testing for using in my project. 
Now I made some changes so it is Thread Safe for a QT application. I would like to change the Copyright header at the beginning and I wanted to ask if you can suggest the best way to say that comes from you and your Project

Thanks
Marco

**Comment by artoj** [comment]
Hi,

(I'm not a lawyer)

can you list the source files that you took?

Another question, is your project's license compatible with GPLv3 (specifically with that version) ?

I'll admit that our copyright headers are bit of a mess currently. I think this is something that we need to fix in the next hackathon.

Arto

**Comment by marcocalignano** [comment]
Hi, 

I took 

projects/lib/src/sprt.h 
projects/lib/src/sprt.cpp 

and I use them in the project leela.zero. I'd like to change the header to 

    This file is part of Leela Zero.
    Copyright (C) 2017 Marco Calignano
plus the copyright of you guys if you can give some names maybe looking at the git commits and also make a reference to your project like 

    This file is part of Leela Zero.
    Copyright (C) 2017 Marco Calignano
    originally take from cutechess (http://github.com/cutechess)
    Copyright (C) 2014 Arto Jonsson

If this is OK for you just let me know the names of the contributors per file 

Thank you

**Comment by artoj** [comment]
Hi,

those files were written by Ilari so substitute my name with his in the example and I think the format is fine.

@ilaripih ok with you?

Arto

**Comment by ilaripih** [comment]
Yes, that's okay with me.

**Comment by marcocalignano** [comment]
OK Done!
if you want to have a look go to 
https://github.com/marcocalignano/leela-zero

in the sprt branch 

Thanks
