### ISSUE TITLE
[macOS] 'mandoc: -T xhtml: Bad argument'

### ISSUE THREAD

**Issue by mibere** [cutechess/cutechess#309]
To create the HTML documentation an user has to execute the command 'make doc-html'.

As the tool 'mandoc' is not part of macOS it has to be installed, e.g. via Homebrew.
The current Homebrew version of mandoc is 1.14.3.

Issue: the command 'make doc-html' aborts with this message:

> mandoc: -T xhtml: Bad argument

This is because mandoc 1.14.3 (on macOS) supports just the following output formats:

>      The mandoc utility accepts the following -T arguments, which correspond to output modes:
> 
>      -T ascii     Produce 7-bit ASCII output.  See ASCII Output.
> 
>      -T html      Produce HTML5, CSS1, and MathML output.  See HTML Output.
> 
>      -T lint      Parse only: produce no output.  Implies -W all and redirects parser messages, which usually appear on stan-
>                   dard error output, to standard output.
> 
>      -T locale    Encode output using the current locale.  This is the default.  See Locale Output.
> 
>      -T man       Produce man(7) format output.  See Man Output.
> 
>      -T markdown  Produce output in markdown format.  See Markdown Output.
> 
>      -T pdf       Produce PDF output.  See PDF Output.
> 
>      -T ps        Produce PostScript output.  See PostScript Output.
> 
>      -T tree      Produce an indented parse tree.  See Syntax tree output.
> 
>      -T utf8      Encode output in the UTF-8 multi-byte format.  See UTF-8 Output.
> 
>      If multiple input files are specified, these will be processed by the corresponding filter in-order.
>

**Comment by artoj** [comment]
Thanks for very clear bug report. I'll take a look.

**Comment by mibere** [comment]
Until then I create the macOS development builds of cutechess-cli (see [https://stockfishchess.de](https://stockfishchess.de)) with the documentation in txt format.

Leave a comment if you need assistance or testing.

**Comment by artoj** [comment]
The '-Txhtml' seems to have been deprecated for some time now so I switched it to use the synonymous '-Thtml' instead.
