### ISSUE TITLE
Not fully PV in TCEC cutechess

### ISSUE THREAD

**Issue by sovaz1997** [cutechess/cutechess#310]
There is a problem in Cutechess: output of incomplete pv. This problem now exists in the TCEC, but it seems that this is exactly the problem of Cutechess. I would like to know if this problem is fixed now, because TCEC uses Cutechess version 2014.

**Comment by alwey** [comment]
You might try it out?

**Comment by ilaripih** [comment]
This was also discussed at TalkChess.com: http://talkchess.com/forum/viewtopic.php?t=65874
Looks like the current CuteChess master doesn't suffer from this bug so I'm closing the issue.
