### ISSUE TITLE
Missing letters in generated HTML documentation

### ISSUE THREAD

**Issue by mibere** [cutechess/cutechess#313]
After fixing #309 the generated HTML files (cutechess-cli.6.html, engines.json.5.html) look like this in the browser:

Example 1:
![1](https://user-images.githubusercontent.com/17352825/33086168-22c1cf66-cee7-11e7-97ff-0272a12287d3.png)

Example 2:
![2](https://user-images.githubusercontent.com/17352825/33086169-22de59e2-cee7-11e7-8651-bfdab6e109e9.png)

As you can see, there are missing letters on the left (see bold blue links). Tested in Chrome 62 and Safari 11, macOS.

**Comment by artoj** [comment]
I updated the CSS style to the new mandoc default.

**Comment by mibere** [comment]
Thanks. The [macOS development build](https://stockfishchess.de/) will contain the CSS and HTML files from now on.
