### ISSUE TITLE
Lock engine as white for tournament games

### ISSUE THREAD

**Issue by Nordlandia** [cutechess/cutechess#321]
I miss the option to select engine as white only in tournament tab. 

For example right click on engine in _Player_ tab then «Lock engine as white 🔒»

Another option or possibility is an checkbox named «Alternate colours» which can be enabled or deactivated if wanted.

**Comment by alwey** [comment]
what kind of tournaments would be relevant?

**Comment by Nordlandia** [comment]
Locking engine is particularly aimed for 1v1 matches, so for Round Robin.

**Comment by alwey** [comment]
We already had related enhancements for the CLI ( #95 and #188). What is missing now is a reasonable GUI implementation.

**Comment by alwey** [comment]
@Nordlandia : /wrt to the [question at talkchess](http://talkchess.com/forum/viewtopic.php?topic_view=threads&p=744498&t=66093): It has been in the **CLI** for a couple of months.

The relevant options are `-noswap` and `-repeat [n]`, see documentation.

Giovanni might want to give it a try.

**Comment by alwey** [comment]
I am not sure I would like to see support of these features (no side swap and  repeat n times) in the GUI. This is why I have not started working on this for the GUI just after the CLI. There is some  prospect of users mixing everything up and then complaining. In my opinion the user of the CLI is more conscious of the settings and his choices.

**Comment by Nordlandia** [comment]
Locking engine as white in matches can be good choise if that particular engine is weaker. 

For example lock _stockfish 8_ against latest _stockfish dev_ to see how it performs.
