### ISSUE TITLE
Length-based draw adjudication

### ISSUE THREAD

**Issue by tpoppins** [cutechess/cutechess#325]
Please consider adding a secondary, optional draw adjudication method that would limit the length of a game to x moves and could operate alongside the current eval-based method. Perhaps it could be enhanced by incorporating eval as well, e.g.

if MovesPlayed == x and Eval < y terminate game as draw

This would be extremely useful for rating lists' LTC tests, e.g. CCRL 40/40.

**Comment by Nordlandia** [comment]
Fritz gui support that.

**Comment by tpoppins** [comment]
Fritz GUIs don't adjudicate based on length, they just end the game without a result. They also run games in a tournament one by one rather than concurrently. No, for tournaments Fritz GUIs don't even come close to Cute Chess.

The only thing they got that CC doesn't is a tournament config file, but I understand the CC developers are considering adding it.

**Comment by Nordlandia** [comment]
I agree that Fritz GUIs can implement resign and draw adjudication that can be configurable. Current system: Never, Late, Early. 

![33](https://user-images.githubusercontent.com/26534454/34040891-0dfbea00-e196-11e7-9c2e-5f6e0b53624a.png)
![34](https://user-images.githubusercontent.com/26534454/34040894-102f34ee-e196-11e7-8ec5-5dada13d23b2.png)

**Comment by ilaripih** [comment]
Done by @alwey

**Comment by tpoppins** [comment]
Thank you!
