### ISSUE TITLE
cutechess.com

### ISSUE THREAD

**Issue by yellow-panther** [cutechess/cutechess#326]
Hello cutechess,

both websites cannot be found (connection failed), but with Wayback Archive these (former) links are:
https://web.archive.org/web/20170914102239/http://cutechess.com/
https://web.archive.org/web/20161026160717/http://www.twitchysynapse.com/software.php

Regards,

**Comment by artoj** [comment]
We'll take a look at this during the next hackathon.

**Comment by ilaripih** [comment]
twitchysynapse.com is no more and won't be back.

cutechess.com is being transferred to Godaddy

**Comment by artoj** [comment]
@ilaripih any update?

**Comment by ilaripih** [comment]
Thanks for the reminder. https://cutechess.com/ works now, and we even have HTTPS.
