### ISSUE TITLE
Engine output

### ISSUE THREAD

**Issue by jherrera80** [cutechess/cutechess#33]
First of all, congratulations on such a nice GUI, hope it keeps getting developed.

There's one thing that would be nice to have, if it's not too much work. The ability to show the engine output in an organized way, as it is done in arena, for example. To be able to switch between the current "Engine Debug", and the "pretty" and tabbed output, something like this:

depth|time|nodes|score|pv
-------|-----|--------|-------|-------
9/17|0:05|23494|1.57|Ke4 d5 Ke4 d5 Ke4 d5 Ke4 d5 Ke4
8/15|0:03|6457|1.23|Ke4 d5 Ke4 d5 Ke4 d5 Ke4 d5 

And show time, nps, tbhits, currmove, hash usage, etc in another row, maybe above the pvs.

**Comment by ilaripih** [comment]
Thanks for opening the issue. This feature is definitely on the agenda and will be implemented at some point.

**Comment by rwst** [comment]
I think the first step would be an intuitive way to filter debug output. Without looking at the code, I would like to have a way to see immediately the two engines' names, click on one, and get an (additional?) window showing only the output from one engine. Alternatively, have a button to split/unsplit the debug output into two engine-specific windows. Am I on the right track with the one or the other?

**Comment by ilaripih** [comment]
Filtering raw debug output is a separate issue. Even if debug output is disabled, the GUI should display the engines' thinking output as described by jherrea80.

When this issue is done, I think the debug output should be disabled by default, just like it is in cutechess-cli.

**Comment by ilaripih** [comment]
We should have a chart of both engine's evaluation scores (move number on X axis, score on Y). There are a few of options for drawing plots:

* DIY with QGraphicsView
* The recently GPL'd Qt Charts: http://blog.qt.io/blog/2016/01/18/qt-charts-2-1-0-release/ (requires Qt 5.4)
* http://qcustomplot.com/

**Comment by ilaripih** [comment]
I chose QCustomPlot for the EvalHistory widget, because it has a good API, is really easy to integrate to a project and doesn't bloat the build too much.

**Comment by ilaripih** [comment]
The initial version is now done. I also disabled the engine debug log by default, but it can be opened from the "View" menu. What's still missing:

- [ ] Use SAN format in UCI pvs. XBoard pvs can be whatever the engine likes to send, so they're tough to parse.
- [ ] Format time as "mm:ss" if it's less than an hour. Otherwise "hh:mm:ss".
- [ ] Divide score by 100 (use pawn units)

**Comment by jherrera80** [comment]
Nice!

**Comment by ilaripih** [comment]
As far as the gui 1.0 milestone is concerned I consider this done. But I'll open a new issue about improvements (showing nps, current move, hash usage, etc., as well as showing only one eval widget in non-pondering games).

**Comment by jherrera80** [comment]
I have noticed a couple of things:

- When the engine sends just "info depth x+1", the new row shows the new depth x+1 but the rest of the tokens are from depth x.

- When there are several pv updates during the same depth, because the best move changes, they are overwritten and only the last pv update remains.

I think both of these can be solved by just showing a new pv when the info string from the engine contains the "pv" token, irregardless of whether it is from a new depth.

**Comment by ilaripih** [comment]
That's a good suggestion. The first one is clearly a bug and the second one hiding the PV history. Issue reopened.

**Comment by ilaripih** [comment]
Now the evalwidgets don't show tokens from depth n-1 on depth n's row. @jherrera80 can you test if the current functionality is correct?

**Comment by jherrera80** [comment]
Sure, I'll test it when I get home.

**Comment by jherrera80** [comment]
It is working fine now. The first few plies are not printed, not sure if it has anything to do with time being 0 ms.

**Comment by ilaripih** [comment]
Many engines (eg. Crafty) don't send eval for the first few plies at all. But if you find in the engine debug widget ("View -> Engine Debug" menu item) that an engine sends eval for a ply that is not shown in the Eval widget, it's a bug that should be fixed.

**Comment by jherrera80** [comment]
With stockfish for example, if I use it from the console I get this:

Stockfish 190616 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
go infinite
info depth 1 seldepth 1 multipv 1 score cp 75 nodes 20 nps 3333 tbhits 0 time 6 pv e2e4
info depth 2 seldepth 2 multipv 1 score cp 80 nodes 55 nps 9166 tbhits 0 time 6 pv e2e4 b7b6
info depth 3 seldepth 3 multipv 1 score cp 97 nodes 141 nps 20142 tbhits 0 time 7 pv d2d4 d7d6 e2e4
info depth 4 seldepth 4 multipv 1 score cp 92 nodes 235 nps 33571 tbhits 0 time 7 pv d2d4 e7e6 e2e4 d7d6
info depth 5 seldepth 5 multipv 1 score cp 54 nodes 1664 nps 151272 tbhits 0 time 11 pv e2e4 d7d5 e4e5 e7e6 d2d4
info depth 6 seldepth 6 multipv 1 score cp -5 nodes 4124 nps 217052 tbhits 0 time 19 pv e2e4 d7d5 e4e5 d5d4 d2d3 b8c6
...

And if I start a new game with cutechess (setting time control to infinite, to emulate analysis mode), I get this in the debug window:

<stockfish(3): info depth 5 seldepth 5 multipv 1 score cp 54 nodes 1664 nps 332800 tbhits 0 time 5 pv e2e4 d7d5 e4e5 e7e6 d2d4
<stockfish(3): info depth 6 seldepth 6 multipv 1 score cp -5 nodes 4124 nps 412400 tbhits 0 time 10 pv e2e4 d7d5 e4e5 d5d4 d2d3 b8c6
...

As you can see, cutechess seems to be ignoring the first few plies.

**Comment by jherrera80** [comment]
BTW, it would also be nice to have all the fields aligned to the right (except the PV of course), and that scores always had two decimals (e.g. 0.00).

**Comment by ilaripih** [comment]
You're correct - the first move's evaluation will probably miss a ply or two because the game actually starts before its events are fully connected to the UI. But the rest of the moves should have the full evaluation.

**Comment by ilaripih** [comment]
I opened issue #74 about the statistics that are still missing. Closing this one.
