### ISSUE TITLE
timestamp

### ISSUE THREAD

**Issue by flok99** [cutechess/cutechess#332]
Hi,

Can you maybe add at full timestamp (e.g. including the hour/min/sec) in the pgn output or give an other means of mapping game results to logging of the engine?

Situation: a chess engine causes invalid moves. As 1000ths of games are played during the night, it is impractical to map game to a location in the logfile. As the engine logfile contains timestamps, then that could be a key.

**Comment by alwey** [comment]
+1 for optional comment in PGN at game end.

**Comment by ilaripih** [comment]
Maybe it would be easiest to parse if the timestamp was a new PGN tag. Is the "game started" timestamp enough or would you need a "game ended" timestamp as well?

**Comment by alwey** [comment]
I have got something like that. A problem may be to switch off the timestamp tags.

```
[Event "?"]
[Site "?"]
[Date "2018.01.13"]
[Round "?"]
[White "crafty"]
[Black "Dirty"]
[Result "0-1"]
[ECO "A00"]
[GameEndTime "2018-01-13T19:34:09.204 CET"]
[GameStartTime "2018-01-13T19:32:59.310 CET"]
[Opening "Dunst (Sleipner, Heinrichsen) Opening"]
[PlyCount "116"]
[TimeControl "30+0.3"]

1. Nc3 {+0.38/15 0.74s} c5 2. Nf3 {+0.72/14 0.73s} Nc6 3. e4 {+0.47/14 1.1s} d6 
...

```

**Comment by ilaripih** [comment]
Thanks for the good work @alwey
