### ISSUE TITLE
bug related to whitepov parameter

### ISSUE THREAD

**Issue by johnriksten** [cutechess/cutechess#335]
Hi,

First of all, I love your program!

I have found a bug concerning the whitepov paramter. It works fine in most situations, i.e. when the score is numerical. But in the final stages of a game, when mate scores are given, cutechess doesn't reverse the scores from the black player. So, for example, "M5" is not changed into "-M5". I suppsoe this is easy to miss because you almost never get to this stage of a game if you use adjudication.

I have attached a sample pgn (renamed to .log) plus a screenshot of the evaulation profile of the game in the Fritz GUI.

[whitepov.log](https://github.com/cutechess/cutechess/files/1608745/whitepov.log)
![whitepov](https://user-images.githubusercontent.com/35167367/34639573-644b87fa-f2e2-11e7-97eb-302e78933417.JPG)

**Comment by johnriksten** [comment]
For completeness, I use the cli, not the gui.

**Comment by ilaripih** [comment]
Thanks for the report. The bug affects both GUI and CLI. "whitepov" for UCI engines seems indeed to be broken for mate scores.

**Comment by ilaripih** [comment]
Unfortunately I don't have much time to test but the fix seemed to be so simple that I pushed it anyway. If you build CuteChess from source, could you test if the fix works?

**Comment by johnriksten** [comment]
That's fast! I didn't expect it would be a tough one.

Unfortunately I'm not in the habit of compiling code so I'd have to find out how that works and set it up from scratch...

**Comment by alwey** [comment]
@johnriksten :

Thank you for your quick response. I will try out the new patch.

However, I think there originally was a misunderstanding what the _whitepov_ parameter is and what it is supposed to do.

From the manpage of cutechess-cli:
```
whitepov
             Invert the engine's scores when it plays black.  This option
             should be used with engines that always report scores from
             white's perspective.
```

UCI engines always report from the side to move perspective. This is also the case for Gull and Fire. None is having a white perspective. The whitepov option is used when testing CECP (Xboard) engines like Crafty that report from a white perspective.

What you wanted to achieve has not really been implemented into cutechess yet. Ilari's patch is helping.

**Comment by ilaripih** [comment]
Thanks @alwey I was trying to remember what the `whiteEvalPov` check was doing in `uciengine.cpp` in the first place. Anyway, the patch makes things more consistent.

**Comment by alwey** [comment]
The patch works as promised, I think it does not break things that worked before.

The adjudicator of course uses the side-to-move perspective. So the score adjudication is mixed up when the whitepov parameter is abused.

**Comment by alwey** [comment]
Example: Stockfish is winning with black, adjudication
```
[Event "?"]
[Site "?"]
[Date "2018.01.06"]
[Round "1"]
[White "Gull 3 x64"]
[Black "Stockfish 8 64 BMI2"]
[Result "1-0"]
[FEN "rnbqk2r/4bppp/p3pn2/1p1p4/3P1B2/2N1PN1P/PP3PP1/R2QKB1R w KQkq - 0 1"]
[PlyCount "118"]
[SetUp "1"]
[Termination "adjudication"]
[TimeControl "20+0.2"]

1. Bd3 {+0.50/13 0.53s} Nc6 {+0.39/18 0.81s} 2. O-O {+0.58/13 0.36s}
O-O {+0.27/15 0.13s} 3. a4 {+0.39/14 1.9s} b4 {+0.45/19 1.1s}
4. Nb1 {+0.50/13 0s} Bd6 {+0.41/22 3.9s} 5. Nbd2 {+0.39/14 0.78s}
Bxf4 {+0.29/18 0.34s} 6. exf4 {+0.52/13 0.67s} a5 {+0.34/16 0.14s}
7. Rc1 {+0.69/14 0.42s} Ba6 {+0.25/18 0.43s} 8. Bxa6 {+0.66/15 1.5s}
Rxa6 {+0.25/19 0.41s} 9. Nb3 {+0.60/15 0.88s} Ne7 {+0.12/19 1.8s}
10. Qd3 {+0.60/15 1.3s} Ra7 {+0.14/17 0.12s} 11. Nc5 {+0.64/13 0.33s}
Qa8 {+0.12/19 0.43s} 12. Rfe1 {+0.44/12 1.2s} Rc8 {0.00/18 0.26s}
13. Kh2 {+0.35/11 0.62s} Rac7 {-0.10/16 0.28s} 14. Rc2 {+0.23/12 0.73s}
Nf5 {-0.11/17 0.44s} 15. Nd2 {+0.14/14 1.6s} Nd6 {-0.06/18 1.1s}
16. Ndb3 {+0.18/13 0.42s} Qa7 {0.00/18 0.82s} 17. Rec1 {+0.22/14 0.42s}
h5 {0.00/19 0.73s} 18. Qd1 {+0.24/12 0.37s} h4 {-0.20/15 0.30s}
19. Qe1 {+0.14/13 0.42s} Nh5 {-0.39/17 0.54s} 20. Qe3 {0.00/12 0.42s}
Nf5 {-0.27/20 0.95s} 21. Qf3 {0.00/15 0.46s} g6 {-0.21/18 0.48s}
22. Rd1 {0.00/14 0.36s} Rc6 {-0.45/19 0.38s} 23. Rcd2 {-0.08/13 1.2s}
Qb8 {-0.64/19 1.1s} 24. Kg1 {-0.24/13 0.73s} Qc7 {-0.65/19 0.87s}
25. Kh1 {-0.26/14 0.59s} Qxf4 {-0.54/20 0.58s} 26. Qxf4 {-0.31/14 0.56s}
Nxf4 {-0.54/18 0.11s} 27. Nxa5 {-0.23/14 0.22s} R6c7 {-0.56/21 0.49s}
28. Nab3 {-0.34/14 0.18s} e5 {-0.64/20 0.084s} 29. Nd3 {-0.34/14 0.062s}
Nxd3 {-0.50/22 0.80s} 30. Rxd3 {-0.34/14 0.13s} e4 {-0.45/21 0.14s}
31. R3d2 {-0.34/13 0s} Ra8 {-0.55/21 0.25s} 32. Nc5 {-0.43/14 0.66s}
f6 {-0.47/21 0.86s} 33. Ra1 {-0.37/14 0.81s} Kf7 {-0.47/22 1.6s}
34. Kg1 {-0.30/13 0.56s} Ke7 {-0.59/21 1.9s} 35. Rdd1 {-0.32/11 0.18s}
Kd6 {-0.53/18 0.35s} 36. a5 {-0.27/13 0.20s} Kc6 {-1.03/16 0.18s}
37. Ne6 {-0.63/12 0.33s} Re7 {-0.63/15 0.046s} 38. Nf4 {-0.77/13 0.23s}
g5 {-0.81/18 0.53s} 39. Rdc1+ {-0.78/14 2.0s} Kd6 {-1.21/18 0.27s}
40. Ne2 {-1.17/15 1.0s} Rea7 {-1.71/19 0.44s} 41. Ra4 {-1.17/14 0s}
Rxa5 {-1.52/16 0.079s} 42. Rxb4 {-1.17/14 0s} Ra1 {-2.05/17 0.23s}
43. Rb6+ {-1.21/14 0.31s} Ke7 {-1.97/16 0.077s} 44. Rc6 {-1.32/14 0.38s}
R8a2 {-2.02/18 0.21s} 45. Rxa1 {-1.34/13 0.21s} Rxa1+ {-2.29/17 0.29s}
46. Kh2 {-1.34/12 0s} Rd1 {-2.35/16 0.048s} 47. Rc5 {-1.48/14 0.75s}
e3 {-2.50/19 0.27s} 48. fxe3 {-1.61/14 0.38s} Nxe3 {-2.52/17 0.077s}
49. Rc3 {-1.61/14 0.087s} Nf1+ {-2.79/20 0.17s} 50. Kg1 {-1.61/13 0s}
Ng3+ {-3.28/17 0.067s} 51. Kf2 {-1.61/13 0s} Ne4+ {-3.39/19 0.34s}
52. Ke3 {-2.00/12 0.13s} Nxc3 {-3.53/18 0.060s} 53. Nxc3 {-2.08/12 0.14s}
Rc1 {-3.47/22 0.51s} 54. Nxd5+ {-2.56/13 0.41s} Ke6 {-4.01/21 0.78s}
55. Nb6 {-2.66/14 0.81s} Rc2 {-4.19/18 0.14s} 56. d5+ {-3.43/15 1.1s}
Kd6 {-4.39/19 0.22s} 57. Kd3 {-3.29/13 0.60s} Rxg2 {-5.51/15 0.15s}
58. Ke4 {-4.15/12 0.28s} g4 {-8.38/16 0.17s} 59. Kd4 {-7.32/11 0.37s}
gxh3 {-17.85/16 0.63s, White wins by adjudication} 1-0
```

**Comment by johnriksten** [comment]
It seems to me the issue is caused by the fact that the program doesn't keep track of the scores in a consistent way. Using the whitepov parameter forces a change to the black scores at the moment of input (when the information is received from the engine). In fact, it should not be changed until ther moment of output (for the cli, when the score is written to the pgn file). So, what you need is a function that looks like this (in pseudo-code):

function output_score (colour, score) {
	if (whitepov and colour = 'black') {
		return -score
	} else {
		return score
	}
}

Then, whenever you print the score to the pgn file, instead of "print score", you can use "print output_score(colour, score)". This will require you to know for each print if you're dealing with white or black, of course.

**Comment by alwey** [comment]
@johnriksten: There is no bug. Cutechess consistently has a side-to-move perspective. The option whitepov must only be applied to engines that

a) are CECP (Xboard protocol) engines, and
b) always report from the perspective of the white side.

There are relatively few engines that match these criteria, e.g. _Crafty_ and _Aice_.

**Comment by johnriksten** [comment]
@alwey: I understand what you're saying. However, contrary to what the help says about the whitepov parameter, I use it with engines that report from a side-to-move perspective because I like the scores to mean the same regardless of which engine (black or white) reports it, just like in the pgn you just shared. This basically means I always use whitepov. It's just easier to read, It's also the way it works in the Fritz GUI in which I open the pgn files.

My suggestion would make it possible to use adjudication together with the whitepov parameter, while at the same time providing the option to choose what you want the output to look like, Whether it would make everything work the way it should or not, is a matter of opinion.

**Comment by alwey** [comment]
@johnriksten : Now our opinions are converging. So, you are requesting a new capability, an enhancement. Not to break things for other users this is asking for a compatible solution. This may be achieved e.g. by using a new dedicated command line option like  `-whitescores` and a GUI check box to activate white POV scores on output. In the PGN output there should be a comment in the move text section documenting use of this option.

**Comment by ilaripih** [comment]
Okay, I found the issue that describes what @johnriksten is requesting: https://github.com/cutechess/cutechess/issues/162

I'm closing this one because the "whitepov" bug was fixed.
