### ISSUE TITLE
does not alternate white/black with every game

### ISSUE THREAD

**Issue by rwst** [cutechess/cutechess#34]
Example:
```
./cutechess-cli -rounds 4 -engine name=stockfish cmd=stockfish option.Hash=1024 option.OwnBook=false -engine name=komodo cmd=komodo-9.4-linux option.Hash=1024 option.OwnBook=false -each proto=uci option.Threads=4 tc=10+0.1 -repeat
stockfish doesn't have option OwnBook
Started game 1 of 4 (stockfish vs komodo)
Finished game 1 (stockfish vs komodo): 1/2-1/2 {Draw by 3-fold repetition}
Score of stockfish vs komodo: 0 - 0 - 1  [0.500] 1
Started game 2 of 4 (stockfish vs komodo)
Finished game 2 (stockfish vs komodo): 0-1 {Black mates}
Score of stockfish vs komodo: 0 - 1 - 1  [0.250] 2
Started game 3 of 4 (komodo vs stockfish)
Finished game 3 (komodo vs stockfish): 1/2-1/2 {Draw by 3-fold repetition}
Score of stockfish vs komodo: 0 - 1 - 2  [0.333] 3
Started game 4 of 4 (komodo vs stockfish)
Finished game 4 (komodo vs stockfish): 0-1 {Black mates}
Score of stockfish vs komodo: 1 - 1 - 2  [0.500] 4
ELO difference: 0.00 +/- 295.91
Finished match
```
You can see that two games are played s-k and two k-s. That would be okay in total but if I use a book and give the `-repeat` option the same opening is played twice but the colors are not alternated, i.e. game 1 opening 1 s-k, game 2 opening 1 s-k, game 3 opening 2 k-s, game 4 opening 2 k-s. So two identical games will be played.

**Comment by ilaripih** [comment]
Thanks for the report - I can confirm that the bug reproduces in current master but now in the last release versions. Unsurprisingly, one of my KnockoutTournament + refactoring commits broke something.

**Comment by ilaripih** [comment]
Fixed. Can you confirm that it works so I can close the issue?

**Comment by rwst** [comment]
I see no difference. However, I can work around it by giving `-games 2` and so I'm happy.

**Comment by ilaripih** [comment]
Assuming that you've pulled the latest code, can you try building the whole project again:
`make distclean && qmake && make` in the "cutechess" folder.

Changing color should work even with the `-rounds` parameter. At least it did in my tests.

**Comment by rwst** [comment]
No change, even with `make distclean`, it changes color but only every second game. I have given an example command above---why don't you give yours? Maybe there is a subtle difference.

**Comment by ilaripih** [comment]
I tried running the same exact command you gave, but replacing Komodo with another Stockfish:

```
./cutechess-cli -rounds 4 -engine name=sf1 cmd=stockfish option.Hash=1024 option.OwnBook=false -engine name=sf2 cmd=stockfish option.Hash=1024 option.OwnBook=false -each proto=uci option.Threads=4 tc=10+0.1 -repeat
sf1 doesn't have option OwnBook
sf2 doesn't have option OwnBook
Started game 1 of 4 (sf1 vs sf2)
Finished game 1 (sf1 vs sf2): 1/2-1/2 {Draw by 3-fold repetition}
Score of sf1 vs sf2: 0 - 0 - 1  [0.500] 1
Started game 2 of 4 (sf2 vs sf1)
Finished game 2 (sf2 vs sf1): 1/2-1/2 {Draw by 3-fold repetition}
Score of sf1 vs sf2: 0 - 0 - 2  [0.500] 2
Started game 3 of 4 (sf1 vs sf2)
Finished game 3 (sf1 vs sf2): 1/2-1/2 {Draw by 3-fold repetition}
Score of sf1 vs sf2: 0 - 0 - 3  [0.500] 3
Started game 4 of 4 (sf2 vs sf1)
Finished game 4 (sf2 vs sf1): 1/2-1/2 {Draw by 3-fold repetition}
Score of sf1 vs sf2: 0 - 0 - 4  [0.500] 4
ELO difference: 0.00 +/- 0.00
Finished match
```

**Comment by rwst** [comment]
Now it's getting interesting because exactly the same command as yours will result in a different outcome here:
```
ralf@ark:~/cutechess> ./cutechess-cli -rounds 4 -engine name=sf1 cmd=stockfish option.Hash=1024 option.OwnBook=false -engine name=sf2 cmd=stockfish option.Hash=1024 option.OwnBook=false -each proto=uci option.Threads=4 tc=10+0.1 -repeat
sf1 doesn't have option OwnBook
sf2 doesn't have option OwnBook
Started game 1 of 4 (sf1 vs sf2)
Finished game 1 (sf1 vs sf2): 1/2-1/2 {Draw by 3-fold repetition}
Score of sf1 vs sf2: 0 - 0 - 1  [0.500] 1
Started game 2 of 4 (sf1 vs sf2)
Finished game 2 (sf1 vs sf2): 1/2-1/2 {Draw by fifty moves rule}
Score of sf1 vs sf2: 0 - 0 - 2  [0.500] 2
Started game 3 of 4 (sf2 vs sf1)
Finished game 3 (sf2 vs sf1): 1/2-1/2 {Draw by insufficient mating material}
Score of sf1 vs sf2: 0 - 0 - 3  [0.500] 3
Started game 4 of 4 (sf2 vs sf1)
Finished game 4 (sf2 vs sf1): 1/2-1/2 {Draw by insufficient mating material}
Score of sf1 vs sf2: 0 - 0 - 4  [0.500] 4
ELO difference: 0.00 +/- 0.00
Finished match
```
What other factors are there? I'm using `gcc version 5.2.1 20150721 [gcc-5-branch revision 226027] (SUSE Linux) `. Replacing cmd=stockfish with komodo makes no difference so I guess it's not the protocol. I have no further idea.

**Comment by rwst** [comment]
No wait. I confirm what you say. I used the wrong binary (./cutechess instead of ./projects/cli/cutechess), so it's resolved. Maybe such things can be prevented by copying to the main directory after building in projects. Sorry for the fuss.

**Comment by artoj** [comment]
@ilaripih I think we need to include the git revision to the version information
