### ISSUE TITLE
tr() strings from cutechess-lib have to be moved into UI applications

### ISSUE THREAD

**Issue by Prcuvu** [cutechess/cutechess#345]
`tr()` strings from cutechess-lib are not recognized by gui.
I asked another Qt user, who replied that `tr()` strings should all be placed in UI applications by design, instead of libraries. Therefore those strings need to be relocated.
The translation's outcome depends on how this issue will be resolved.

**Comment by alwey** [comment]
Hi, the library is used by both GUI and CLI.

**Comment by Prcuvu** [comment]
This issue is invalid with new version of Qt.
