### ISSUE TITLE
polyglot limitation

### ISSUE THREAD

**Issue by 0zymandia2** [cutechess/cutechess#35]
If the bin books selected, exceed 500Mb combined, cutechess-cli will fail to start the match.

**Comment by ilaripih** [comment]
What error message do you get, if any? Is there a public link to some > 500MB book that I can try?

**Comment by 0zymandia2** [comment]
I posted all the information I have, here:
http://www.talkchess.com/forum/viewtopic.php?t=59884
In addition to that, I should say I tried with concurrency 1, and it made no difference. Cutechess will try to load into memory, almost 4 times the size of the book(s).
I don't recall a bin book that big, on the net. They're usually tiny, but when working with databases of gargantuan proportions, they don't stay tiny anymore. I could upload the ones I'm trying, for you.

**Comment by ilaripih** [comment]
Actually, I probably won't need the book file. The people at TalkChess are most likely correct: a 64-bit version of cutechess-cli is needed to get a 2GB chunk of memory. Alternatively, it could be possible to do book lookups on disk, but that of course needs some new code. I'll see how difficult that would be.

**Comment by 0zymandia2** [comment]
So, it's normal that it uses x4 the size of the book, in RAM?
Book lookups on disk, look like what everyone else is doing, GUI wise, but as you say, that would take some time. In the interim, maybe a 64bit compile would alleviate the matter. No one in the team, can manage a Windows binary?

**Comment by ilaripih** [comment]
The book is stored in RAM as a simple QMultiMap variable. I could try if QHash would be more memory-efficient.

The default MinGW compiler doesn't support 64-bit builds but I'll try the Visual Studio 2015 Community compiler which should be supported by Qt 5.6.

The best solution for such huge books would still be lookups on disk.

**Comment by 0zymandia2** [comment]
Let's hope QHash works better. A 64bit compile of the program, as it stands or modified, would be great.

I look forward to unloading the whole task from RAM, though.

**Comment by ilaripih** [comment]
Here's a quick and dirty 64-bit MSVC2015 build of cutechess-cli: http://ilaripih.mbnet.fi/bin/cutechess-cli-win64-test.zip

**Comment by 0zymandia2** [comment]
It succeeds in addressing more than 4Gb of memory. It's up to the user now, to decide where the limit is, by outfitting the PC with more RAM.
As for the version used, it says 0.7.2 but it seems to be more recent, than the 0.7.3 (from September 6) I was using. Closing the Window now, even with the mouse, won't leave engines open.

**Comment by ilaripih** [comment]
Yes, the 64-bit build above is based on current master, which still uses the 0.7.2 version number because that's the latest official release.

I'm still going to implement accessing Polyglot books directly from the disk. Otherwise the RAM usage is too big for large books.

**Comment by ilaripih** [comment]
It's now possible to pass cutechess-cli the "-bookmode disk" parameter to access book files directly from disk.

**Comment by 0zymandia2** [comment]
I'll try that as soon as a binary is available.

**Comment by ilaripih** [comment]
Unit tests written and new "-bookmode" option documented. A new 64-bit Windows build at http://ilaripih.mbnet.fi/bin/cutechess-cli-win64-test.zip

**Comment by ilaripih** [comment]
I'm closing this issue. Please reopen if I missed something.
