### ISSUE TITLE
Separate W/L/D totals for black and white

### ISSUE THREAD

**Issue by xoto10** [cutechess/cutechess#354]
For engine tournaments, it would be useful to get the results from cutechess-cli for black and white separately. This might highlight strengths or weaknesses in the engines. Is this something that could be done?

**Comment by alwey** [comment]
Indeed this is something I also had in mind. I am working on this. It has already been a topic for multi-variant Stockfish testing, the inventive people there are capable of testing black/white strength even now using a kludge.

**Comment by alwey** [comment]
Actually you can also use the `-noswap` option to enable side results. The test environment has to be prepared for this.

**Comment by Nordlandia** [comment]
Separate W/B wins in result tab for GUI is also something i hope can be considered.

**Comment by alwey** [comment]
> Separate W/B wins in GUI is also requested addition.
Yes, now by your request, not by xoto10.

**Comment by Ipmanchess** [comment]
Maybe a good idea to add also the Time Forfaits in real time during testing!

**Comment by alwey** [comment]
@Ipmanchess : I also had this in mind, but this is a different issue. In order to keep track of things we will have to have separate issues. I will open an issue about statistics of terminated games like time forfaits / illegal moves / false claims / connection stalls, and so on:  #355.

**Comment by Ipmanchess** [comment]
@alwey that's nice,thanks! When i open tournament results it would be great to see these Time forfaits..
When testing 1000&1000games we can stop test if too many TF happening..and adjust settings if needed!
For testers we would win a lot testing time..

**Comment by alwey** [comment]
I prepared an extension to the library and output of white and black scores in cutechess-cli:

```
Finished game 1004 (Stockfish 9 64 BMI2 vs Stockfish-test): * {No result}
Score of Stockfish-test vs Stockfish 9 64 BMI2: 229 - 218 - 557  [0.505] 1004
Elo difference: 3.81 +/- 14.33
When playing White: 129 - 98 - 276  [0.531] 503
When playing Black: 100 - 120 - 281  [0.480] 501
White vs Black    : 249 - 198 - 557  [0.525] 1004
Finished match
```

**Comment by xoto10** [comment]
Oh wow, great! I was intending to volunteer to help with this but I was
obviously too slow. I see engine testers often talking about pentanomial
instead of trinomial so this seems an obvious step forward.

:-)

>
>

**Comment by alwey** [comment]
@xoto: You are welcome. Please refer to https://github.com/ianfab/fishtest/issues/13, where @ianfab and @ddugovic analyse the use cases. I also think the `-noswap` option has an immediate advantage. The drawback of this is that one has to use pairs of tests when testing differing players.

**Comment by Nordlandia** [comment]
Layout concept:

Match results:  Stockfish vs Houdini 

Stockfish:
White wins, White draws, White losses | Black wins, Black draws, Black losses 

Houdini:
White wins, White draws, White losses | Black wins, Black draws, Black losses 

Stockfish performance white 65% | Stockfish performance black 35%

Houdini performance white 52% | Stockfish performance black 40%

**Comment by Nordlandia** [comment]
Achieving the result of draw as the black pieces is definitely a better result than playing draw as white pieces.  

Games : 136000 (finished)

White Wins : 50837 (37.4 %)
White Draws :
Black Wins : 40784 (30.0 %)
Black Draws : 
Draws : 44379 (32.6 %)

**Comment by alwey** [comment]
I'll try to provide a solution with various output formats from `concise` to 
`extra-wide` and possibly a freely configurable output option.

**Comment by Nordlandia** [comment]
@alwey are you going to hackathon?

@ilaripih mentioned it.

**Comment by alwey** [comment]
@Nordlandia The cutechess hackathon is a yearly phase of intensive development. During these phases I have been an observer. My contributions are mostly before and shotly after a hackathon.

**Comment by Nordlandia** [comment]
Layout inspiration:

![Statistics](https://user-images.githubusercontent.com/26534454/61305400-0ab07380-a7eb-11e9-9eac-a4d3c40f8e15.png)

**Comment by ilaripih** [comment]
Done by @alwey
