### ISSUE TITLE
No console output of cutechess-cli under Ubuntu 17.10 (because of *.debug=false)

### ISSUE THREAD

**Issue by beyondCritics** [cutechess/cutechess#366]
Under Ubuntu 17.10 cutechess-cli produces no console output whatsoever.
It turns out, that appending to the environment of cutechess-cli 
`QT_LOGGING_RULES="*.debug=true"`
or alternatively setting
`*.debug=true `
within the user local ~/.config/QtProject/qtlogging.ini fixes this. 
However i believe this is some kind of oversight, since debug output is generally thought of as only interesting for developer.
EDIT: describe workaround more clearly

**Comment by MortenLohne** [comment]
Same issue here after upgrading to Ubuntu 17.10. Thanks for providing a workaround.

**Comment by ilaripih** [comment]
We have an issue about using `QtInfoMsg` instead of `qDebug` but now this became a bit more urgent: https://github.com/cutechess/cutechess/issues/234

**Comment by ilaripih** [comment]
Should be fixed now. Please re-open issue if the problem persists.
