### ISSUE TITLE
repeat option does not (with chess960, no book)

### ISSUE THREAD

**Issue by rwst** [cutechess/cutechess#37]
It is a nice feature that a random 960 game gets a random start position. However the repeat option does not do the expected, which would be using the same position with w/b. I used
```
./projects/cli/cutechess-cli -rounds 4 -engine cmd=stockfish -engine cmd=stockfish -pgnout results.pgn -each proto=uci option.Threads=4 tc=1+0.01 timemargin=1000 whitepov -variant fischerandom -repeat
```
but the result pgn had a new position with every game. This does not change when I add the option `-games 2`.

I'm happy to say that I can work around this by using a book with the 960 positions. `repeat` does repeat then.

**Comment by ilaripih** [comment]
Sounds like a bug, thanks for the report.

**Comment by rwst** [comment]
Fix confirmed, thanks.
