### ISSUE TITLE
Total game duration

### ISSUE THREAD

**Issue by Nordlandia** [cutechess/cutechess#374]
I wish i can choose to use HH:MM:SS in "Tags" instead of current GameStartTime & GameEndTime.

Another possibility is to include this information inside move tab once game is finished. Also "Game duration" can be added inside "Tags" in HH:MM:SS format or equivalent.

Concept:

![concept](https://user-images.githubusercontent.com/26534454/38162234-f072e326-34dd-11e8-8813-3d614e13c2e3.png)

![c1](https://user-images.githubusercontent.com/26534454/38162341-9ab4b232-34df-11e8-8658-560b9b701443.png)

**Comment by alwey** [comment]
The [GameStartTime] and {GameEndTime] were introduced in response to user request #332. The aim was to provide help for the search for relevent information within common engine log files.

I understand that you are interested in seeing the total game length as [GameDuration] information, just as given in the TCEC PGN notation.  This should not be too difficult to include. Of course, already having the other tags this is redundant information.

```
[Event "TCEC Season 10 - Superfinal"]
[Site "http://tcec.chessdom.com"]
[Date "2017.11.20"]
[Round "1"]
[White "Komodo 1970.00"]
[Black "Houdini 6.03"]
[Result "1/2-1/2"]
[BlackElo "3185"]
[ECO "E11"]
[EventDate "2017.11.20"]
[GameDuration "04:31:46"]
[Opening "Bogo-Indian: 4.Bd2 Be7 5.g3 d5 6.Bg2 O-O 7.O-O c6 8.Qc2 b6"]
[PlyCount "156"]
[TerminationDetails "3-fold repetition"]
[TimeControl "7200+15"]
[WhiteElo "3232"]
```

**Comment by Nordlandia** [comment]
@alwey the reason for this request is that it's bothersome to subtract into exact time. First having to open website calculator and then copying back and forth. For statistical reasons "game length" is indeed useful in that regard. 

[GameEndTime "2018-03-25T11:24:38.689 W. Europe Daylight Time"]
[GameStartTime "2018-03-25T11:14:48.817 W. Europe Daylight Time"]

**Comment by alwey** [comment]
@Nordlandia: No problem, I already got it the first time ;-)

**Comment by alwey** [comment]
@Nordlandia: Done. I will prepare a pull request.

```
[Event "?"]
[Site "?"]
[Date "2018.03.31"]
[Round "?"]
[White "cheese-19-linux-64-pop"]
[Black "xiphos-sse"]
[Result "0-1"]
[ECO "C69"]
[GameDuration "00:01:45"]
[GameEndTime "2018-03-31T21:25:50.135 CEST"]
[GameStartTime "2018-03-31T21:24:04.629 CEST"]
[Opening "Ruy Lopez"]
[PlyCount "180"]
[TimeControl "30+0.3"]
[Variation "Exchange, Bronstein Variation"]
```

**Comment by Ipmanchess** [comment]
Nice ,that was fast! Thank you..

**Comment by ilaripih** [comment]
Thanks @alwey !
