### ISSUE TITLE
doesn't have option analysis_opt

### ISSUE THREAD

**Issue by hero2017** [cutechess/cutechess#377]
I'm trying to setup a tournament between raubfisch and stockfish on my 4 core system using cutechess-cli but I'm getting the error:

Raubfisch doesn't have option Analysis_Opt

Yet when I enter the uci command manually when running the engine exe I don't get an error with: setoption name analysis_opt value off

I've set the options in the engines.json file as:

"name" : "Analysis_Opt",
"value" : "Off"

if I run the uci command I see:

option name Analysis_Opt type combo default Both var Off var White var Black var Both

**Comment by alwey** [comment]
I would suggest using

```
"alias" : "",
"choices" : [
        "Off",
        "White",
        "Black",
        "Both"
],
"default" : "Both",
"name" : "Analysis_Opt",
"type" : "combo",
"value" : "Off"

```

**Comment by hero2017** [comment]
Thanks alwey. I don't really follow the reasons for it but if it works I'm ok with it..unfortunately it's not. I think it's an issue with formatting, either bracket or comma. This is what I have and I get unknown engines being listed:
```

      {
      "command" : "d:/Raubfisch.exe",
      "name" : "Raubfisch",
      "options" : [
	  {
		"alias" : "",
		"choices" : [
        "Off",
        "White",
        "Black",
        "Both"
],
"default" : "Both",
"name" : "Analysis_Opt",
"type" : "combo",
"value" : "Off"
      ],
      "protocol" : "uci",
      "workingDirectory" : "D:/cutechess/data",
      "rating" : 3400
   },
```

Also, how did you get that info? Where can I learn about such options and perhaps others?

**Comment by ilaripih** [comment]
I guess this issue can be closed. There's a separate issue about supporting position/move analysis.
