### ISSUE TITLE
GUI tournament options incomplete

### ISSUE THREAD

**Issue by rwst** [cutechess/cutechess#38]
At the moment there seems no way to specify arbitrary options for a new tournament. The dialog for example does not allow specification of a tournament book. This could be resolved by a field that enables textual input of any supported option. An alternative would be to have a text file with default UCI config options (for both gui/cli) or global GUI data field with such content.

**Comment by ilaripih** [comment]
This is a known issue - the whole GUI side is still very much incomplete.

**Comment by ilaripih** [comment]
Opening books can be used now and otherwise this is a duplicate of #83.
