### ISSUE TITLE
cutechess-cli resign

### ISSUE THREAD

**Issue by ghost** [cutechess/cutechess#385]
The game adjudication of the resign option is based on the score of only one engine. It could be useful to adjudicate the game if the losing engine is below a certain score and the winning engine is above that score.

**Comment by alwey** [comment]
This request is a logical conjunction (AND) of the present adjudication feature and the trust feature requested in issue #288, but also for non-mate scores.

**Comment by alwey** [comment]
I do not think that a combined adjudication has advantages /wrt to the standard adjudication based on the score of the losing player except for cases where the losing player is sandbagging.

**Comment by voyag** [comment]
The advantage is that is more accurate especially when one tests at short time control.

**Comment by alwey** [comment]
A disadvantage is that games will be longer and only be more exact in certain cases. Nevertheless  one precondition for this CR would be the functionality of #414.

**Comment by alwey** [comment]
I implemented a solution with two-sided game adjudication some time ago. I will do some tests and upload a PR soon.
