### ISSUE TITLE
copy/paste

### ISSUE THREAD

**Issue by lucasart** [cutechess/cutechess#4]
A feature that would be very useful is the ability to copy/paste a position (Ctrl+C/Ctrl+V).
Copy would write the FEN string into the clipboard, and paste would set the board (of the current tab) to that position.

**Comment by ilaripih** [comment]
There's now a "Copy FEN" menu item that copies the currently visible position's FEN string to the clipboard. It cannot be yet used with the CTRL+C sequence but we could attach that action to the gameviewer, meaning that if the input/mouse focus is on the gameviewer, CTRL+C executes the "Copy FEN" action. "Paste FEN" is more complicated and will be implemented later.

**Comment by ilaripih** [comment]
Now CTRL+C (or whatever the copy sequence is on the user's platform) triggers the "Copy FEN" action when the game viewer is focused.

**Comment by lucasart** [comment]
Thanks. I guess the "paste" part is a little trickier, because it is context dependent. If an engine is thinking or pondering on the current position, then either paste is disabled, or engines need to be stopped (and user prompted to abort the game or whatever).

**Comment by ilaripih** [comment]
Yes, I think pasting a new FEN means starting a new game, unless we're in analyze mode, which doesn't yet exist in cutechess-cli. But it wouldn't be that hard to open a new game with the current settings (time control, players, etc) in a new tab whenever the user executes the "Paste FEN" action.

**Comment by lucasart** [comment]
Better wait for analyse mode. Without it, paste is not very useful.

**Comment by ilaripih** [comment]
Probably for now I should just add a starting FEN input to the "New Game" dialog.

**Comment by lucasart** [comment]
Yes.

**Comment by ilaripih** [comment]
FEN input will be a part of `GameSettingsWidget`, issue #82. Progress can be followed there.
