### ISSUE TITLE
Invalid "illegal move" claim by GUI?

### ISSUE THREAD

**Issue by tpoppins** [cutechess/cutechess#403]
In the game below the latest dev build of Cute Chess GUI appears to have made this bizarre "illegal move" claim. 4...f7-f5 is a perfectly valid move, what's going on?

The game:

```
[Event "?"]
[Site "?"]
[Date "2018.07.14"]
[Round "?"]
[White "_Monochrome"]
[Black "Alibaba 1.40"]
[Result "1-0"]
[ECO "A20"]
[GameDuration "00:00:08"]
[GameEndTime "2018-07-14T03:09:13.571 Eastern Daylight Time"]
[GameStartTime "2018-07-14T03:09:05.222 Eastern Daylight Time"]
[Opening "English, Nimzovich Variation"]
[PlyCount "7"]
[Termination "illegal move"]
[TimeControl "40/120"]

1. c4 {book} e5 {book} 2. Nf3 {book} d6 {book} 3. d4 {book} e4 {book}
4. Ng5 {+0.76/6 3.3s, Black makes an illegal move: f7-f5} 1-0


```

The complete debug log:

```
<_Monochrome(0): info score cp 84 depth 3 nodes 3839 time 0 pv f3g5 g8f6 b1c3 
<Alibaba 1.40(1): alibaba.ini found. Loading values....   
<Alibaba 1.40(1): [alibaba] using hashsize 256mb selected
<Alibaba 1.40(1): [alibaba] pawn value   = 80
<Alibaba 1.40(1): [alibaba] knight value = 300
<Alibaba 1.40(1): [alibaba] bishop value = 305
<Alibaba 1.40(1): [alibaba] rook value   = 500
<Alibaba 1.40(1): [alibaba] queen value  = 900
<Alibaba 1.40(1): [alibaba] king value   = 3200
<Alibaba 1.40(1): [alibaba] end pawn val   = 110
<Alibaba 1.40(1): [alibaba] end knight val = 310
<Alibaba 1.40(1): [alibaba] end bishop val = 315
<Alibaba 1.40(1): [alibaba] end rook val   = 510
<Alibaba 1.40(1): [alibaba] end queen val  = 910
<Alibaba 1.40(1): [alibaba] end king val   = 3200
<Alibaba 1.40(1): done. 
<Alibaba 1.40(1): Choosing default transpo 1
<Alibaba 1.40(1): Choosing default ref 1
<Alibaba 1.40(1): Choosing default nrTtBits 22
<Alibaba 1.40(1): Choosing default twoLevelTable 1
<Alibaba 1.40(1): Choosing default ttValue 1
<Alibaba 1.40(1): Choosing default ttMove 1
<Alibaba 1.40(1): Choosing default timeStamp 1
<Alibaba 1.40(1): Choosing default useFlag 1
<Alibaba 1.40(1): Settings
<Alibaba 1.40(1): --------
<Alibaba 1.40(1): Refutation table   : true
<Alibaba 1.40(1): Transposition table: true
<Alibaba 1.40(1): Clearing entries with age 721 ply
<Alibaba 1.40(1): Keepmethod   : New
<Alibaba 1.40(1): TwoLevelTable: true
<Alibaba 1.40(1): UseTtValue   : true
<Alibaba 1.40(1): UseTtMove    : true
<Alibaba 1.40(1): useFlag      : true
<Alibaba 1.40(1): timeStamp    : true
<_Monochrome(0): info score cp 45 depth 4 nodes 35622 time 47 pv f3g5 g8f6 b1c3 c8f5 
<Alibaba 1.40(1): Initializing transposition table (4194304 entries * 40) --> 167772160 bytes
<Alibaba 1.40(1): Thinking output (pv lines) is on
<Alibaba 1.40(1): opponent's name is _Monochrome
<_Monochrome(0): info score cp 96 depth 5 nodes 231915 time 313 pv f3g5 g8f6 b1c3 c8f5 c1f4 
<_Monochrome(0): info score cp 76 depth 6 nodes 2210173 time 2918 pv f3g5 g8f6 b1c3 c8f5 g2g4 f5e6 
<_Monochrome(0): bestmove f3g5
>Alibaba 1.40(1): f3g5
>Alibaba 1.40(1): time 12000
otim 11674
>Alibaba 1.40(1): go
<Alibaba 1.40(1):  1 -651 0 3 Qd8xg5  .Bc1-g5                                 
<Alibaba 1.40(1):  3 -41 0 100 Bc8-f5   h2-h3                                  
<Alibaba 1.40(1):  5 -122 1 11711  e4-e3  Bc1-e3   c7-c6   h2-h3                  
<Alibaba 1.40(1):  7 -54 28 255324 Bc8-f5   g2-g4  Bf5-g6  Qd1-b3   e4-e3  Bc1-e3  
<Alibaba 1.40(1): 4615782 nodes (int:0, leaf:2332858, quies:0), 2282924 n/s
<Alibaba 1.40(1): 4784552 reads, 0 hits ( 0.00%) 3581259121 writes
<Alibaba 1.40(1): 12127762 moves in 0 times ( 0.00)
<Alibaba 1.40(1): move  f7-f5 
>_Monochrome(0): isready
>Alibaba 1.40(1): force
>Alibaba 1.40(1): result 1-0 {Black makes an illegal move: f7-f5}
>Alibaba 1.40(1): quit
<Alibaba 1.40(1): BTM	WS WL BS BL 6970
<Alibaba 1.40(1): +--------------------------+
<Alibaba 1.40(1): 8 |:r: n :b: q :k: b :n: r |
<Alibaba 1.40(1): 7 | p :p: p :::   :p: p :p:|
<_Monochrome(0): info debug isready command
<_Monochrome(0): readyok
<Alibaba 1.40(1): 6 |:::   ::: p :::   :::   |
<Alibaba 1.40(1): 5 |   :::   :::   ::: N :::|
<Alibaba 1.40(1): 4 |:::   :P: P :p:   :::   |
<Alibaba 1.40(1): 3 |   :::   :::   :::   :::|
<Alibaba 1.40(1): 2 |:P: P :::   :P: P :P: P |
<Alibaba 1.40(1): 1 | R :N: B :Q: K :B:   :R:|
<Alibaba 1.40(1): +--------------------------+
<Alibaba 1.40(1):     A  B  C  D  E  F  G  H
<Alibaba 1.40(1): best move score = +0.13
<Alibaba 1.40(1): alibaba terminating!
```

Cute Chess GUI latest dev 64-bit build (commit 4a9e31d)
Win 7 x64 Pro
Dual Xeon X5670 @2,93 GHz / HT off / 48 GB RAM

Monochrome: [link](https://drive.google.com/drive/folders/0B9voFYjJVtn_YTBqZHlLYzU4X3M) set up as a UCI engine, no config options
Alibaba: [link](http://kirr.homeunix.org/chess/engines/Jim%20Ablett/ALIBABA/) set up as an Xboard engine, Memory=512 (no other settings available)

**Comment by alwey** [comment]
Nothing to be seen here. As far as I can see, this is an engine problem.

The engine alibaba makes an illegal move: `e7-e5` instead of `e7e5`.
If SAN were activated, the correct notation would have been `e5`.

Please refer to
https://www.gnu.org/software/xboard/engine-intf.html

**Comment by tpoppins** [comment]
You mean "f7-f5 instead of f7f5", right? The move is not illegal but its format is. Thank you, alwey.

Would it be possible to implement a GUI-side workaround for this?

**Comment by alwey** [comment]
> You mean "f7-f5 instead of f7f5"

Yes, sorry, I mixed this up. The correct move formats would have been `f7f5` and `f5`.

> Would it be possible to implement a GUI-side workaround for this?

It would not be too difficult, but sorry I would not support it. And I am not sure @ilaripih or @artoj  would support this change.

I think it is good to give some help where human interaction is to be expected. But regarding interfaces between computer programs in most cases I prefer illegal formats to fail. This encourages programmers to implement interfaces correctly.

It is also possible to feed the engine input/ouput through an adapter program or filter.

**Comment by tpoppins** [comment]
I strongly agree. That's the only way to go forward. Here at CCRL, however, we often have to look backwards, having to deal with hundreds of legacy engines, some of which suffer from crippling bugs. Most of these have been out of development for years, so there's little chance of the authors fixing the bugs. In this particular case WB2UCI solves the problem; there are many others, though.

Making those old engine work could be viewed as a programming challenge, I suppose. I wonder if anyone would be interested in taking that up. I have accumulated a list of engines that have problems with Cute Chess; some (like Cinnamon 2.0 and OBender) won't even start, although they do work in other GUIs (Arena and ChessGUI, the main CCRL workhorses). Is it worth your time to submit new issues for these?

**Comment by alwey** [comment]
@tpoppins :+1: 

> Here at CCRL, however, we often have to look backwards, having to deal with hundreds of legacy engines, some of which suffer from crippling bugs. Most of these have been out of development for years, so there's little chance of the authors fixing the bugs. In this particular case WB2UCI solves the problem; there are many others, though.

Yes, I can imagine.

> Making those old engine work could be viewed as a programming challenge, I suppose. I wonder if anyone would be interested in taking that up. I have accumulated a list of engines that have problems with Cute Chess; some (like Cinnamon 2.0 and OBender) won't even start, although they do work in other GUIs (Arena and ChessGUI, the main CCRL workhorses). 

No, go ahead. I already noticed some issues with old engines. And then some issues have already been resolved. e.g. by extending the compatibilty a bit, e.g. for CECP V1 engines.

> Is it worth your time to submit new issues for these?

I would suggest using one collective issue for that at start. We can then sort out where cutechess does not support the standards, or otherwise point out the causes of the problems.

**Comment by alwey** [comment]
I opened a new issue #405 for this purpose. 

@tpoppins: Please consider closing this issue.

**Comment by tpoppins** [comment]
Thank you, alwey.
