### ISSUE TITLE
UCI option not exposed in engine properties

### ISSUE THREAD

**Issue by tpoppins** [cutechess/cutechess#406]
Engine Coiled 0.5 has a UCI option GaviotaTbPath

```
uci
id name Coiled 0.5 x64
id author Oscar Gavira, Spain.
option name Hash type spin default 128 min 1 max 2048
option name OwnBook type check default false
option name OwnBookLimit type spin default 8 min 2 max 10
option name ShowPv type combo default Middle var None var Middle var Full
option name GaviotaTbUse type check default false
option name GaviotaTbPath type string empty
option name GaviotaTbCache type spin default 32 min 8 max 1024
option name GaviotaTbCompression type spin default 4 min 0 max 9
uciok

```

which doesn't show up on the Advanced tab of the engine properties in Cute Chess 1.1.0:

[screentshot](https://s33.postimg.cc/owk424x7j/coiled05-config.png)

As a workaround I'm using "setoption name GaviotaTbPath value e:\gaviota" in the Init Strings field of the engine properties dialog box.

I have noted several other engines whose options Cute Chess doesn't parse properly, most notably options listed twice. Should I list them here or open a new issue?

**Comment by alwey** [comment]
> Should I list them here or open a new issue?

Please list them here, as you already have chosen a matching general topic.

/Wrt Coiled 0.5
`option name GaviotaTbPath type string empty`
is incorrect, so the option is ignored. Use
`option name GaviotaTbPath type string default empty`.

Example from the UCI specification
http://wbec-ridderkerk.nl/html/UCIProtocol.html

	Example:
    Here are 5 strings for each of the 5 possible types of options
	   "option name Nullmove type check default true\n"
      "option name Selectivity type spin default 2 min 0 max 4\n"
	   "option name Style type combo default Normal var Solid var Normal var Risky\n"
	   "option name NalimovPath type string default c:\\n"
	   "option name Clear Hash type button\n"

**Comment by alwey** [comment]
> As a workaround I'm using "setoption name GaviotaTbPath value e:\gaviota" in the Init Strings field of the engine properties dialog box.

Clever.

**Comment by tpoppins** [comment]
Ah yes; I should have seen that the "default" part was missing. Thank you, I'll notify the author.

**Comment by tpoppins** [comment]
For [Deepov 0.4.1](https://drive.google.com/drive/folders/0B9voFYjJVtn_YTBqZHlLYzU4X3M) Cute Chess displays Hash twice on the Advanced tab: [screenshot](https://s33.postimg.cc/mamz4ezlr/Deepov-0141-config.png)
The UCI output doesn't seem to call for it:
```
uci
id name Deepov 0.4.1
id author Romain Goussault - Navid Hedjazian
Current options
option name hash type spin default 256 min 1 max 2048
uciok

```
I was going to list BigLion 2.23x and BikJump 2.01 here as well, but they send Hash twice to the GUI themselves, so not Cute Chess' fault.

I'll post more examples as I remember them.

**Comment by tpoppins** [comment]
Arena 3.5.1 and Polyglot 3.8 cannot parse Deepov's output either, although it appears fairly standard. Bizarre!

Changed the issue title to a more generic one since the first problem brought up here turned out to be irrelevant.

**Comment by alwey** [comment]
I had another look at this:

a) Deepov issues an incorrect score format:

`
<Deepov(8): info depth 7 score 54 nodes 1107274 nps 1851628 time 598`

should rather be
`
<Deepov(8): info depth 7 score cp 54 nodes 1107274 nps 1851628 time 598`


b) Deepov sends `option name hash` twice - once when the program starts (should not do that) and once after the `uci` command. Because of the timing this leads to a double entry.

```
<Deepov(8): Current options
<Deepov(8): option name hash type spin default 256 min 1 max 2048
<Deepov(8): id name Deepov 0.4.1
<Deepov(8): id author Romain Goussault - Navid Hedjazian
<Deepov(8): Current options
<Deepov(8): option name hash type spin default 256 min 1 max 2048
<Deepov(8): uciok
>Deepov(8): setoption name hash value 256
>Deepov(8): isready
<Deepov(8): Option: hash updated to 256
<Deepov(8): readyok
```

From the UCI specs:
http://wbec-ridderkerk.nl/html/UCIProtocol.html
* option
	This command tells the GUI which parameters can be changed in the engine.
	This should be sent once at engine startup after the "uci" and the "id" commands
	if any parameter can be changed in the engine.
	The GUI should parse this and build a dialog for the user to change the settings.
	Note that not every option needs to appear in this dialog as some options like
	"Ponder", "UCI_AnalyseMode", etc. are better handled elsewhere or are set automatically.
