### ISSUE TITLE
Cutechess-cli does not list engine names in PGN tags

### ISSUE THREAD

**Issue by alwey** [cutechess/cutechess#408]
On my platform Linux, Ubuntu 14.04 I noticed a problem with cutechess-cli: Tags for White and Black do not reflect the engine names anymore. Does anybody have the same problem?

Before commit 22cccd8ae6cf1194a15fad3e78a0b25d02f26230

```
[Event "?"]
[Site "?"]
[Date "2018.07.25"]
[Round "1"]
[White "Stockfish 3 64bit SSE4.2"]
[Black "Stockfish 7 64 BMI2"]
[Result "*"]
[ECO "A06"]
[GameDuration "00:00:25"]
[GameEndTime "2018-07-25T00:55:14.860 CEST"]
[GameStartTime "2018-07-25T00:54:49.175 CEST"]
[Opening "Reti Opening"]
[PlyCount "82"]
[Termination "unterminated"]
[TimeControl "10+0.1"]
```

After commit 22cccd8ae6cf1194a15fad3e78a0b25d02f26230:

```
[Event "?"]
[Site "?"]
[Date "2018.07.25"]
[Round "1"]
[White "UciEngine"]
[Black "UciEngine"]
[Result "*"]
[ECO "A06"]
[GameDuration "00:00:27"]
[GameEndTime "2018-07-25T00:57:55.403 CEST"]
[GameStartTime "2018-07-25T00:57:27.740 CEST"]
[Opening "Reti Opening"]
[PlyCount "96"]
[Termination "unterminated"]
[TimeControl "10+0.1"]
```

**Comment by alwey** [comment]
I committed a small patch. White and Black PGN tags are set in the startGame() method.

**Comment by gcp** [comment]
Can you make a pull request? This bug is pretty annoying.

**Comment by gcp** [comment]
I saw you had a patch, but as already said, a pull request against this upstream would be good.

**Comment by alwey** [comment]
OK, no problem
