### ISSUE TITLE
Tags displayed for wrong games

### ISSUE THREAD

**Issue by tpoppins** [cutechess/cutechess#426]
Run several loose (i.e. started from the Game/New menu rather than Tournament one) games, cycle between the tabs of the completed games -- their tags don't change. The tags displayed for the first game you check are displayed for the rest.

**Comment by alwey** [comment]
I cannot confirm this observation for individual games. For me these games update their tags even after the game has finished. But for finished tournament games before a new one is started in the same tab there is no update for the tags when switching forth and back. So at the end of a tournament there are stale tags.

This is related to #233.

**Comment by ilaripih** [comment]
@tpoppins Are you using a released Cute Chess version or do you compile it from source code?

**Comment by tpoppins** [comment]
Own build from August 2 with 64-bit MSYS2.

**Comment by tpoppins** [comment]
Good to see this done.
