### ISSUE TITLE
cannot support large (> 3 billion) nodes as a parameter

### ISSUE THREAD

**Issue by horos22reg** [cutechess/cutechess#433]
all,

i'm trying to replicate deepmind's paper results for alphazero for lc0, by running the following cutechess-cli command to run a sf9/lc0 match:

cutechess-cli -tournament -gauntlet -rounds 1 -games 24 -concurrent 1 -pgnout tournament.pgn -recover -engine conf=stockfish tc=inf nodes=4200000000 -engine conf=lc0 tc=inf nodes=4800000

with the basic idea being to emulate the hardware that deepmind used via substituting speed for time and being replicable by using nodecounts instead of time controls. (from the paper, 70 million nodes/sec * 60 secs for stockfish == 4.2 billion nodes for stockfish, 80000 nodes/sec for lc0 * 60 secs == 4.8 million nodes for lc0)

however, cutechess-cli is complaining that 4.8 billion is an illegal parameter, which I assume is because it is too large to fit in a signed integer. 

This value is perfectly legal however with the uci client.

could cutechess-cli please support this value? Also is there a forum for discussing cutechess-cli usage?

if not, it would be great if people who use cutechess - or the authors - could go onto the lczero forum (https://groups.google.com/forum/#!forum/lczero) and answer questions on it, there are quite a few people using it there.

thanks much

**Comment by alwey** [comment]
I already read about this in the Lczero forum and I had a look into the code. I will try to create a pull request enhancing the nodes limits parameter.

**Comment by esp5** [comment]
alwey,

ok thanks.. i'll test it out as soon as a binary gets to github.

alternatively are there compile instructions for windows? I didn't see them in the repo.

**Comment by ilaripih** [comment]
Yes, `QString::toInt()` should be changed to `QString::toLongLong()` and `TimeControl::m_nodeLimit`'s type should be `qint64`.

**Comment by ilaripih** [comment]
I think the easiest way to compile on Windows is to download and install the Qt SDK (with MinGW compiler), open the cutechess project (`cutechess.pro`) in Qt Creator and hit the build button. If you have MSVC installed you can also set Qt Creator to use that instead of MinGW.

**Comment by tobchem** [comment]
Or you could follow these instructions: https://github.com/cutechess/cutechess/wiki/Making-a-release
