### ISSUE TITLE
Incomplete insufficient material detection

### ISSUE THREAD

**Issue by brtzsnr** [cutechess/cutechess#44]
The following positions are draws, but cutechess still tries to play them. See http://www.e4ec.org/immr.html for a  complete list.

3K4/1b6/8/kB5B/8/8/8/8 w - - 0 1
B7/8/8/3K3B/8/8/7k/5b2 w - - 1 2
8/4BK2/2k5/8/1B6/8/8/8 b - - 0 2

**Comment by ilaripih** [comment]
Thanks for the report. You're right that CuteChess could adjudicate the `K + n * B` case where `n > 1` and bishops stand on the same color as drawn. But these cases positions are quite rare and it shouldn't be a problem to the engines that CuteChess lets the game continue. Or do you know of an engine that refuses to keep playing in these positions?

I'd still like to implement this but it's not a high priority.

**Comment by brtzsnr** [comment]
My engine refuses to play this, but I worked around it. Winboard adjudicates correctly.

**Comment by ilaripih** [comment]
If Winboard does it, then I'll implement it at some point. BTW, you can also use the `trust` engine option to have cutechess-cli trust (ie. not validate) result claims made by the engine.
