### ISSUE TITLE
Sittuyin lone pawn promotion bug

### ISSUE THREAD

**Issue by gbtami** [cutechess/cutechess#448]
In position `8/8/R2P1k2/8/8/8/8/4K3 w - - 0 9` cutechess enables pawn moves:
d6d7 gives check, but not a promotion OK
d6d6f promotion but doesn't gives check OK
d6c7f  promotion but gives check NOT OK 
d6c5f  promotion but gives check NOT OK
![sittuyin](https://user-images.githubusercontent.com/479964/47992994-b0550400-e0ee-11e8-80cf-4128de69bf31.png)

**Comment by alwey** [comment]
Confirmed: This is a bug.

[Sittuyin Rules](https://vdocuments.site/how-to-play-myanmar-traditional-chess-eng-book-1.html)
Rule c5 is violated: Promotion moves are not tested for discovered checks.

> c.5	The promotion shall not be made in the check position to the opponent king by newly-promoted general or discovered check position by its rook.
