### ISSUE TITLE
Incorrect increment in Fischer clock

### ISSUE THREAD

**Issue by ghost** [cutechess/cutechess#451]
Fischer clock is adding time before move, not after it. I can see "0:00", but can’t call flag. After my move, it is "0:00" + increment.

**Comment by alwey** [comment]
"Your move" implicates a manual game. Per default the flag is not called against a human player, please refer to feature request #134. However you can configure this behaviour in the GUI per "Tools/Settings/General/"Human player can play  after timeout". 

In addition, you cannot call flag, the GUI does this for you.

I think the implementation of Fischer increment is basically correct. The increment is applied immediately before a side gets the move, but not before a side's first move. The application of increments to the first move and to book moves has been discussed in a talkchess.com forum. This would be closer to the over-the-board rules but disadvantageous (less stable time control for opening books of flexible depth particularly for odd plies) when testing improvements for chess engines.  It has been [suggested to make this configurable](http://talkchess.com/forum3/viewtopic.php?f=7&t=64027&p=730596#p730562).

[FIDE rules, Glossary, p. 31](http://rules.fide.com/images/stories/Laws_of_Chess_2018_-_EB_approved_-_clean_version.pdf)
> increment: 6.1. An amount of time (from 2 to 60 seconds) added from the start before each
move for the player. This can be in either delay or cumulative mode.

HTH
