### ISSUE TITLE
Explain different tournament types in the UI

### ISSUE THREAD

**Issue by Krzychumag** [cutechess/cutechess#452]
I have a question what the "Pyramid" in Tournament type. Is this option related to the Swiss system in chess,

**Comment by alwey** [comment]
It is a tournament type as requested in issue #401:
```
                  round-robin    Round-robin tournament (default)
                  gauntlet       First engine plays against the rest
                  knockout       Single-elimination tournament
                  pyramid        Every engine plays against all of its predecessors
```

If you do not need it, do not use it. 
We might want to add a tooltip description for the GUI selection as a hint.
