### ISSUE TITLE
winboard "feature done" bug

### ISSUE THREAD

**Issue by dshawul** [cutechess/cutechess#459]
It looks like cutechess-cli hangs with winboard engine's that take to too long to initialize -- which in my case is due to loading neural networks. The winboard protocol says this:

> done (integer, no default)
> If you set done=1 during the initial two-second timeout after xboard sends you the "xboard" command, the timeout will end and xboard will not look for any more feature commands before starting normal operation. If you set done=0, the initial timeout is increased to one hour; in this case, you must set done=1 before xboard will enter normal operation.

So I can do a "feature done 0" ... then time-taking operation ... "feature done 1".
This would allow for initialization times of upto 1 hour but cutechess-cli times out despite what its code suggests

`
	else if (name == "done")
	{
		write("accepted done", Unbuffered);
		m_initTimer->stop();
		
		if (val == "1")
			initialize();
		return;
	}
`

This has caused severe problems at TCEC.

More at http://talkchess.com/forum3/viewtopic.php?f=2&t=68956

Daniel

**Comment by dshawul** [comment]
Hi,

I don't think the timeout of 35 seconds applies  to winboard engines because of the following in the protocol specification

```
done (integer, no default)
If you set done=1 during the initial two-second timeout after xboard sends you the "xboard" command, the timeout will end and xboard will not look for any more feature commands before starting normal operation. If you set done=0, the initial timeout is increased to one hour; in this case, you must set done=1 before xboard will enter normal operation.
```

So if the engine sets done=0, cutechess-cli had to wait for upto an hour before declaring the engine is stuck.  That is how winboard engines that took a long time to initialize ( e.g. I had the same problem with 6-men egtbs loading, and now with loading neural networks). 


> This is an intentional limit. CuteChess should not give buggy or trolling participants occasion to delay a tournament. This establishes a "house rule" equivalent to chess rule 6.7.1:

But an engine that sets done=0 is not trying to troll but letting the gui know its initialization is going to take time and the GUI should wait. Maybe you can set the limit of 35 seconds after the engine sent a done=1. Infact most chess engines send done=1 immediately so a limit of 2 second should work too.

Daniel

**Comment by alwey** [comment]
The general protocol timeout is intended to keep some control of the timing of tournaments. It is  independent of the CECP or UCI timers. So the hammer will fall even if an engine has a correct timing within its protocol.

**Comment by alwey** [comment]
@dshawul : I will try to make a PR in order to make timing user configurable. So if a longer starting phase is needed this could be set via option in the CLI.
