### ISSUE TITLE
Being able to save & load engine settings

### ISSUE THREAD

**Issue by Nordlandia** [cutechess/cutechess#466]
Thus avoiding having to retype everything for each time. 

For example i usually switch between 4096 MB hash and 2048 MB hash allocation dependent on time control. Being able to quickly open saved engine settings is nice shortcut than manually adjust everything all over again. 

Save and load feature. 

Concept visualized: 
![settings](https://user-images.githubusercontent.com/26534454/50238216-122bad80-03bf-11e9-8317-f128d9c8e0b6.png)

**Comment by alwey** [comment]
I think cutechess can already help you as-is. You might want to use different permanent (named) configurations, e.g. "Komodo 9 10254 MB Hash" and "Komodo 9 2048 MB Hash".
