### ISSUE TITLE
Gustav III's Chess

### ISSUE THREAD

**Issue by Nordlandia** [cutechess/cutechess#467]
Variant proposal. 

Chess variant advocated by  King Gustav III of Sweden (1746-92).

>  Strategy: It seems like this game works very well, despite the fact that the combined piece power is enormous compared with regular chess. On this comparably small board, which was also an invention by Gustav III, the General-Adjutant cannot run amok. The positions are too cramped for that. This circumstance explains why the game retains much of the strategical and positional character of regular chess. The General-Adjutant is unique because it can, without any aid, give mate to the enemy king. The four extra squares are also important hiding nests for the King. If a Pawn is worth 1 point, a Queen is worth 9 points, then a General-Adjutant is worth about 12 points. 

![gustaviii](https://user-images.githubusercontent.com/26534454/50398678-b3c54d00-0779-11e9-90b5-37abff3f5cde.gif)

http://mlwi.magix.net/bg/gustaviii.htm

**Comment by alwey** [comment]
OK, this needs some preparation (display of wall pieces i.e. unreachable squares)

**Comment by alwey** [comment]
@Nordlandia: I implemented the rules for this variant (GustavBoard).  The graphics part is still missing.

**Comment by alwey** [comment]
Two components are necessary:

1. A new Amazon glyph (the one by U. M. Janos of Green Chess). This will be in a PR to update of the default.svg pieceset.
![amazonp](https://user-images.githubusercontent.com/6425738/50485722-bbddf080-09f6-11e9-9769-6c58b73c2ca8.png)

At the moment the "Q~"-glyphs of Promoted Queen (Crazyhouse) are used as a work-around.
![amazon2](https://user-images.githubusercontent.com/6425738/50485222-c4cdc280-09f4-11e9-8eb2-2d083114a376.png)

2. Currently CuteChess does not draw wall pieces. Although you cannot see them the walls actually limit the moves.

**Comment by ilaripih** [comment]
I merged the "Support Gustav III's Chess" pull request but will leave this issue open until the GUI improvements are there.

**Comment by Nordlandia** [comment]
Thanks for that. 

@ilaripih please check #461 when time allows it.
