### ISSUE TITLE
pv unreadable, when too long

### ISSUE THREAD

**Issue by erbsenzaehler** [cutechess/cutechess#469]
When the pv is too long it gets unreadable. This is current master on archlinux using qt 5.12.0
![2018-12-26-074039_1920x1080_scrot](https://user-images.githubusercontent.com/6897022/50435970-f014bc80-08e3-11e9-93aa-d9b5daa5ad62.png)

**Comment by alwey** [comment]
Thanks for reporting this problem.

I am using old Qt 5.2.1 and I do not observe such pv effects at all. When narrowing the evaluation dock the pv notation is abbreviated using three dots. 

   
![pv1](https://user-images.githubusercontent.com/6425738/50447453-7f899200-091b-11e9-8127-094047521f2b.png)

When the evaluation is more radically narrowed the pv simply gets out of view (to the right).

![pv2](https://user-images.githubusercontent.com/6425738/50448104-62ef5900-091f-11e9-9c7d-803552458dc9.png)

After narrowing further

![pv3](https://user-images.githubusercontent.com/6425738/50448149-b06bc600-091f-11e9-8ff3-52565f4da009.png)

So there might be a Qt configuration issue that is only triggered when using higher Qt versions.

**Comment by erbsenzaehler** [comment]
Might be an Qt issue. I tried with qt 5.9.5 on my laptop running Ubuntu 18.04 and everything works nice there. 

I am getting this message every time I start a new game:

qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 27675, resource id: 41943219, major code: 40 (TranslateCoords), minor code: 0

**Comment by erbsenzaehler** [comment]
I can confirm, that I no longer experience this issue with both my laptop(ubuntu) and my workstation(archlinux)
