### ISSUE TITLE
Compile of latest linux cutechess-cli?

### ISSUE THREAD

**Issue by noelben** [cutechess/cutechess#473]
Where to find compile of latest linux cutechess-cli?

**Comment by QueensGambit** [comment]
Hello noelben,
there a few ways how you can get the latest cutechess-cli excecutable:

1) You can download `cutechess_20170720.1.0.0.1.0.0-1_amd64.deb` at:
* https://github.com/cutechess/cutechess/releases
_This presumes that you have a Debian based OS like Ubuntu for example._
Then you can install full CuteChess with:
```
sudo apt-get install cutechess_20170720.1.0.0.1.0.0-1_amd64.deb
```
Afterwards the `cutechess-cli` should be added to your environment path executable, so you can run it from any system location.

2) If you're only interested in the `cutechess-cli` and not the gui,
download and extract `cutechess-cli-1.0.0-linux64.tar.gz` at:
* https://github.com/cutechess/cutechess/releases

3) If you're interested in the current development version of the `cutechess-cli`, clone the repo:
```
git clone https://github.com/cutechess/cutechess.git
```
and check out **Making a release -> GNU/Linux**
* https://github.com/cutechess/cutechess/wiki/Making-a-release

Greetings,
~QueensGambit

**Comment by noelben** [comment]
I need a new compile from current development version or even version 1.1.0, the supposedly last released official version. Only cutechess-cli.

I tried that Making a release -> GNU/Linux, but was not successful in compiling it under google cloud Ubuntu 16.04 LTS.

**Comment by alexforever86** [comment]
@QueensGambit Is there a plan for a release in the near future?

**Comment by QueensGambit** [comment]
Hello @alexforever86,
I'm not an official member of the [cutechess](
https://github.com/cutechess) development team, so I don't have push rights for this repository and can't create a release for v.1.1.0.
I also haven't all the libraries installed to create releases for all systems using cross-compiling.
You must either ask @artoj or @ilaripih.

If you're interested in the current executables v.1.1.0 (GUI and CLI) for Ubuntu 18.04.
You can visit the release page on my fork:
https://github.com/QueensGambit/cutechess/releases

This might be interesting for @noelben.

Greetings,
~QueensGambit

**Comment by noelben** [comment]
Thanks QueensGambit, 1.1.0 would be enough.

**Comment by maximmasiutin** [comment]
The page https://github.com/cutechess/cutechess/wiki/Making-a-release gives the information on how to build both cutechess (GUI) and the `cutechess-cli`. Is there any oportunity to build `cutechess-cli` only without making the GUI version, so I would not need to install libraries for the GUI version?

For instance, the https://github.com/cutechess/cutechess#building-from-source chapter gives the following sequence of commands:
```
$ mkdir build
$ cd build
$ cmake ..
$ make
```

However, how can i replace the line `cmake ..` to a line that only compiles the `cutechess-cli`?
