### ISSUE TITLE
Revert to full nodecount display at low values

### ISSUE THREAD

**Issue by matoototo** [cutechess/cutechess#481]
Low nodes are often seen with NN engines, and as they're becoming more and more popular this might be a nice QOL improvement.

Proposal:
Below 1000 nodes and/or nps, show the full value, above that move to K, M, etc. (maybe add a single decimal point, since consumer GPUs often range from 1k to 20k nps on Leela, and the added granularity would be nice)

**Comment by alwey** [comment]
The nodecount is displayed identically as "Nodes", e.g.  1, 198, 15687, 10801137, 12960775216.
I guess you are referring to search speed instead, given in nodes per second,  listed under "NPS".
I  will prepare a pull request to give NPS in kilos only if nps >= 10000, else in unity.
