### ISSUE TITLE
Feature: Provide path to engines.json

### ISSUE THREAD

**Issue by noelben** [cutechess/cutechess#489]
engines.json path could be in 
`C:\Users\name\AppData\Roaming\cutechess`

Cutechess-cli could be in 
`c:\chess\man`

batch file in c:\chess\man could have
`cutechess-cli -tournament gauntlet -enginejson C:\Users\name\AppData\Roaming\cutechess\engines.json -rounds 100 ...`

engines.json file is updated via cutechess gui.

If the batch file that is used to run the match using cutechess-cli is located in the location of the engines.json file then there is no need to specify the option name -enginejson

**Comment by alwey** [comment]
At first cutechess-cli searches for `engines.json` in the current working directory. If there is no `engine.json` file in this directory then cutechess-cli will read the `engines.json` from its default configuration directory.

**Comment by noelben** [comment]
Wow, it worked. Thanks. Closes #489
