### ISSUE TITLE
Colour of eval history

### ISSUE THREAD

**Issue by louism33** [cutechess/cutechess#500]
Hello! Thank you for an amazing piece of software!

One tiny issue: would it be possible to customize the colour of the evaluation history graph? Currently I cannot tell the difference between black eval and white eval, as they both seem pink. 
Thanks in advance,
Louis

**Comment by alwey** [comment]
Hello, there are quick (and-dirty) patches available on talkchess http://talkchess.com/forum3/viewtopic.php?f=2&t=66430&p=797169

However, a viable solution for configurable UI representations needs more resources. This is under way and will tackle more than just this issue. There are requests for configurable board square colours, border colours, square labels, piece sets and so on.

**Comment by louism33** [comment]
thanks! keep up the good work, your software makes testing a chess engine painless!
