### ISSUE TITLE
cutechess does not send "debug on"

### ISSUE THREAD

**Issue by louism33** [cutechess/cutechess#505]
when running cutechess with -debug , at no point does it send "debug on" to the engine. Is this intentional? 

Thanks

**Comment by alwey** [comment]
Well spotted. Support of UCI command "debug" is currently missing in cutechess.

There are two different matters:

The `-debug` option of cutechess-cli tells _cutechess-cli_ to turn on its own debug mode and show all of its communications. 

From the manual page (cutechess-cli.6) or help file (help.txt):
 `-debug  Display all engine input and output.` 

In contrast, "debug on" refers to a UCI command which turns on an engine's debug mode (if supported).
Fom the UCI specifiction:
```
* debug [ on | off ]
	switch the debug mode of the engine on and off.
	In debug mode the engine should sent additional infos to the GUI, 
        e.g. with the "info string" command,
	to help debugging, e.g. the commands that the engine has received etc.
	This mode should be switched off by default and this command can be sent
	any time, also when the engine is thinking.
```
Support for this UCI command is currently missing in cutechess. Cutechess currently does not support the CECP (Xboard) feature debug either. Here an engine signalises "feature debug=1" and cutechess rejects this.

So it would be an enhancement of cutechess to support more UCI and CECP functionality.
Engine debug would then be individually controllable in the -engine sections, e.g. `-engine some_engine proto=uci debug=on ...`. 

Using `debug=on` in the `-each `section of the command line would then turn on debugging for all engines at once.

**Comment by ilaripih** [comment]
I guess it would make sense to put the engines in debug as well when the `-debug` option is used.
