### ISSUE TITLE
tournament results console does not show correct results

### ISSUE THREAD

**Issue by hros** [cutechess/cutechess#507]
I created a tournament between two variants of the same engine (lczero) which I called "LeelaChess-1" and "LeelaChess-2".
The results window showed a draw result for all games:
_Score of LeelaChess-1 vs LeelaChess-2: 0 - 20 - 0 [0.000]_
Looking at the saved pgn showed a completely different picture (no draws. one engine wins almost all the time).
I guess it has to do with the similar names of the engines

**Comment by alwey** [comment]
Hi, there is nothing wrong. The results window showed (W-L-D)  0 wins, 20 losses, and 0 draws from LeelaChess-1's perspective.

There is no problem with the names. Cutechess can even discern the scores of _identical_ players based on their tournament schedule.

Please close this issue. Thank you.
