### ISSUE TITLE
Cannot initialize player

### ISSUE THREAD

**Issue by rchastain** [cutechess/cutechess#510]
Hello!

I have a [UCI engine](https://github.com/rchastain/smirf-uci) which works well with Winboard, but with Cute Chess sometimes the tournament aborts with the message "Cannot initialize player...".

The engine uses a DLL and sometimes it takes one second to start (to load the DLL I imagine). I suspect this is why Cute Chess fails to start the engine.

Does someone would have a solution for that?

Or is it another explanation to that issue?

Regards.

Roland

**Comment by alwey** [comment]
I tested smirf-uci under Linux with the "Wine under Linux"-environment at . About one hundred games were played against various opponents at tc=10+0.1. I did not notice any initialisation problems.

However, now and then smirf played illegal moves. The opponents played no illegal moves during the tests.

**Comment by rchastain** [comment]
Thank you for your answer, and for your test of Smirf. So I suspect Windows Defender to be the origin of my problem.
About the illegal moves, thank you for your information. The interface translates Shredder-FEN to X-FEN, and X-FEN to Shredder FEN. The illegal moves are probably the result of a translation error. I will make some other tests.
