### ISSUE TITLE
cutechess-cli tournament from position

### ISSUE THREAD

**Issue by croc54** [cutechess/cutechess#514]
Is there any option to start a tournament between two engines from a given position?

**Comment by alwey** [comment]
You can use the `-openings` option to achieve this. E.g. you might use an openings file with only one starting position.

`cutechess-cli -engine cmd=engine1 proto=uci -engine cmd=engine2 proto=uci -each tc=30+.3 -openings file=onep1.epd format=epd -games 2 -rounds 10  -pgnout test1.pgn`

**Comment by ilaripih** [comment]
@croc54 Did @alwey 's comment answer your question and can we close this issue?

**Comment by croc54** [comment]
yes, the solution suggested by alwey works. thanks.
