### ISSUE TITLE
Result table column with acchieved points missing

### ISSUE THREAD

**Issue by rwbc** [cutechess/cutechess#516]
I noticed that the simplest of all columns, the plain acchieved points, is missing.
I think it should be there, either left or right from the 'Score' column. (=> Points)

`Rank Name                          Elo     +/-   Games   Score   Draws`

**Comment by ilaripih** [comment]
What do you mean by achieved points, how is if different from "Score"?

**Comment by rwbc** [comment]
Well, the plain score (points) is simply not there, but the already calculated score percentage.
Normally result tables include the plain score = acchieved points too.

**Comment by rwbc** [comment]
Here an example output from Ordo.
The 'POINTS' column does not exist in CuteChess and the '%' column in Ordo corresponds to the SCORE column in CuteChess.

The percentage is ofc nice, especially if all players have not (or not yet) the same number of games,
but we still want to know the current points w/o doing some own maths, while looking at the table.

```
   # PLAYER               :   RATING  ERROR  POINTS  PLAYED    (%)
   1 Goedel_600-64        :  3021.40  37.30   122.5     196  62.50
   2 Pirarucu_307         :  3019.69  37.38   122.0     196  62.24
   3 Marvin_340-64        :  2996.10  36.58   115.0     196  58.67
   4 RodentIII_0287-64    :  2982.83  38.46   111.0     196  56.63
   5 Winter_06-64         :  2910.80  35.75    89.0     196  45.41
   6 Topple_072-64        :  2894.31  37.05    84.0     196  42.86
   7 Counter_33-64        :  2870.90  35.27    77.0     196  39.29
   8 Asymptote_062-64     :  2823.97  38.62    63.5     196  32.40

White advantage = 19.97 +/- 10.61
Draw rate (equal opponents) = 32.01 % +/- 1.79
```

**Comment by rwbc** [comment]
I see now that this issue should be fixed with the above pull request.
Shall I close the issue now as it seems auto-close for the given date did not work?
