### ISSUE TITLE
Scheveningen Type of Tournament (Special Case of Gauntlet)

### ISSUE THREAD

**Issue by Oragonon** [cutechess/cutechess#521]
Please add the Scheveningen type of tournament.  It is actually a special case of Gauntlet with several strong engines in a 1st team running the gauntlet made up of a 2nd team of engines. The no. of engines in the 1st team may not be equal to the members of the 2nd team. 1st team has the option to play White or Black only or alternating.

**Comment by alwey** [comment]
This is a generalisation of feature request #488.

As a work-around for now you might start a sequence of gauntlet tournaments.

**Comment by Oragonon** [comment]
Thanks for adding -seeds option. However, there is still no option for the seeds to play Black only. Sometimes I want to study the black side of an opening variation. So I set up a Scheveningen tournament with strong engines playing the Black side vs a team of weak engines. I don't want my seeds to play White in this tournament.

**Comment by alwey** [comment]
It  is possible to play Black only with the seeds in the CLI using the `-reverse` option:
```
-reverse    Use schedule with reverse sides.
```

Using this option the schedule A vs B, C vs D, ... becomes B vs A, D vs C, ...
For the **GUI** I submitted PR #594 in order to provide the same functionality.
It is also included in my [EXPER1](https://github.com/alwey/cutechess/tree/EXPER1) branch of patches.

However, a dedicated tournament mode is necessary for an an easy-to use Scheveningen scheme.

**Comment by alwey** [comment]
@Oragonon : While  the `reverse` feature is not in the GUI you may use a trick: The original seeds should be non-seeds and vice versa.

When having a gauntlet with 3 strong engines seeded and 7 weak engines to play against the strong engines would start playing White. However, seeding the 7 weak engines against the 3 strong engines (non-seeded) would have the strong engines play Black as intended.

**Comment by Oragonon** [comment]
Thanks a lot alwey! I am using the cutechess gui now to play Scheveningen
tournaments.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
