### ISSUE TITLE
Enter setup by hand still possible?

### ISSUE THREAD

**Issue by rain0r** [cutechess/cutechess#540]
In some old versions of cutechess it was possible to edit the setup / formation by hand. You could then place the figures of each side by drag and drop on the table and resume the game from that position.

Is this still possible with the current version? I'm missing this feature.

Or, which was the last version that supported this feature?

**Comment by alwey** [comment]
I am not aware of a version that supported this feature.

**Comment by alwey** [comment]
@rain0r: Or do you refer to `placement` chess variant?

**Comment by rain0r** [comment]
No, I mixed two programms up - sorry.

**Comment by alwey** [comment]
@rain0r : Thank you, please close this issue.
