### ISSUE TITLE
Swiss tournament

### ISSUE THREAD

**Issue by Krzychumag** [cutechess/cutechess#542]
Can you once again ask for making the program the opportunity to play Swiss tournaments.
I have asked once, now please again. Please take care of this first and don't write to wait a few more years.

**Comment by alwey** [comment]
This is a duplicate of #267.

Please refrain from opening new issues for a request already made.
If everybody did this, the project would not move forward but it would be much more difficult to track the issues.

**Comment by Krzychumag** [comment]
Thank you alwey.

**Comment by alwey** [comment]
Please close this issue.

**Comment by artoj** [comment]
Closed as duplicate.
