### ISSUE TITLE
Wrong LLR calculation in SPRT matches

### ISSUE THREAD

**Issue by zz4032** [cutechess/cutechess#543]
The calculated LLR in Cutechess at the time of stoppage (or generally) seems to be incorrect.
Excerpt from Cutechess with stopping condition:
`-sprt elo0=0.0 elo1=5.0 alpha=0.05 beta=0.05`
```
880 - 759 - 1863  [0.517] 3502
Elo difference: 12.0 +/- 7.9, LOS: 99.9 %, DrawRatio: 53.2 %
SPRT: llr 2.95 (100.2%), lbound -2.94, ubound 2.94 - H1 was accepted
```
SPRT script for checking:
http://hardy.uhasselt.be/Toga/sprt_elo.py
`python sprt_elo.py --elo0 0.00 --elo1 5.00 -W 880 -L 759 -D 1863`
Script output:
`LLR [u,l]                   :  2.27  [-2.94,2.94]`
Standings of finished SPRT matches in "Fishtest" can be confirmed by the script.

**Comment by alwey** [comment]
Cutechess is ok. It uses logistic elo input parameters, not Bayes elo.

`python sprt_elo.py --elo0 0.00 --elo1 5.00 -W 880 -L 759 -D 1863 --logistic`

output:
`LLR [u,l]                   :  2.95  [-2.94,2.94]`

Please close this issue.

**Comment by zz4032** [comment]
Ok, thanks. Unfortunately this means that the drawratio affects the results.
