### ISSUE TITLE
font size problem on Ubuntu 18.04

### ISSUE THREAD

**Issue by warpian** [cutechess/cutechess#547]
building a release of 1.0 (master latest) on Ubuntu 18.04
following instructions exactly as stated on the main page (installing custom version of Qt5 etc)
build completes succesfully with no errors
when starting the gui by executing /projects/gui/cutechess
the gui comes up with no readible texts anywhere and in the console I get multiple messages:

"QFont::setPointSizeF: Point size <= 0 (-0.600000), must be greater than 0"

Been diving into the code to see where the font size is set, but I haven't been able to figure out how this is configured (if not hard coded, in a property file of some kind maybe?).

**Comment by alwey** [comment]
I am developing under Ubuntu 18.04 and I have not encountered this problem yet.

>  following instructions exactly as stated on the main page (installing custom version of Qt5 etc)

I tried to follow but I did not find the referenced section  "installing custom version of Qt5".

**Comment by MichaelB7** [comment]
New install of Ubuntu 18.04 yesterday, followed the instructions exactly as stated on the main page and have no issues here whatsoever.  My guess is unistall qt5 and reinstall the standard version of qt5.

**Comment by artoj** [comment]
I cannot reproduce the issue. Please re-open if you can reproduce it. Thanks!
