### ISSUE TITLE
Rejected legal engine moves in kinglet

### ISSUE THREAD

**Issue by ianfab** [cutechess/cutechess#563]
In kinglet, some engine moves get rejected in both CLI and GUI although they are allowed as user input moves in the GUI. Examples:

* Pawn promotion to king/commoner
8/2p5/4p3/5p2/3P1P2/1rP2R2/p7/8 b - - 1 40
move: a2a1k

* Castling
r3k2r/5ppp/1p2b3/pBn5/3qP3/2Np1P2/PP2K1PP/1Q1R3R b kq - 1 17
move: a8c8

(Both observed in engine vs. engine games using Fairy-Stockfish)

**Comment by alwey** [comment]
@ianfab . Thank you for reporting this. i will look into it.

**Comment by alwey** [comment]
Indeed, while my first promotion test showed no problem, in my second test promotion went wrong.


```
<stockfish-fairy-10.2(3): bestmove a2a1k ponder d4d5
>stockfish-large-10.4 (xboard)(2): result 1-0 {Black makes an illegal move: a2a1k} 
```

**Comment by ianfab** [comment]
If you run a match for kinglet with Fairy-SF these illegal move issues occur quite frequently, so if you have problems reproducing it with the above FENs or if you want more positions for testing, you can also just run some short TC matches, and latest after a few dozen games you should get some.

**Comment by alwey** [comment]
This is a problem with sanPV in connection with UCI. The xboard protocol seems to work.
As a work-around, please add "kinglet" to the list of variants avoiding SAN PV:
```

diff --git a/projects/lib/src/uciengine.cpp b/projects/lib/src/uciengine.cpp
index 58128708..b0d577cf 100644
--- a/projects/lib/src/uciengine.cpp
+++ b/projects/lib/src/uciengine.cpp
@@ -126,7 +126,7 @@ void UciEngine::sendPosition()
 void UciEngine::startGame()
 {
        Q_ASSERT(supportsVariant(board()->variant()));
-       const QList<QString> directPvList = {"giveaway", "suicide", "antichess"};
+       const QList<QString> directPvList = {"giveaway", "suicide", "antichess", "kinglet"};
 
```

**Comment by ianfab** [comment]
In case this applies to variants with non-royal kings, could this also affect extinction and codrus?

**Comment by alwey** [comment]
Yes, indeed.

**Comment by alwey** [comment]
I uploaded the work-around. I am trying to isolate the root cause. I think this problem is related or identical to issue #201.
