### ISSUE TITLE
No castling in Cutechess

### ISSUE THREAD

**Issue by se7enty6** [cutechess/cutechess#568]
I have downloaded and installed Cutechess 1.0.0. I played a game against LC0 where it didn't allow me to castle whereas it was possible. Castling was not one of the legal moves as per the GUI.

**Comment by sprinter89** [comment]
You can drag your king to rook so you can castling.

**Comment by se7enty6** [comment]
Yes, that worked. Normally, the king moves only two squares to the side. Thanks.
