### ISSUE TITLE
Differentiate promoted pieces in crazyhouse

### ISSUE THREAD

**Issue by Nordlandia** [cutechess/cutechess#582]
In Crazyhouse i suppose it make sense to differentiate an genuine queen and a promoted one.

"For example, if my opponent has 2 queens on the board and I end up in a position where I can capture either one it would be nice to know at first glance which one will give me a queen in hand and which one will give me a pawn in hand and capture the correct one. "

Reference: https://github.com/ornicar/lila/issues/6165

**Comment by alwey** [comment]
They are shown as different glyphs., e.g. `Q` (White Queen) and `Q~` (Promoted White Queen with a ^ above their crown), so no issue.

**Comment by Nordlandia** [comment]
Thanks, i didn't know it was implemented. Looks good. 🤩✅
