### ISSUE TITLE
New builds

### ISSUE THREAD

**Issue by RafaelDominiquini** [cutechess/cutechess#584]
Hi,

Why are there no new builds available here? The last one was in 2017. There are more than 250 commits since that build!

Thank you.

**Comment by artoj** [comment]
Agreed. We're planning to release new builds.

**Comment by Krzychumag** [comment]
Please write when a new version will be released builds.

**Comment by ilaripih** [comment]
Okay, new release with Mac and Windows builds here: https://github.com/cutechess/cutechess/releases/tag/1.2.0
