### ISSUE TITLE
Global Settings dialog

### ISSUE THREAD

**Issue by ilaripih** [cutechess/cutechess#59]
GUI needs a Settings dialog where the user can set the following options:

- [x] Concurrency for tournament games. It should always be possible to manually start a new game.
- [x] Default folder for chess engines
- [x] Enable/disable the black&white dots showing legal moves

Progress of default game and tournament settings can be followed in separate issues #82 and #83.

**Comment by artoj** [comment]
The engine management window should also be part of the settings windows.

**Comment by ilaripih** [comment]
It could be a separate tab in the Settings dialog. The dialog for configuring a single engine is fine as it is.

Adjudication options could be a separate dialog as well - it's also needed in NewGameDialog and NewTournamentDialog.

**Comment by ilaripih** [comment]
All action points of this issue are done.
