### ISSUE TITLE
Adding support for Terachess 1 and 2.

### ISSUE THREAD

**Issue by gekkehenker** [cutechess/cutechess#590]
http://history.chess.free.fr/terachess.htm

It is huge.
It's confusing.
It's mostly ridiculous, but it's also fun.

And despite the amount of pieces, its rules luckily aren't very complicated.

Could support for Terachess be added?
Sometimes the novelty of a huge 16x16 variant is worth it.

**Comment by alwey** [comment]
Hello, it is possible to support it but this variant is costly.
There are 23 kinds of pieces in this variant. The movements of some pieces are tricky. You need graphic symbols for all of them. I would not touch this variant now.

I can offer a CuteChess implementation of the game of _Grant Acedrex_ which was described by King Alphonso X de Castilla, in 1283 (https://en.wikipedia.org/wiki/Grant_Acedrex). This game is supported by at least one chess engine.

**Comment by gekkehenker** [comment]
I guess it's the Rhinoceros, Eagle and Nightrider that are really tricky then?


Grand Acedrex would be cool too, tahnks.

**Comment by alwey** [comment]
_Rhinoceros_ and _Eagle_ have already been implemented in Grant Acedrex. The names are _Rhinoceros_ and _Aanca_ - the latter is described as a giant bird of prey. It is the sheer number of pieces, promotion rules, and artwork that makes this variant costly.
