### ISSUE TITLE
which files the king and rook ocuppy after the castling in shako

### ISSUE THREAD

**Issue by gaintpd** [cutechess/cutechess#604]
Dear European friends. What's the files the King and Rook ocuppy after castling in shako variant.
 
I have implementated the **shako** variant. And it is near the end, this is the problem left. Please give me an confirmation.
Thank you very much.

**Comment by ianfab** [comment]
One of the design principle of shako is that if you remove the additional ranks and files (i.e., the outermost on each side) it behaves like standard chess (with the exception of promotion). Therefore, the king target files are D and H, also see https://github.com/ianfab/Fairy-Stockfish/blob/7a40cd420707ec05afea47b630267ab0baf95daf/src/variant.cpp#L826-L827. The rooks then occupy the E and G files, respectively.

**Comment by gaintpd** [comment]
@ianfab Thank you very much for your prompt reply. Now this problem get settled.
I test the castling problem with this fenstring:
`c3n4c/er3k2re/pp2pppb1p/1bqp4n1/2p4pp1/3P3PP1/1PPNP3N1/P4PPB1P/ER1BQK2RE/C8C w KQkq - 3 10`
And get the result that in consistent with your explanation.
![Screenshot from 2020-08-13 22-11-32](https://user-images.githubusercontent.com/17960782/90145282-5ba9e700-ddb2-11ea-9d7b-6d83ae6edc00.png)

Thank you again for your kindly help.
