### ISSUE TITLE
Pirarucu 3.3.5

### ISSUE THREAD

**Issue by Krzychumag** [cutechess/cutechess#608]
How to install this engine Pirarucu 3.3.5 in the program Cutechess 1.2.0.

**Comment by alwey** [comment]
Exemplary installation of UCI engine Pirarucu, version 3.3.5:

1. Unzip the engine package into an appropriate directory and move the `pirarucu--3.3.5` directory to the desired path.

2. In CuteChess,  select Tools->Settings->Engines->"+"-Button. The engine configuration dialog appears. The Protocol selector should show "UCI".
3. Press button "Working Directory" and browse to the installed directory e.g. 
`some-path/pirarucu-3.3.5`. Press "Open".
4. Press button "Command" and browse to bin/, select command `pirarucu`. Press "Open".
5. If  necessary, select the "Advanced" tab, select "Detect" and/or modify the settings.
6. The configuration name can be edited  in "Basic"/ "Name".
7. Select "Ok". Now the engine has been installed under the selected name.

![pira1](https://user-images.githubusercontent.com/6425738/90240009-030d3500-de18-11ea-91b0-e9bda9b6cab2.png)

This is an example how to install a chess engine in CuteChess GUI. We should set up or link to a page showing the process.
As there are 3000 engines and even more versions we cannot answer these kind of questions every time. We appreciate your understanding.

**Comment by Krzychumag** [comment]
Warmly he is thanking for help. Now everything is acting. I asked for help because the chess engine is written in Jave.

**Comment by artoj** [comment]
Seems to be solved. Closing
