### ISSUE TITLE
Add Concurrency  Box to Tournament Settings

### ISSUE THREAD

**Issue by MichaelB7** [cutechess/cutechess#614]
Probably the most often reason why one has to leave Tournament Settings is when they realized the concurrency setting is not set correctly.

**Comment by alwey** [comment]
In the CuteChess GUI the `GameManager` limits the number of concurrent games. It will start new games from the game queue only if the number of current games is less than the concurrency.

The setting
Tools->Settings->Tournaments -> Concurrent Games
is dynamic: you can change it while a tournament is going on. The change is immediately transmitted to the GameManager but only after a game has finished the change comes into action.

**Comment by MichaelB7** [comment]
That is good to know!
