### ISSUE TITLE
many engines have "connection stalls"

### ISSUE THREAD

**Issue by tissatussa** [cutechess/cutechess#633]
## Output of `cutechess-cli --version` / `cutechess --version`
i'm only using the GUI version :
Cute Chess 1.2.0
Using Qt version 5.12.8
Running on Ubuntu 20.04.1 LTS/x86_64

## How did you run Cute Chess exactly?
just ./projects/gui/cutechess without any parameters

## Expected behavior
engines should not time out, eg. "White's connection stalls"

##Actual behavior
many UCI engines stop / crash with resulting message eg. "White's connection stalls"

NOTE: Andy Grant, creator of the Ethereal chess engine, thinks it's due to CuteChess, not the engines : At https://github.com/AndyGrant/Ethereal/issues/158 he states : "Ethereal does behave correctly under cutechess. 143,511,079 games played on my testing framework across many machines under many cutechess versions. The fact that you said the issue occurs for Lc0 as well, indicates that the issue is not with the engines." -- i have the same opinion, when i use these 'malfunctioning' engines (in CuteChess) as stand alone, they seem to function properly.

**Comment by alwey** [comment]
Thank you for reporting. We need more information.

Which engines stall under which conditions (e.g. concurrency, number of threads, time control, engine configuration parameters, table bases, opening books)?

Andy Grant seems to have no such no problems with cutecgess.

**Comment by alwey** [comment]
Thank you for reporting. We need more information.

Which engines stall under which conditions (e.g. concurrency, number of threads, time control, engine configuration parameters, table bases, opening books)?

Andy Grant seems to have no such problems with cutechess.

**Comment by tissatussa** [comment]
As i stated : i just use the GUI .. how can i run a test for you ? Can i generate a log file which shows all these conditions ?  In general : "concurrency" is a term which i do not recognise, is it in the settings ?  i use 2 threads.  Time Control 15 min + 10 sec / 40 moves and CuteChess lets me set a "Margin" (this might be the cause??) : "the time limit can be exceeded by this many milliseconds" -- i always did 200 ms .. no special engine parameters .. no table bases .. no opening books .. my settings are rather basic.  I put Hash 512 Mb.

**Comment by tissatussa** [comment]
And many engines have this problem, now and then .. especially LC0 and Ethereal .. it's not often, say 1 in 7 games this happens.

**Comment by alwey** [comment]
All of those engines have NN components in them, have they not?

**Comment by tissatussa** [comment]
It could be all those misbehaving engines have NN .. i did not notice .. does it matter?  And please tell me how to get a list of the Conditions, when i run another test for you ..

**Comment by alwey** [comment]
> It could be all those misbehaving engines have NN .. i did not notice .. does it matter? And please tell me how to get a list of the Conditions, when i run another test for you ..

NN engines might be slow to respond.


>  just use the GUI .. how can i run a test for you ? Can i generate a log file which shows all these conditions ?

By right.clicking into the "Engine Debug" Dock and selecting "Save Log to File ..." you can save its content.

>  In general : "concurrency" is a term which i do not recognise, is it in the settings ? i

GUI: Tools->Settings->Tournaments->Concurrent Games Spinbox. Its value dynamically controls the number of concurrent games of a tournament after the next tournament game has finished.

The CLI has an option
```
-concurrency n
             Set the maximum number of concurrent games to n.
```

**Comment by alwey** [comment]
> And please tell me how to get a list of the Conditions, when i run another test for you ..

This is a bit more difficult. 
There is the engine's section in the _engines.json_ file.
It looks like
```
       {
                "command" : "./Barbarossa-0.3.0-linux64-sse42",
                "name" : "Barbarossa-0.3",
                "options" : [
                        {
                                "alias" : "",
                                "default" : 16,
                                "max" : 1024,
                                "min" : 16,
                                "name" : "Hash",
                                "type" : "spin",
                                "value" : 16
                        }
                ],
                "protocol" : "uci",
                "stderrFile" : "",
                "workingDirectory" : "/usr/local/bin"
        },

This is the general configuration of the engine. The active configuration for a game or tournament can be different if you modified the actual settings via the "Engine Settings" dialog.
```

You might either add a screenshot of  the "Engine Configuration" dialog and mark the settings you changed (General: Tools->Settings ->Engines->(engine xyz)->double click: "Engine Configuration", Better: From the list of players of a tournament or engine configuration button of a single game, select the "Engine Configuration" dialog of the engine under investigation).

**Comment by tissatussa** [comment]
yesterday i setup another game : Arasan v22.1 vs. Vajolet v2.8.0 .. both not NN engines .. i do not run tournaments yet, just single games between 2 engines, and it happened again : "White loses on time" !?

[engine_debug2.log](https://github.com/cutechess/cutechess/files/5509207/engine_debug2.log)
![Arasan_no_time](https://user-images.githubusercontent.com/1109281/98520120-ec894500-2271-11eb-9280-bab783b5157e.png)
![Arasan_v22 1_engine_config_basic](https://user-images.githubusercontent.com/1109281/98520123-ed21db80-2271-11eb-845b-741a26372176.png)
![Arasan_v22 1_engine_config_advanced](https://user-images.githubusercontent.com/1109281/98520125-ed21db80-2271-11eb-8003-b550447c4b30.png)
![Vajolet_v2 8 0_engine_config_basic](https://user-images.githubusercontent.com/1109281/98520127-edba7200-2271-11eb-9573-fcde84c32a8b.png)
![Vajolet_v2 8 0_engine_config_advanced](https://user-images.githubusercontent.com/1109281/98520133-ee530880-2271-11eb-9cfd-232a0e8cfd3b.png)
![setting_games](https://user-images.githubusercontent.com/1109281/98520136-ee530880-2271-11eb-8dde-0a388946309c.png)

i only found a file "engines.json.5" in ./docs  (which i renamed here by adding ".txt" because it could not be attached otherwise).
[engines.json.5.txt](https://github.com/cutechess/cutechess/files/5509152/engines.json.5.txt)
as you see it's not a real json file .. it seems an info text with some markup !?

as my (stripped) engine debug log file shows : at the end Arasan had a "best move" Kb6 but the display shows "White loses on time" ..

**Comment by rwbc** [comment]
> 
> 
> yesterday i setup another game : Arasan v22.1 vs. Vajolet v2.8.0 .. both not NN engines .. i do not run tournaments yet, just single games between 2 engines, and it happened again : "White loses on time" !?
> 
> [engine_debug2.log](https://github.com/cutechess/cutechess/files/5509207/engine_debug2.log)
...
> as my (stripped) engine debug log file shows : at the end Arasan had a "best move" Kb6 but the display shows "White loses on time" ..

So far you never mentioned your hardware/system and AFAIK you also did not mention you are playing with ponder on.
I can say from my professional software tester experience and from computerchess testing for 20 years
that most problems come from the users themselves (their environment/setup etc.).

Your screenshots show you use ponder=on with 2 threads per program.
This means you have already 4 cores under full load always.
This will only work reliably, if you have more than 4 real cores.
If you have more than 4 cores available we can dig deeper, can you confirm this?

What exactly is your environment? Hardware/OS etc. ?
BTW you are also doing weird things by playing with MPV=5 in game play. Is that intentional?

**Comment by tissatussa** [comment]
Thank you for helping solving my problem. Your last entry holds good info !  I answer your questions here.

As i stated in the very first paragraph of my issue, i run Ubuntu 20.04.1 LTS/x86_64 .. it's a laptop .. to get all hardware info i did the command 'sudo lshw' and made the output into a ZIP :

[lshw.zip](https://github.com/cutechess/cutechess/files/5511108/lshw.zip)

Some main info is:

description: Notebook
product: SATELLITE C855-226 (PSCBWE)
vendor: TOSHIBA
version: PSCBWE-07L00VDU
width: 64 bits
capabilities: smbios-2.7 dmi-2.7 smp vsyscall32
configuration: boot=normal chassis=notebook family=Type1Family sku=PSCBWE uuid=507E0448-5A6F-E281-2350-7054D2C66678

description: CPU
product: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
vendor: Intel Corp.
version: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
size: 1419MHz
capacity: 4GHz
width: 64 bits
clock: 100MHz
configuration: cores=2 enabledcores=2 threads=4

Indeed i did not mention i use "ponder on" .. is it relevant ?  I guess this is the checkbox "Thinking on opponent's time" ?

I seem to have 2 cores and 4 threads, but i'm not into hardware .. you say "This will only work reliably, if you have more than 4 real cores", well, then this might be the cause !  I will set threads 1 and test again.

About MPV : thank you for stating "I know virtually no person who uses MPV in game play" .. i did not know any disadvantage of MPV .. i once read MPV 1 should be best, but not why .. my experience during analysis of a position by 1 engine using MPV (eg. 5 or even 9) is that some move can have a low evaluation upto some depth, but then will ONLY gain significant value when some high MPV is set, otherwise the engine will never encounter its strength at higher depth .. OK, i will set MPV 1 in game play !

**Comment by rwbc** [comment]
...

> Question: why does CuteChess offer an MPV setting anyhow when a user should never use MPV > 1 in game play or tournament ? CuteChess is for engine vs engine only, is it not ? Or can CuteChess also be used to analyse a game position by 1 engine, and then use eg. MPV 5 ?

Well, if you look again at your own screenshot, you will realize that you showed 'advanced' options of the engine itself,
those are not CuteChess GUI settings.
To make it short, engines (especially UCI ones) expose their changeable options to GUIs.
Only most common options will be generalized by a GUI setting, other GUIs do this for hash, threads and/or tablebases.
IIRC CuteChess does none of this currently. (Even the tablebase adjudication is independent from engine tablebase settings)

You'll notice that MPV by default is always set to 1 by any author and you must have changed it actively to 5.
You might also notice that only a part of engines support MPV at all.

**Comment by tissatussa** [comment]
Thanks.  I'm fully satisfied.  It's clear now.  You might close this issue now .. it might be a great help for people with same problems !  I'm glad CuteChess does not appear to be buggy, as i thought .. I like CuteChess !

**Comment by alwey** [comment]
> Thanks. I'm fully satisfied. It's clear now. You might close this issue now

@tissatussa : Please close this issue by yourself. Besides the author of an issue only both members of the Cute Chess group can close issues.



> i only found a file "engines.json.5" in ./docs (which i renamed here by adding ".txt" because it could not be attached otherwise).
> engines.json.5.txt
> as you see it's not a real json file .. it seems an info text with some markup !?

Ah, this is the UNIX-style manual page for engines.json. It describes the format of the engines.json file.

You can create an engines.json file by adding an engine configuration to the permanent list of known engine configurations. Tools->Settings->Engines->+ (button). An engine configuration can be named like the engine or have a different name. You can have multiple configurations of the same engine.
If everything is ok, an engines.json file should be created after adding the new engine (configuration) _and_ closing the Tools->Settings dialog.

**Comment by tissatussa** [comment]
Thanks for all the quick and valuable support. I'm closing this issue now. However, i want to add a few words.

These days i did some more testing .. i use MPV=1 and 1 thread with all engines now .. and a small Hash -this also seems crucial for performance, but it's another subject-  .. now, only a very times some engine stalls, it just flags .. but one of them is Ethereal .. on Ubuntu 20.04.1 i even installed an older version (11.25, non NNUE) from the standard repository and it has the same problem now and then .. this happens especially when Ethereal (NNUE or not) is almost lost, but not always .. then it feels like the engine is considering forever ..
