### ISSUE TITLE
Sprt doesn't work 

### ISSUE THREAD

**Issue by respel** [cutechess/cutechess#636]
## Output of `cutechess-cli --version` / `cutechess --version`
cutechess-cli 1.2.0
Using Qt version 5.15.1
Running on macOS 10.15/x86_64

## How did you run Cute Chess exactly?

./cutechess-cli -engine cmd=stockfish -engine cmd=stockfish -each proto=uci tc=40/5 -ratinginterval 1 -sprt elo0=-0.25 elo1=+0.25 alpha=0.05 beta=0.05

## Expected behavior

Since we haven't specified any matches or rounds, I expect that the games will go on till either of hypotheses are proven.

## Actual behavior

The match ends after one game with no info about the sprt behaviour.

## Steps to reproduce the behavior

The command above

**Comment by respel** [comment]
I just noticed that a similar issue exists(https://github.com/cutechess/cutechess/issues/360). Hence closing this one.

**Comment by lucasart** [comment]
> ## Expected behavior
> Since we haven't specified any matches or rounds, I expect that the games will go on till either of hypotheses are proven.

Wrong. There is no `-games inf` option in cutechess-cli, and if you don't specify the number of games, the default value is 1. Same for rounds (default also 1).

Perhaps the documentation should state that clearly.

**Comment by respel** [comment]
@lucasart Thanks for the response. 

> You can't calculate the LLR with 1 game

There is already an existing PR(https://github.com/cutechess/cutechess/pull/625) which fixes this issue by assigning a prior to the 3 variables. 
However, sprt is still not working as expected since it still stops after 1 game. I've pointed out the issue to the author and hopefully, it should be easy to fix.

**Comment by respel** [comment]
Resolved by #625
