### ISSUE TITLE
use "Init Strings" text box in Configure Engine dialog ?

### ISSUE THREAD

**Issue by tissatussa** [cutechess/cutechess#638]
how to use this ?  I have an engine which shows :

_option name UseNNUE type check default false_

how can i set UseNNUE True ?  What should be the "Init String" for that ?

**Comment by alwey** [comment]
There should be a check box available for the configuration of this option. This is a basic function of the GUI.

Tools->Settings->Engines->(select engine in question)->Configure Button->Advanced->(select UseNNUE)->(set box checked)

I hope this helps.

TIP: You can save different settings for the same engine using dedicated names.

**Comment by alwey** [comment]
If you insist to use the init string instead,
`setoption name UseNNUE value true`
should work.

**Comment by alwey** [comment]
If you insist on using the init string instead,
`setoption name UseNNUE value true`
should work.

Reference:  [UCI specification](http://wbec-ridderkerk.nl/html/UCIProtocol.html)

**Comment by tissatussa** [comment]
you are right : there IS a check box available for the configuration of this option .. but i just gave an example .. you gave a proper answer : _setoption name UseNNUE value true_ is the format i wanted to know !  Thanks for that, now it's clear.
