### ISSUE TITLE
Castling rights not taken into account with threefold repetition

### ISSUE THREAD

**Issue by Nordlandia** [cutechess/cutechess#644]
Karpov versus Miles, 1986

See ->
https://en.wikipedia.org/wiki/Threefold_repetition#Karpov_versus_Miles,_1986

**Comment by alwey** [comment]
I think for cutechess positions with different castling rights are different (they have different keys), so no problem here.

**Comment by Nordlandia** [comment]
I tried it and the gui declare a draw when the position is just repeated two times. 

Karpov claims draw with his third move Nb5. But the draw by repetion rule also considers the castling availability. At the first Karpov's Nb5, Anthony Miles still had queen side castling movement. With the second Karpov's Nb5, Anthony Miles had no more the castling available. So, the first position is different of the second by this reason. By a mistake, Karpov claims the draw after his thirt Nb5 move, but the position was repeated only twice.

**Comment by alwey** [comment]
The GUI claims 3-fold repetition only after 26 ... Ra8, which has not been played by Miles.
White to make move 27 in this position
`4kb1r/5ppp/4p3/1N6/r3P3/8/Pn1BK1PP/R6R w k - 10 27` (without q castling rights)
for the third time after 
`4kb1r/5ppp/4p3/1N6/r3P3/8/Pn1BK1PP/R6R w k - 2 23` and
`4kb1r/5ppp/4p3/1N6/r3P3/8/Pn1BK1PP/R6R w k - 6 25`.

I think that is OK.

**Comment by alwey** [comment]
The GUI claims 3-fold repetition only after 26 ... Ra4, which has not been played by Miles.
White to make move 27 in this position
`4kb1r/5ppp/4p3/1N6/r3P3/8/Pn1BK1PP/R6R w k - 10 27` (without q castling rights)
for the third time after 
`4kb1r/5ppp/4p3/1N6/r3P3/8/Pn1BK1PP/R6R w k - 2 23` and
`4kb1r/5ppp/4p3/1N6/r3P3/8/Pn1BK1PP/R6R w k - 6 25`.

I think that is OK.

**Comment by Nordlandia** [comment]
It should repeat for the fourth time shouldn't it, since the repetition start after the second Nb5 commence.

**Comment by alwey** [comment]
I do not see this. The repetition is not complete in the Karpov-Miles game but with an additional half-move 26. ... Ra4 the white player encounters the same position for the third time and this is adjudicated by CuteChess.

```
22. ... Ra4 {book} 23. Nc3 {book} Ra8 {book} 24. Nb5 {book}
Ra4 {book} 25. Nc3 {book} Ra8 {book} 26. Nb5 {book}
Ra4 {Draw by 3-fold repetition} 1/2-1/2
```

```
[Event "?"]
[Site "?"]
[Date "2020.12.25"]
[Round "?"]
[White "alwey"]
[Black "alwey"]
[Result "1/2-1/2"]
[ECO "A57"]
[GameDuration "00:00:06"]
[GameEndTime "2020-12-25T17:50:14.493 CET"]
[GameStartTime "2020-12-25T17:50:07.927 CET"]
[Opening "Benko gambit half accepted"]
[PlyCount "52"]
[TimeControl "60+0.6"]

1. d4 {book} Nf6 {book} 2. c4 {book} c5 {book} 3. d5 {book} b5 {book}
4. cxb5 {book} a6 {book} 5. e3 {book} Bb7 {book} 6. Nc3 {book} Qa5 {book}
7. Bd2 {book} axb5 {book} 8. Bxb5 {book} Qb6 {book} 9. Qb3 {book} e6 {book}
10. e4 {book} Nxe4 {book} 11. Nxe4 {book} Bxd5 {book} 12. Qd3 {book} Qb7 {book}
13. f3 {book} c4 {book} 14. Bxc4 {book} Bxc4 {book} 15. Qxc4 {book} d5 {book}
16. Qc2 {book} dxe4 {book} 17. Qxe4 {book} Qxe4+ {book} 18. fxe4 {book}
Nd7 {book} 19. Ne2 {book} Nc5 {book} 20. Nc3 {book} Nd3+ {book} 21. Ke2 {book}
Nxb2 {book} 22. Nb5 {book} Ra4 {book} 23. Nc3 {book} Ra8 {book} 24. Nb5 {book}
Ra4 {book} 25. Nc3 {book} Ra8 {book} 26. Nb5 {book}
Ra4 {Draw by 3-fold repetition} 1/2-1/2
```

**Comment by alwey** [comment]
Cutechess adjudicates early as soon as any player may claim three-fold repetition or 50 moves without Pawn advance or capture. It does not wait until the arbiter is required to adjudicate (e.g. 5-time repetition of position, and 75-moves-rule).

**Comment by Nordlandia** [comment]
Positions are considered the same if
(1) the same player has the move,
(2) pieces of the same kind and color occupy the same squares, and
(3) the possible moves of all the pieces are the same.
Under (3) above, positions are not considered to be the same if:
(a) in the first position, a pawn could have been captured en passant (by the en passant rule, in the subsequent positions, the pawn cannot be captured en passant anymore), or
(b) either player has lost a right to castle, i.e. either king or one of the rooks has been moved, in between repetitions of the position.

So 22. Nb5 and 24. Nb5 is two different positions. The repetition start after 24. Nb5.

**Comment by rwbc** [comment]
> 
> 
> Positions are considered the same if
> (1) the same player has the move,
> (2) pieces of the same kind and color occupy the same squares, and
> (3) the possible moves of all the pieces are the same.
> Under (3) above, positions are not considered to be the same if:
> (a) in the first position, a pawn could have been captured en passant (by the en passant rule, in the subsequent positions, the pawn cannot be captured en passant anymore), or
> (b) either player has lost a right to castle, i.e. either king or one of the rooks has been moved, in between repetitions of the position.
> 
> So 22. Nb5 and 24. Nb5 is two different positions. The repetition start after 24. Nb5.

And what has this to do with alweys reply?
He showed you already twice that CuteChess correctly applies a draw after a three time repetion after 26...Ra4 sigh...

Your problem is no problem for CuteChess and it is just imagined.
And before you nag others too, Winboard also handles it correctly.

**Comment by Nordlandia** [comment]
It need one additional sequence of repetition to declare it a draw according the rules.

**Comment by alwey** [comment]
Cutechess adjudicates early as soon as any player may claim three-fold repetition or 50 moves without Pawn advance or capture. It does not wait until the arbiter is required to adjudicate (e.g. 5-time repetition of position, and 75-moves-rule).

**Comment by Nordlandia** [comment]
I'm confused 🤔

**Comment by alwey** [comment]
@Nordlandia:Please provide a PGN  where CuteChess adjudicates wrongly because of forgetting about castling rights.

**Comment by Nordlandia** [comment]
[Event "?"]
[Site "i7-5930K 4.5GHz"]
[Date "2020.12.25"]
[Round "?"]
[White "sortl"]
[Black "sortl"]
[Result "1/2-1/2"]
[FEN "r3kb1r/5ppp/4p3/8/4P3/2N5/Pn1BK1PP/R6R w kq - 0 22"]
[GameDuration "00:00:28"]
[GameEndTime "2020-12-25T19:52:25.258 Vest-Europa (normaltid)"]
[GameStartTime "2020-12-25T19:51:56.590 Vest-Europa (normaltid)"]
[PlyCount "10"]
[SetUp "1"]
[TimeControl "450+7.5"]

1. Nb5 Ra4 {1.42s} 2. Nc3 {0.88s} Ra8 {1.94s} 3. Nb5 {4.19s} Ra4 {14.11s}
4. Nc3 {0.69s} Ra8 {0.72s} 5. Nb5 {1.64s} Ra4 {1.28s, Draw by 3-fold repetition}
1/2-1/2

**Comment by rwbc** [comment]
> 
> 
> [Event "?"]
> [Site "i7-5930K 4.5GHz"]
> [Date "2020.12.25"]
> [Round "?"]
> [White "sortl"]
> [Black "sortl"]
> [Result "1/2-1/2"]
> [FEN "r3kb1r/5ppp/4p3/8/4P3/2N5/Pn1BK1PP/R6R w kq - 0 22"]
> [GameDuration "00:00:28"]
> [GameEndTime "2020-12-25T19:52:25.258 Vest-Europa (normaltid)"]
> [GameStartTime "2020-12-25T19:51:56.590 Vest-Europa (normaltid)"]
> [PlyCount "10"]
> [SetUp "1"]
> [TimeControl "450+7.5"]
> 
>     1. Nb5 Ra4 {1.42s} 2. Nc3 {0.88s} Ra8 {1.94s} 3. Nb5 {4.19s} Ra4 {14.11s}
> 
>     2. Nc3 {0.69s} Ra8 {0.72s} 5. Nb5 {1.64s} Ra4 {1.28s, Draw by 3-fold repetition}
>        1/2-1/2
> 
> 
> Also it seems that CuteChess declares draw after two times repetition without cases of castling flags involved.

You don't even understand the meaning of three time repetitions? I thought you are a tournament player yourself, like me?

It means a position **appears three times** (being the same with all mentioned rights granted again) not that it must be repeated three times (**that would be already appearing the 4th time** for the same position)
I am out here now, as it seems to lead to nothing.

**Comment by Nordlandia** [comment]
With castling flags it need to be repeated 3 times. Without castling flags 2 times is needed before it's declared a draw.

**Comment by rwbc** [comment]
1. nonsense
2. the repetition rule is always the same with all positions **with the same granted rights** if such a position appears the third time it is draw - period
3. you start to create your own fantasys rules
4. after 22...Ra4 there is already no castling flag anymore
5. you insist on being stubborn for no reason - we call this trolling

**Comment by alwey** [comment]
Let's cool down and list all FEN s of the provided PGN example
Initial position
`r3kb1r/5ppp/4p3/8/4P3/2N5/Pn1BK1PP/R6R w kq - 0 22`

`r3kb1r/5ppp/4p3/1N6/4P3/8/Pn1BK1PP/R6R b kq - 1 22`
`4kb1r/5ppp/4p3/1N6/r3P3/8/Pn1BK1PP/R6R w k - 2 23` (after 22. ... Ra4 q-castling is gone)
`4kb1r/5ppp/4p3/8/r3P3/2N5/Pn1BK1PP/R6R b k - 3 23`
`r3kb1r/5ppp/4p3/8/4P3/2N5/Pn1BK1PP/R6R w k - 4 24`
`r3kb1r/5ppp/4p3/1N6/4P3/8/Pn1BK1PP/R6R b k - 5 24`
`4kb1r/5ppp/4p3/1N6/r3P3/8/Pn1BK1PP/R6R w k - 6 25` (after 24. .... Ra4)
`4kb1r/5ppp/4p3/8/r3P3/2N5/Pn1BK1PP/R6R b k - 7 25`
`r3kb1r/5ppp/4p3/8/4P3/2N5/Pn1BK1PP/R6R w k - 8 26`
`r3kb1r/5ppp/4p3/1N6/4P3/8/Pn1BK1PP/R6R b k - 9 26`
`4kb1r/5ppp/4p3/1N6/r3P3/8/Pn1BK1PP/R6R w k - 10 27` (after 26. ... Ra4) 
The same position with the same en passant and castling rights is reached for the third time -
Cutechess steps in and adjudicates a draw.

**Comment by Nordlandia** [comment]
I don't intend to start a dispute or something. 

It's so strange when wikipedia say "second time only" after 26. Nb5.

**Comment by alwey** [comment]
No problem.

For Miles with Black, it is only the second equal position after Karpov's 26. Nb5. They drew the game by agreement, actually. If 26. ... Ra4 would have been played by Milles, then Karpov could correctly have claimed a draw by repetition of position (3rd occurrence: original, first repetition, second repetition).  Cutechess would do this for Karpov within a  millisecond.


Cutechess **claims on behalf of any player** to make games short, surely more than 99,9% of these games being engine-engine games.

FIDE Handbook - Laws of Chess

9.2

The  game  is  drawn  upon  a  correct  **claim  by  the  player  having  the  move,**  when  the  **same  position, for at least the third time** (not necessarily by a repetition of moves):
 a. is about to appear, if he first writes his move on his scoresheet and declares to the arbiter his intention to make this move, or

b. **has just appeared, and the player claiming the draw has the move.**

Positions  as  in  (a)  and (b)  are considered  the  same,  if  the  same  player  has  the  move,  **pieces of the same kind and colour occupy the same squares, and the possible moves of all the pieces of both players are the same**. Positions  are  not  the  same  if  a  pawn  that  could  have  been  captured  en  passant  can  no longer be captured in this manner. When a king or a rook is forced to move, it will lose its castling rights, if any, only after it is moved.
