### ISSUE TITLE
Random opening order in swiss tournaments

### ISSUE THREAD

**Issue by dsmsgms** [cutechess/cutechess#652]
Just initially randomizing the opening suite does not lead to a good result in swiss tournaments, because the opening order is repeated time over time. TCEC just had a Swiss test and it seems this could cause trouble if there were a Swiss tournament for real between engines. Would it be good to change the default behavior?

**Comment by rwbc** [comment]
CuteChess has no swiss mode implemented. May be you wanted to create an issue in a certain TCEC fork?
