### ISSUE TITLE
error when compile on MacOS

### ISSUE THREAD

**Issue by ArminHHJ** [cutechess/cutechess#660]
OS 10.15.7
Homebrew updated
QT installed (v6)

like the documentation to cutechess.

Armins-MacBook-Pro:~ armin$ **git clone https://github.com/cutechess/cutechess.git**
Cloning into 'cutechess'...
remote: Enumerating objects: 18119, done.
remote: Total 18119 (delta 0), reused 0 (delta 0), pack-reused 18119
Receiving objects: 100% (18119/18119), 7.57 MiB | 2.07 MiB/s, done.
Resolving deltas: 100% (10278/10278), done.
Armins-MacBook-Pro:~ armin$ **cd cutechess**
Armins-MacBook-Pro:cutechess armin$ **qmake**
Info: creating stash file /Users/armin/cutechess/.qmake.stash
Armins-MacBook-Pro:cutechess armin$ **make**
cd projects/ && ( test -e Makefile || /usr/local/opt/qt/bin/qmake -o Makefile /Users/armin/cutechess/projects/projects.pro ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
cd lib/ && ( test -e Makefile || /usr/local/opt/qt/bin/qmake -o Makefile /Users/armin/cutechess/projects/lib/lib.pro ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -Wextra -O2 -fPIC -std=gnu++1z  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -Wall -Wextra -DLIB_EXPORT= -DZ_PREFIX -DNDEBUG -DQT_NO_DEBUG -DQT_CORE_LIB -I. -Isrc -Icomponents/json/src -I3rdparty/fathom/src -I/usr/local/Cellar/qt/6.0.3/lib/QtCore.framework/Headers -I.moc -I/usr/local/Cellar/qt/6.0.3/share/qt/mkspecs/macx-clang -F/usr/local/Cellar/qt/6.0.3/lib -o .obj/board.o src/board/board.cpp
In file included from src/board/board.cpp:19:
src/board/board.h:34:7: error: definition of type 'QStringList' conflicts with
      type alias of the same name
class QStringList;
      ^
/usr/local/Cellar/qt/6.0.3/lib/QtCore.framework/Headers/qcontainerfwd.h:65:7: note: 
      'QStringList' declared here
using QStringList = QList<QString>;
      ^
src/board/board.cpp:307:14: error: no member named 'midRef' in 'QString'
                rank = str.midRef(1).toInt(&ok) - 1;
                       ~~~ ^
src/board/board.cpp:312:24: error: no member named 'leftRef' in 'QString'
                file = m_width - str.leftRef(tmp).toInt(&ok);
                                 ~~~ ^
src/board/board.cpp:357:13: error: use of undeclared identifier 'QRegExp'
        str.remove(QRegExp("[x=+#!?]"));
                   ^
src/board/board.cpp:579:21: error: no member named 'midRef' in 'QString'
                                nempty = token->midRef(i, 2).toInt();
                                         ~~~~~  ^
5 errors generated.
make[2]: *** [.obj/board.o] Error 1
make[1]: *** [sub-lib-make_first-ordered] Error 2
make: *** [sub-projects-make_first] Error 2
Armins-MacBook-Pro:cutechess armin$

**Comment by rwbc** [comment]
According to the issue below it seems it might still crash, if compiling could be ensured.
OTH this issue was commented not long ago and there is hope for the mentioned patches.

https://github.com/cutechess/cutechess/issues/640

**Comment by artoj** [comment]
See PR #661

**Comment by artoj** [comment]
I'm merged in compatibility with Qt 6. Please create a new issue if you spot any regressions.

**Comment by ArminHHJ** [comment]
it work now. thanks.
