### ISSUE TITLE
Incorrect adjudication with 'whitepov' option

### ISSUE THREAD

**Issue by zz4032** [cutechess/cutechess#664]
With `whitepov` defined in engine's options, games are adjudicated incorrectly as a win for White, if Black gives a negative score (advantage for Black) below the adjudication threshold.

Example with `-resign movecount=3 score=500` and `whitepov` for both engines:

`1. b3 {book} e6 {book} 2. Bb2 {book} a6 {book} 3. e4 {book} b6 {book} 4. g3 {+0.42/11 3.7s} Bb7 {+0.28/30 2.9s}`
...
`35. Qe2 {+0.09/21 0.21s} Nxf3 {-1.88/29 0.62s} 36. Nf4 {+0.13/20 0.21s} Rg8 {-6.83/24 0.55s} 37. Qxe3 {-6.52/13 5.3s} Nh4+ {-M49/42 0.54s} 38. Kh2 {-7.77/1 0s} Rg2+ {-M25/59 0.58s, White wins by adjudication} 1-0`

**Comment by alwey** [comment]
Hi @zz4032, I have some questions:

In the example game  
1. were both engines CECP (xboard) engines?
2. Did the adjudication depend on the losing side's scores (this is the default) or on all scores?
3. Has the trust feature been used (default: no) for any engine?

**Comment by zz4032** [comment]
1. Both engines were UCI engines (`proto=uci`).
2. On the losing side's score.
3. `trust` has not been used. Problem still occurs, if `trust` is activated.

To me it looks like nothing is wrong with the engines' evaluations. Cutechess seems not to take into account that with `whitepov` Blacks negative score means an advantage.

**Comment by alwey** [comment]
The `whitepov` option is used to tell cutechess the POV _of CECP engines_: If `whitepov` set to true, cutechess assumes the engine communicates the scores as white side's advantage. E.g  _Crafty_, _Aice_, and _Dreamer_ use this scoring method. The default value for `whitepov` is false. In this case Cutechess assumes a positive score means an advantage for the reporting CECP engine. This is also the case for all UCI engines as specified by the UCI protocol.

From the manual page of cutechess-cli:

```
     whitepov
             Invert the engine's scores when it plays black. This option
             should be used with engines that always report scores from
             white's perspective.

```

So this option is not intended for UCI engines playing Black.

**Comment by alwey** [comment]
Related to #162

**Comment by zz4032** [comment]
Ok, I misunderstood the available option in that case. #162 is what I had in mind.
