### ISSUE TITLE
Opening move not used, if leading to 3-fold repetition

### ISSUE THREAD

**Issue by zz4032** [cutechess/cutechess#666]
## Output of `cutechess-cli --version` / `cutechess --version`
cutechess-cli 1.2.0
Using Qt version 5.12.8
Running on Ubuntu 20.04 LTS/x86_64
## How did you run Cute Chess exactly?
./cutechess-cli -pgnout ./games.pgn -tournament gauntlet -openings file=./book.txt format=pgn plies=40 -rounds 1 -games 1 -engine cmd=./stockfish-dev name=stockfish-dev -engine cmd=./stockfish-dev name=stockfish-dev -each proto=uci tc=1+0.1
Book is attached: [book.txt](https://github.com/cutechess/cutechess/files/6409028/book.txt)
## Expected behavior
With option `plies=40` all 25 plies should be played from the opening book.
## Actual behavior
There is a 3-fold repetition at move 13 (ply 25) in the book and instead of immediately adjudicating the game, move 13 is omitted and game starts with move 12 out of the book (engine chooses a different 13th move and the game continues).

**Comment by alwey** [comment]
I think this is no bug, but intended behaviour.

**Comment by alwey** [comment]
The moves of opening suites are only played as far as they do not cause the game to end, e.g. by checkmate, stalemate or draw by adjudication. It also does not replay illegal moves. Cutechess automatically adjudicates the fifty-move-rule, threefold repetition, and known cases of insufficient material.

If ok, please close this issue.

**Comment by zz4032** [comment]
Ok, I didn't know about this. I would prefer Cutechess to play the book move and end the game as a draw.

**Comment by alwey** [comment]
If I understand correctly, your use case is to replay a set of games and extend them in re-play if possible. If not, let the games be adjudicated automatically?
