### ISSUE TITLE
Time Control Bug

### ISSUE THREAD

**Issue by MandiYang** [cutechess/cutechess#688]
## Output of `cutechess-cli --version` / `cutechess --version`
```
cutechess-cli 1.2.0
Using Qt version 5.12.8

Copyright (C) 2008-2020 Ilari Pihlajisto, Arto Jonsson and contributors
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
Cute Chess 1.2.0
Using Qt version 5.12.8

Copyright (C) 2008-2020 Ilari Pihlajisto, Arto Jonsson and contributors
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
## How did you run Cute Chess exactly?

 Run `cutechess` command on terminal. 

## Expected behavior

White or Black looses

## Actual behavior

Game goes on.

## Steps to reproduce the behavior

1. Set time control to something
2. Start the game and wait until the time goes to zero.

**Screenshots**

![Screenshot from 2021-12-19 12-04-17](https://user-images.githubusercontent.com/64307609/146673220-8bc80227-95cb-4065-93e2-ec4260e57e4a.png)

**Comment by alwey** [comment]
This is a feature of version 1.0.0, requested in #134.

You can disable this behaviour via Tools->Settings->General. Untick the "Human player can play after timeout".

If the problem has been solved, please close this issue.
