### ISSUE TITLE
Error building on macOS using homebrew

### ISSUE THREAD

**Issue by jconsidi** [cutechess/cutechess#689]
## Output of `cutechess-cli --version` / `cutechess --version`

Initial output of qtdiag 
```
Qt 6.2.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 13.0.0 (clang-1300.0.29.3) (Apple)) on "cocoa" 
OS: macOS 12.0 [darwin version 21.1.0]
```

Trying to compile from the current master https://github.com/cutechess/cutechess/commit/8cd2d7929a542cd4f8fcdaa54ac49c9565cbd746

## How did you run Cute Chess exactly?

I was trying to follow [these instructions](https://github.com/cutechess/cutechess/wiki/Building-from-source#macos) for a source build

```
$ brew install qt
$ git clone https://github.com/cutechess/cutechess.git
$ cd cutechess
$ qmake
$ make
```

## Expected behavior

Expected a successful build...

## Actual behavior

The build fails with these errors when running make -
```
.moc/moc_qcustomplot.cpp:249:35: error: unexpected namespace name 'QCP': expected expression
, QtPrivate::TypeAndForceComplete<QCP, std::true_type>
                                  ^
1 error generated.
make[2]: *** [.obj/moc_qcustomplot.o] Error 1
make[1]: *** [sub-gui-make_first-ordered] Error 2
make: *** [sub-projects-make_first] Error 2
```

## Steps to reproduce the behavior

1. Install/update home-brew on macOS 12.0.1
2. brew install qt
3. git clone https://github.com/cutechess/cutechess.git
4. cd cutechess
5. qmake
6.  make

**Comment by artoj** [comment]
On Mon, Dec 20, 2021 at 19:16:35 -0800, Jeffrey Considine wrote:
> ```
> .moc/moc_qcustomplot.cpp:249:35: error: unexpected namespace name 'QCP': expected expression
> , QtPrivate::TypeAndForceComplete<QCP, std::true_type>
>                                   ^
> ```

Thanks for the report. I see it on my system also but nothing has changed
on our end. There's an unofficial patch floating around:
https://www.qcustomplot.com/index.php/support/forum/2380

I'll wait a few days after the holidays and if there's no official patch
release from QCustomPlot, I'll apply the unofficial patch.

Can you file an issue updating the Github CI to include a Qt 6.2 build?
