### ISSUE TITLE
Security of releases

### ISSUE THREAD

**Issue by artoj** [cutechess/cutechess#69]
Currently we don't sign our releases or provide the binaries over HTTPS. This is something that we want to address for 1.0. While Cute Chess probably isn't the  main target for tampering we want to be sure that what we release is what people get.

At minimum we should sign the release commits using the tools available in git and serve the binaries (with checksums) over HTTPS. This should be pretty straightforward with services such as Let's Encrypt.

**Comment by ilaripih** [comment]
I'm thinking that we could host cutechess.com and the downloads at a "real" server, eg. a 5$/mo Digital Ocean node and get a HTTPS certificate from Let's Encrypt. In the future (after 1.0) we could run the yet-to-be-written game broadcasting service on the same server.

**Comment by ilaripih** [comment]
I think the problem is solved - it's possible to attach binaries to Github releases, which I just did: https://github.com/cutechess/cutechess/releases/tag/cli-0.8.2

The download links use HTTPS.

**Comment by artoj** [comment]
Ok, that's good. I think we should also include the checksums of those files in the (Github) release notes.

**Comment by ilaripih** [comment]
I added SHA-1 checksums to the cli-0.8.2 release notes.

**Comment by artoj** [comment]
From the next release onwards we should use SHA2-256 sums but that's fine for now. Closing.
