### ISSUE TITLE
Allow duplicates with different parameters

### ISSUE THREAD

**Issue by anonymous7002** [cutechess/cutechess#690]

**Comment by alwey** [comment]
Cutechess GUI does this already and of course the CLI is used like that all the time, e. g. for parameter tuning. 

GUI Example:  Tournament->New

Use the `+` to add an engine. Add it twice. Use the"tool"-button to modify the parameters of the second instance. Do not forget to modify the name of this instance else the tournament will not start. If all engine parameters are set, click OK. Set up the tournament parameters, then click OK.

You can also play single games with the same engine with different configurations or  parameters: Game->New. Select the same engine (configuration) for White and for Black. Modify the configuration for one of them (tool-button).

If you want to clone and modify a permanent engine configuration, use Tools->Settings->Engines. Select the original engine configuration and click the clone button (4th from the left) to clone and modify the configuration. Click OK when finished. The new configuration now appears in the list of available engine configurations.

HTH.

If OK, please close this issue.
