### ISSUE TITLE
Menu shortcuts

### ISSUE THREAD

**Issue by jherrera80** [cutechess/cutechess#70]
In the menu bar, ALT+G alternates between Game and Engines menus (both have an underscore on the g). The letter 'E' is unused, why not use ALT+E for Engines?

**Comment by ilaripih** [comment]
Please check out #59 - engine configuration will probably become a part of a new settings dialog.

**Comment by jherrera80** [comment]
Ok, closing it then.

**Comment by artoj** [comment]
Re-opening. The menu shortcuts are missing from some entries. I'll take a look at this.

**Comment by artoj** [comment]
Done in f1bd713.
