### ISSUE TITLE
Changing variant does not enable supported list of engines

### ISSUE THREAD

**Issue by artoj** [cutechess/cutechess#703]
## Output of `cutechess-cli --version` / `cutechess --version`

Cute Chess 1.2.0+git latest master as of Jan 19 2022
Using Qt version 6.2.2
Running on macOS 11.6/x86_64

## How did you run Cute Chess exactly?

cutechess &

## Expected behavior

In New Game window, changing the value of variant should enable the list of engines that support that particular variant.

## Actual behavior

Changing the variant does *not* enable list of engines even though a configured engine supporting that variant exists.

## Steps to reproduce the behavior

1. Configure a chess engine, for example Sloppy.
2. Click Game -> New Game
3. Observe that chancellor variant is selected and CPU player lists are not enabled.
4. Select the standard variant.
5. Observe that CPU player lists are still disabled even though Sloppy supports the standard variant.

In Qt creator the following is printed to console:

```
Cute Chess[905:2133603] [qt.core.qobject.connect] QObject::connect: No such signal QComboBox::currentIndexChanged(QString)
Cute Chess[905:2133603] [qt.core.qobject.connect] QObject::connect:  (sender name:   'm_variantCombo')
Cute Chess[905:2133603] [qt.core.qobject.connect] QObject::connect:  (receiver name: 'GameSettingsWidget')
```

**Comment by alwey** [comment]
Engine list still OK for **Qt-5**.9 and next-to-latest master of 2021-12-29. I guess a type cast must be corrected.

Cute Chess 1.2.0 (6779813 - unbreak the build on Qt 6.2.2)
Using Qt version 5.9.5
Running on Ubuntu 18.04.6 LTS/x86_64

**Comment by artoj** [comment]
That was fast, thanks! I'll merge your PR and create another issue for the underlying issue, that is, using SIGNAL and SLOT macros instead of the QObject methods. This problem should have been found during compile time --- not runtime. The uses of those macros should be removed.
