### ISSUE TITLE
Wrong lose on time if insufficient mating material

### ISSUE THREAD

**Issue by voyag** [cutechess/cutechess#710]
In this position:
`8/8/8/4k3/4p3/4N3/4K3/8 w - - 0 1`
if black run out of time it's a draw because white has insufficient mating material, while cutechess give white a win.

**Comment by mhouppin** [comment]
According to FIDE rules, section 6.9:

> [...] If a player does not complete the prescribed number of moves in the allotted time, the game is lost by the player. However, the game is drawn, if the position is such that the opponent cannot checkmate the player’s king by any possible series of legal moves.

Cutechess is right in giving the winning point to White, since there exists a sequence of legal moves in which White mates Black. For example:

```
[Variant "From Position"]
[FEN "8/8/8/4k3/4p3/4N3/4K3/8 w - - 0 1"]

1. Kd2 Kf4 2. Nc4 e3+ 3. Kd3 e2 4. Nd2 e1=R 5. Kd4 Kg3
6. Kd3 Kh2 7. Kd4 Kh1 8. Ne4 Rg1 9. Ke3 Rd1 10. Kf3 Re1
11. Kg3 Rf1 12. Kh3 Rg1 13. Nf2#
```

**Comment by voyag** [comment]
And in this position:
`8/8/3rk3/8/8/2K5/8/8 w - - 0 1`
how can the white king checkmate the opponent?

**Comment by alwey** [comment]
This example is valid.
