### ISSUE TITLE
Chess protocol was not started in time when using getchar(), scanf(), gets()

### ISSUE THREAD

**Issue by vierbaum** [cutechess/cutechess#737]
I've been writing a simple chess engine in c over the last couple of weeks.
When trying to impement the UCI protocol and linking it up to cutechess I had the problem that cutechess sends the error "Chess protocol was not started in time". After a bit of debugging i found out, that my code works when reading stdin via std::getline (c++) but not when using gets(), scanf() or getchar(). The engine reads stdin and writes to stdout (I know this for sure as I implemented a log file) but cutechess does not seem to read the stdout of my engine
here are my 2 implementations, if there's something wronge in my code, let me know
`int think(std::string input) {

    if (input == "isready")
      printf("readyok\n");

    if (input == "uci")
      printf("id name engine\nid author nld\n\noption name test type spin default 1 min 1 max 512\nuciok\n");

    if (input == "quit")
      return 0;
    return 1;
}
int main(int argc, char *argv[]) {
  std::string s;
  char c, i = 0;
  while (1) {
    std::getline(std::cin, s);
    if(!think(s)) return 0;
  }
}`
And the not working c implematation
`  char* input;
  size_t size = 128;
  input = (char*) malloc(size * sizeof(char));
  char c, i = 0;
  while (1) {
    while ((c = getchar()) != '\n') {
      *(input + i) = c;
      i++;
    }
    *(input + i) = '\0';
    i = 0;
    if(!think(input)) return 0;
  }
  return 0;`
  with think() being essentially the same function.

**Comment by jxu** [comment]
This is likely an issue with your own engine, not cute chess. If you use C style string handling maybe it's an issue with file streams or flushing the buffer.

**Comment by artoj** [comment]
This seems to be issue with the engine rather than Cute Chess.
