### ISSUE TITLE
Realtime engine statistics

### ISSUE THREAD

**Issue by ilaripih** [cutechess/cutechess#74]
As mentioned in issue #33 we should show at least the following realtime statistics somewhere, maybe in the EvalWidget:

- [x] Nodes per second
- [x] Tablebase hits
- [x] Hash table usage
- [x] Current ponder move
- [x] Ponderhit percentage

**Comment by alwey** [comment]
I would rather keep the number of nodes, too. This is primary information from the engines like the tablebase hit counts.

**Comment by ilaripih** [comment]
All done for UCI mode. I'll create a new issue about implementing some of these features for Xboard engines. It's not so urgent because very few Xboard engines currently report tbhits, hash table usage, etc.
