### ISSUE TITLE
Navigate move list with arrows

### ISSUE THREAD

**Issue by mcostalba** [cutechess/cutechess#75]
Allow to navigate move list back and forth with keyboard, not only with mouse. Usually other GUI use left and right arrow, respectively for back and forth.

**Comment by ilaripih** [comment]
You can already do that if you put input focus (ie. click) on the slider under the board. But it would make sense that the same functionality would work when the input focus is on the move list.

**Comment by mcostalba** [comment]
Thanks for your quick reply: I tried hard to use keyboard but without success (I missed the focus on the slider). 

Yes, keyboard navigation with focus on the list is the most "natural" behavior and definitely what  average user would expect. At least it is for me :-)

**Comment by ilaripih** [comment]
Now it's possible to use the left and right arrow keys to select moves when the MoveList widget has input focus.

**Comment by mcostalba** [comment]
Thanks!
