### ISSUE TITLE
CLI : set "whole game" in tc parameter ?

### ISSUE THREAD

**Issue by tissatussa** [cutechess/cutechess#753]
i can set command line parameter `tc=80/180+2` and it works : 180 seconds for 80 moves plus 2 sec bonus .. in GUI i can also select "whole game", not only 80 sec .. how can this be set in CLI ? I tried `tc=/180+2` but it doesn't work. Btw. i could do `tc=10000/180+2` but ala ..

**Comment by alwey** [comment]
Please try `tc=180+2` .

**Comment by alwey** [comment]
Any feedback?

**Comment by tissatussa** [comment]
> Any feedback?

indeed something like `tc=180+2` works .. i was adding '/' but your syntax just lacks it .. thanks.
