### ISSUE TITLE
Invalid Adjudication of Fisherandom Games

### ISSUE THREAD

**Issue by stevemisc** [cutechess/cutechess#756]
## How did you run Cute Chess exactly?
Include the full command-line used to run the application. In case the `-conf` parameter was used, include the relevant engine configurations from the configuration file.

### Machine
Dell i9 Laptop with 32 Gb of RAM and 14 cores

### engines.json
```
[  
	{    
		"name": "Maverick",    
		"command": "..\\Maverick\\Downloads\\2015-10-28\\maverick64.exe",      
		"protocol": "uci"  
	},  
	{	"name": "Stockfish",
		"command": "..\\..\\Engines\\Stockfish\\15.1\\stockfish-windows-2022-x86-64-avx2.exe",
		"protocol": "uci"
	},  
	{   "name": "Komodo",
		"command": "..\\..\\Engines\\Komodo\\Dragon 3.2\\dragon-3.2-64bit-avx2.exe",
		"protocol": "uci"  
	}
]
```

### Command Line
`cutechess-cli -variant fischerandom -engine conf=Komodo -engine conf=Stockfish -each option.Hash=128 timemargin=5 book=Maverick2018.bin tc=inf depth=4 -pgnout test_games.pgn -concurrency 8 -games 100 -wait 5`

## Expected behavior
I expected 100 fisherrandom / chess960 games between Komodo and Stockfish, each engine searching to a depth of 4 ply for each move. I expected valid adjudication of the games

## Actual behavior
The adjudication of the games was junk. Mates were claimed when they wasn't a mate, draw by 50 move rule was claimed after 15 moves etc! Here's a link to the PGN output. 

[PGN Output](https://www.dropbox.com/s/9q4os1cw68ben3k/test_games.pgn?dl=0)

## Steps to reproduce the behavior

1. Set up the engines 
2. Run the command line as above
3. Wait until the games have finished
4. Inspect the PGN output

**Screenshots**
NA

**Comment by alwey** [comment]
Problems with Chess960 have been reported in #616 and #637. Please apply patch #617 which fixes generalized (Chess960) castling. This patch has already been tested with 1,5 million games without encountering an error.
