### ISSUE TITLE
Possible move trace resides

### ISSUE THREAD

**Issue by lsap** [cutechess/cutechess#759]
cutechess 1.0.0

It was started like any GUI application (from start menu).

Expected behavior

Traces disappear after the move.

Actual behavior

Traces are there until the next move.

Steps to reproduce the behavior

Play with Stockfish for black:
1. d4 c6
2. Nc3 d5
3. e4 dxe4
4. Nxe4 Nd7
5. c3 Ngf6
6. Nxf6+ Nxf6
7. Nf3 Bg4
8. h3 Bxf3
9. Qxf3 Qd5
10. Be2 h5
11. O-O e6
12. Qd3 Qe4
13. Qd1 Bd6
14. Re1 Qh4
15. Bf1 Nd5
16. g3 Qd8
17. h4 Be7
18. Bg2 a5
19. Bf3 Nf6
20. Qb3 Qb8
21. Bf4 Qc8
22. c4 a4
23. Qc3 b6
24. b4 O-O
25. b5 cxb5
26. Bxa8 Qxa8 (this is where I spotted trace)
27. ...

The saved game (PGN) can't be landed here but please specify where to upload it (if needed)

**Comment by alwey** [comment]
Hello, it would be nice to have a screenshot depicting the problem.
Also, we need to know which on platform (Windows/Linux/Mac) the problem occured.

Does the problem also show up with the newest releases [Cute Chess 1.2.0](https://github.com/cutechess/cutechess/releases/tag/1.2.0) or [Cute Chess 1.3.0-beta4](https://github.com/cutechess/cutechess/releases/tag/v1.3.0-beta4)?

**Comment by lsap** [comment]
The problem occured on Kubuntu 20.04. The traces disappear after moves correctly now (Cutechess 1.2.0, Kubuntu 22.04). I can't force stockfish 16 to play the same moves though.

**Comment by alwey** [comment]
Good to hear. You can indeed publish PGN notation here by either inserting the game's content as code (using symbol <> above) or attaching a PGN file by drag & drop or clicking on the section below the text editor and inserting a file from the file selector - this also works on modern Linux browsers.

If the problem does not occur or cannot be reproduced anymore, then please close this issue.

**Comment by lsap** [comment]
Could I reopen it if needed?

**Comment by alwey** [comment]
I guess you can reopen an issue.

Click on the title of the issue that you want to re-open.
At the bottom of the issue, click on the "Reopen Issue" button.
