### ISSUE TITLE
Cutechess does not recognize (mostly) .net Core engines. May crash when adding .net core engine

### ISSUE THREAD

**Issue by Vladimir-Bosnjak** [cutechess/cutechess#760]
## Output of `cutechess-cli --version` / `cutechess --version`
cutechess-cli 1.3.0-beta4
Using Qt version 5.15.2
Running on Windows 10 Version 2009/x86_64

## How did you run Cute Chess exactly?
I simply started the gui.

## Expected behavior
It should recognize my basic Uci compliant interface (.exe) written in .net Core without problems.

## Actual behavior

For .net Core 6 .exe, the gui simply crashed. For .net core 3, it simply didn't recognize the engine.

## Steps to reproduce the behavior

Startup Gui.
Goto "tools - settings - engines"
Try to add .net core engine.
Either crashes or simply does not recognize. Caveat: it recognized it once, and then it didn't.

Important: the previous stable release doesn't recognize .net core engines either. It recognized it once, then started coding and releasing new versions without modifying the Uci protocol, and then it didn't recognize it anymore. Creating new empty engines dind't work. Here's the basic C# .net code. You'll notice that if you start a .net Framework console project, you won't have problems. But if you start a .net Core console project, then it's a gamble and mostly it doesn't work.

Using VS 2022. Windows 10. Here is sample code which you could try out yourself. Just start a C# console project and copy this code, then compile and try out:

```
private static void Main(string[] args)
        {
            while (true)
            {
                string input = ReadInput();

                if (input == null)
                    break;

                string[] tokens = input.Trim().Split();

                if (tokens.Length == 0)
                    continue;

                switch (tokens[0])
                {
                    case "uci":
                        Console.WriteLine($"id name ValChess");
                        Console.WriteLine($"id author Uci2");
                        Console.WriteLine("uciok");
                        break;
                    case "isready":
                        Console.WriteLine("readyok");
                        break;
                    case "position":
                        break;
                    case "go":
                        Console.WriteLine("bestmove e2e4");
                        break;
                    case "ucinewgame":
                        break;
                    case "stop":
                        break;
                    case "quit":
                        break;
                    case "setoption":
                        break;
                    default:
                        break;
                }
            }
        }

        private static string ReadInput()
        {
            return Console.ReadLine();
        }



```

**Comment by tissatussa** [comment]
i recognize being unable to add some engines to CuteChess (GUI) .. they might even seem to run fine in terminal, but CuteChess rejects them : in the "Configure Engine" popup window 'Basic' tab, fill in Name, Command, Working Directory and protocol (UCI) will succeed, but then clicking the 'Advanced' tab may fail : CuteChess tries to communicate by the selected protocol, but the 'handshaking' (uci, ucinewgame .. isready, readyok, etc) doesn't match and/or takes too long and then CuteChess 'aborts' : it can not add the engine .. if you want i can give some example engines which act this way, but i guess several causes exist.

you can try using a debugger like `lldb` or `gdb` (i'm on Linux) .. these tools can give more detailed info .. recently this was helpful for the author of KingFish, solving an issue : https://github.com/colding10/Kingfish/issues/18

**Comment by tissatussa** [comment]
also i recognize your experience _It recognized it once .. then it didn't recognize it anymore_ indeed this is strange, i have no clue why this can happen.

**Comment by Vladimir-Bosnjak** [comment]
I did attach a debugger to my empty engine (there's nothing in yet but a few basic commands), but the debugger is useless here because there's not even handshaking going on. I need some process where I can observe how the initial interaction between cutechess and this console goes. But I don't know how to do that. I'm not an experienced programmer. What is stopping cutechess from even acknowledging the engine? 

Fritz 18 GUI doesn't like it either. SO the problem must be in the .net core console program executable . 
But if don't know how to analyze this. What advanced "debugging" does exist when one doesn't have access to source code? Though Cutechess has sourcecode but it's C++. I just do C#.

**Comment by tissatussa** [comment]
can your engine run in terminal ? Give the `uci` command, then `ucinewgame`, and some `go` command ? You could start with an engine which just does random moves according to the chess rules. I guess CuteChess expects proper handshaking by the UCI protocol, using isready / readyok in the proper way, that's essential .. how CuteChess does this, i don't know.

**Comment by tissatussa** [comment]
i guess these are typical Windows issues .. i'm only on Linux, but i can run .NET programs and engines .. however, some version problems occur here too, i'm not into .NET and i try to avoid it, sorry :-(

**Comment by Vladimir-Bosnjak** [comment]
Turns out for .NET Core 6 (perhaps even earlier .net core projects), the executable needs to be deployed differently.  Some "all-in-one package must be created, or the runtime.config.json file and the dll file must be placed together with the executable.
