### ISSUE TITLE
Stop cutechess-cli run gracefully

### ISSUE THREAD

**Issue by eduherminio** [cutechess/cutechess#764]
Is there an option to stop cutechess-cli gracefully so that it shows the SPRT summary at the end before closing, with the summary of the results?

I'm expecting to see something like this:
```
Score of a - vs b: 373 - 271 - 78  [0.571] 722
...      a playing White: 190 - 134 - 37  [0.578] 361
...      a playing Black: 183 - 137 - 41  [0.564] 361
...      White vs Black: 327 - 317 - 78  [0.507] 722
Elo difference: 49.4 +/- 24.2, LOS: 100.0 %, DrawRatio: 10.8 %
SPRT: llr 2.96 (100.7%), lbound -2.94, ubound 2.94 - H1 was accepted

Player: a
   "Draw by 3-fold repetition": 14
   "Draw by adjudication: maximal game length": 1
   "Draw by fifty moves rule": 9
   "Draw by insufficient mating material": 53
   "Draw by stalemate": 1
   "Loss: Black mates": 134
   "Loss: White mates": 137
   "No result": 5
   "Win: Black mates": 183
   "Win: White mates": 190
Player: b
   "Draw by 3-fold repetition": 14
   "Draw by adjudication: maximal game length": 1
   "Draw by fifty moves rule": 9
   "Draw by insufficient mating material": 53
   "Draw by stalemate": 1
   "Loss: Black mates": 183
   "Loss: White mates": 190
   "No result": 5
   "Win: Black mates": 134
   "Win: White mates": 137
Finished match
```

But in Windows all I get is a crash, sometimes reporting the last games as with no results, sometimes even without that.
v1.3.0-beta4

![image](https://github.com/cutechess/cutechess/assets/11148519/e21c606d-794b-4ae0-9b66-317831ca613f)

**Comment by ilaripih** [comment]
Thanks for the report, this seems to be a new bug. It should be possible to cleanly terminate cutechess-cli with CTRL+C and get the results, but currently it crashes. We'll try to fix this ASAP.

**Comment by eduherminio** [comment]
I've been trying it more and more and sometimes it does return the results.
I have to say that I'm also experiencing crashes anyway when I set the concurrency too high (close or over the number of cores), so maybe it has to do that with.

Let me know if I can help collecting some logs/data anyway.

**Comment by ilaripih** [comment]
I pushed a fix that should at least take care of the crash when terminating the match with Control+C (SIGINT). It is possible that the same bug caused the crashes with high concurrency values, but more testing is needed.

**Comment by ilaripih** [comment]
@eduherminio Do you get crashes with high concurrency values in 2-player matches, or only with more players in the tournament? Can you give an example command line that sometimes results in a crash?

**Comment by eduherminio** [comment]
@ilaripih I'm trying 1.3.1-beta2.
- I haven't been able to reproduce the original issue any more when `ctrl+c`'ing a run, now it seems to finish gracefully whenever I cancel a run. So 👍🏼
- I can't reproduce any more the crashes in 2p matches when high-concurrency, now it also finishes gracefully, so also 👍🏼
  By crashes I mean the `cutechess-cl.exe has stopped working` windows; for me it's still being problematic to go run too many games concurrently.

But regarding that last statement, after enabling some internal logs it seems to be somehow on my end anyway, due to the different running instances of the same binary trying to white to the same file:
`2023-07-30 15:20:33.6578 Error FileTarget(Name=logs): Failed write to file 'logs-2023-07-30.log'. Exception: System.IO.IOException: The process cannot access the file logs-2023-07-30.log' because it is being used by another process.`

----

I'm using this pwsh script:
````pwsh
&"cutechess-1.3.1-beta2-win64\cutechess-cli.exe" `
-engine conf="Lynx 958 - tt move ord" `
-engine conf="Lynx 0.14.1" `
-each `
    tc=inf/15+1 `
    book="Perfect_2021\BIN\Perfect2021.bin" `
    bookdepth=8 `
	option.Hash=64 `
-games 2 -rounds 2500 -repeat 2 -maxmoves 300 `
-sprt elo0=0 elo1=10 alpha=0.05 beta=0.05 `
-concurrency 10 `
-ratinginterval 10 `
-pgnout "matches\extend-depth-on-check.pgn"
```

**Comment by ilaripih** [comment]
Thanks! I'm running some high concurrency tests as well, and will try your script too. I'll close this issue as the "stopping gracefully" part is now fixed, but we can still continue the topic of high concurrency values + crashes at https://github.com/cutechess/cutechess/issues/757
