### ISSUE TITLE
Command Prompt opens when I open Cutechess

### ISSUE THREAD

**Issue by Dominiquini** [cutechess/cutechess#765]
## Output of `cutechess-cli --version` / `cutechess --version`

Cute Chess 1.3.0
Using Qt version 5.15.2
Running on Windows 10 Version 2009/x86_64

Copyright (C) 2008-2020 Ilari Pihlajisto, Arto Jonsson and contributors
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

## How did you run Cute Chess exactly?

Click on the shortcut on the start menu

## Expected behavior

Open only the windows of the Cutechess program

## Actual behavior

A command prompt opened and soon after the program window

## Steps to reproduce the behavior

1. Open Cute Chess on the start menu
2. See the 2 windows opened!

**Screenshots**

![QAIh7RJjAQ](https://github.com/cutechess/cutechess/assets/1180808/9338771f-a4bc-4898-9b13-eb8943b17fc8)

**Comment by Ipmanchess** [comment]
Same here..for the rest it runs well..

**Comment by artoj** [comment]
Do you have the possibility to build Cute Chess from source? I created a commit that should fix the issue: 9da2d3a in master

**Comment by artoj** [comment]
Fixed in 1.3.1.
