### ISSUE TITLE
"Advanced" tab empty for Leela Chess Zero

### ISSUE THREAD

**Issue by OverLordGoldDragon** [cutechess/cutechess#773]
1. Installed latest [cutechess-1.3.1-win64.exe](https://github.com/cutechess/cutechess/releases/tag/v1.3.1) (Windows 11)
  2. `Tools > Settings > Engines > Default Location > lc0/build`
  3. `Tools > Settings > Engines > + > Command > stockfish.exe [from another directory]` -> it's added, and `Advanced` works
  4. `Tools > Settings > Engines > + > Command > lc0.exe` -> it's added, but `Advanced` is empty ([example instructions](https://lczero.org/play/gui/cutechess/))

I built `lc0.exe` from source with Python/Anaconda, and set working directory to `lc0/build/`, which contains `lc0/build/lc0.exe`. I've changed nothing else, `Protocol` is `uci`. Both engines work in Nibbler and Arena.

**Comment by mooskagh** [comment]
Try running `lc0.exe` outside of CuteChess. Just start it, type `go nodes 10000`, and check whether it shows any errors (or paste a screenshot here).

I suspect it's a Lc0 configuration issue rather than CuteChess. If so, I suggest asking in the `#help` channel of the Lc0 discord chat at http://lc0.org/chat

**Comment by OverLordGoldDragon** [comment]
The default configs fail. I'll try the Discord, thanks.

<img src="https://github.com/cutechess/cutechess/assets/16495490/dbb3d309-8c63-4c5d-ac41-549ea1e06e3a" width="600">

**Comment by OverLordGoldDragon** [comment]
Thanks @mooskagh in Discord -- Fixed by creating `lc0/build/lc0.config` with

```
weights=weights-large.pb.gz  # replace with yours
backend=cuda-fp16  # replace with non-failing backend
```

https://lczero.org/play/flags/#config-file
