### ISSUE TITLE
cannot run my main.py file through the app

### ISSUE THREAD

**Issue by GyatsoYT** [cutechess/cutechess#781]
hello there i recently installed cutechess and when i try to add my engine made in python i cannot run it through python main.py filled in command box

**Comment by GyatsoYT** [comment]
This is what happens 
![277157320-2037977e-ccf7-485c-bb46-7fd0d92c60de](https://github.com/cutechess/cutechess/assets/106143461/0bb9fa18-5ee4-4822-a9af-23046413c2a1)
![277157323-f448b6a2-09f2-4756-9f77-1f0ed9709e0e](https://github.com/cutechess/cutechess/assets/106143461/527a103b-f687-4e6a-bb66-b41d3d49375e)
Btw I am on windows

**Comment by mooskagh** [comment]
Not sure whether it will work, but as a workaround you can try to create `engine.cmd`, write `python bot1.py` there, and add this file instead as an engine.

**Comment by tissatussa** [comment]
`engine.cmd` is a bash file ?

**Comment by mooskagh** [comment]
A windows shell script.

**Comment by Disservin** [comment]
alternatively you can use pyinstaller to create an executable
`pyinstaller --onefile --workpath ./build --distpath ./build --specpath ./build -n chess-engine main.py`
