### ISSUE TITLE
time display among engines differs

### ISSUE THREAD

**Issue by tissatussa** [cutechess/cutechess#788]
the info table "Depth Time Nodes Score PV" shows the "time" at each depth. It seems some engines display the TOTAL evaluation time there, other engines display the time spent at THAT depth .. this is confusing .. what do the protocols define about this (UCI and XB) ? Or can this time data be set by authors to their liking ?

**Comment by alwey** [comment]
The UCI protocol does not specify it in a strict way. I think the intention is to issue the total time for the current search command (e.g. for the best next half move). The info texts provide user information. The are essentially irrelevant for the game protocol. However, in practice they are relevant for game adjudication by the arbiter (e. g. in cutechess the evaluation aspect can be used for early adjudication of wins, losses, and draws).

```
* info
	the engine wants to send infos to the GUI. This should be done whenever one of the info has changed.
	The engine can send only selected infos and multiple infos can be send with one info command,
	e.g. "info currmove e2e4 currmovenumber 1" or
	     "info depth 12 nodes 123456 nps 100000".
	Also all infos belonging to the pv should be sent together
	e.g. "info depth 2 score cp 214 time 1242 nodes 2124 nps 34928 pv e2e4 e7e5 g1f3"
	I suggest to start sending "currmove", "currmovenumber", "currline" and "refutation" only after one second
	to avoid too much traffic.
	Additional info:
	* depth 
		search depth in plies
	* seldepth 
		selective search depth in plies,
		if the engine sends seldepth there must also a "depth" be present in the same string.
	* time 
		the time searched in ms, this should be sent together with the pv.
	* nodes 
		x nodes searched, the engine should send this info regularly 
        ...
```
source: https://wbec-ridderkerk.nl/html/UCIProtocol.html

Also the xboard protocol is not very explicit. This protocol has precedence, it is older than UCI. I think the intention is the same as above: give the time used for the current search:

<html><body>
<h3 id="10">10. Thinking Output</h3>

<p>
If the user asks your engine to "show thinking", xboard sends your
engine the "post" command.  It sends "nopost" to turn thinking off.
In post mode, your engine sends output lines to show the progress of
its thinking.  The engine can send as many or few of these lines as it
wants to, whenever it wants to.  Typically they would be sent when the
PV (principal variation) changes or the depth changes.  The thinking
output should be in the following format:
</p>

<pre class="emph-box">ply score time nodes pv</pre>

<p>Where:</p>

ply | Integer giving current search depth.
-- | --
score | Integer giving current evaluation in centipawns.
time | Current search time in centiseconds (ex:1028 = 10.28 seconds).
nodes | Nodes searched.


</body>
</html>

source: https://www.gnu.org/software/xboard/engine-intf.html

**Comment by alwey** [comment]
> . i think displaying the total time is best, opposed to what you suggest : this way also the time-spent-per-depth can be derived ..

No actually I also think an engine should definitely display the total time for the current search.
