### ISSUE TITLE
change square colors ?

### ISSUE THREAD

**Issue by tissatussa** [cutechess/cutechess#789]
i see no option to change the square colors .. is it possible ? I once saw a PR to add a "board" tab to the options pane, to select the square coloring and even the piece types, but it seems v1.3.1 doesn't have this feature .. i'm using the appimage on Linux .. does a .ini or .json file exist where such parameters are kept ?

[ i'm on Xubuntu 22.04 ]

**Comment by alwey** [comment]
Currently the board features are fixed. However, there is a PR to change square colors, border colors, marker colors, piece sets. Please refer to PR #581.

This is also available (among other features) in the [EXPER3 branch of my repository](https://github.com/alwey/cutechess/commits/EXPER-3) of February 2022.
