### ISSUE TITLE
Humans can't castle

### ISSUE THREAD

**Issue by secrestb** [cutechess/cutechess#790]
## Output of `cutechess-cli --version` / `cutechess --version`
Using Qt version 5.15.2
Running on Windows 10 Version 2009/x86_64
Cutechess 1.3.1

## How did you run Cute Chess exactly?
I used the GUI?!

I started a new game with stockfish as white and human as black.  TL 40 moves in 1min with a 5 sec inc.

## Expected behavior

When you move the king two squares toward the rook (castle), then recognize it as a legal move and perform castling.

## Actual behavior
At the point in the game I wanted to castle, it wouldn't.  Castling was legal at that point.  I attempted to select the king and move it two squares toward the rook.  Nothing happened.

## Steps to reproduce the behavior

Start a new game between two humans.  1. g3 , g6; 2. Bg2, Bg7; 3. Nf3, Nf6; 4. O-O won't work

**Comment by alwey** [comment]
Castling works for me. Cutechess 1.3.1 using Qt:5.15.2 Windows 10 Version 22H2.

In order to castle your king has to capture your rook.

**Comment by ilaripih** [comment]
Like alwey said, we use the "king captures rook" method because it works with all chess variants, including Chess960. But it's possible that this will change at some point for standard chess because "king captures rook" doesn't feel intuitive to most people.
