### ISSUE TITLE
Cute Chess crashes when a tournament error by "No response to ping"

### ISSUE THREAD

**Issue by winapiadmin** [cutechess/cutechess#794]
## How did you run Cute Chess exactly?

By a shortcut that points to Cute Chess GUI (by the installer)

## Version

1.3.1

## Expected behavior

The game continues.

## Actual behavior

A dialog with title "Tournament error" then crashes or stop the tournament
Dialog content: `No response to ping`

## Steps to reproduce the behavior

Create a tournament with chess engines
Time: 1+1
Type: round robin
Recover crashed engines
Save unfinished games
Swap sides
Rounds: 1
Engines: 4

**Comment by ilaripih** [comment]
Hi. Can you provide some additional details:

- What operating system do you use?
- In Settings -> Tournaments -> Games, what's the **Concurrent games** value?
- What chess engines did you use? Is there a freely available chess engines that I can try to re-produce this with?
- Did you use any opening book or opening suite?
- Did the crash happen immediately, during a game or between games?

**Comment by winapiadmin** [comment]
Concurrent games: 1
Engines: SF 7-16.1 (include some prerelease versions) +Rybka+AsmFish+Chess Coding Adventure+Komodo Dragon (mostly free) (all in x64)
No opening book or suite
The problem happens when beginning with engines that is not SF and SF 16 and 16.1 (including beta versions)

**Comment by ilaripih** [comment]
Thanks! I artificially forced the engines to not respond to ping, and did get a crash, fixing it right away.

**Comment by ilaripih** [comment]
Fixed now in master, we'll do a new release today
