### ISSUE TITLE
redirecting stderr of engines

### ISSUE THREAD

**Issue by lucasart** [cutechess/cutechess#8]
is it possible to redirect the stderr of engines, with cutechess-cli ?

my problem is as follows:
- my engine has lots of assert()
- sometimes the debug version crashes, in ways that I cannot replicate manually. the non debug version never crashes, so it should be an assert().
- I want to run a debug compile with cutechess-cli, in real tournament conditions, until it crashes, and see which assert() fired.

**Comment by ilaripih** [comment]
We thought we'd do it like this: If the "-debug" parameter is passed to cutechess-cli, engines' stderr is redirected to cutechess-cli's stderr, along with information about which engine the message came from.

**Comment by Stefano80** [comment]
I have often missed the same feature. I often instrument engine code to get some internal statistics, which I would like to collect in realistic situation. At the moment there is no simple way to do it.

**Comment by ilaripih** [comment]
It's now possible to redirect an engine's stderr to a file, because that was the easiest thing to do.

**Comment by Stefano80** [comment]
Thank you I'll try to check it as soon as possible

**Comment by Stefano80** [comment]
Hi, 

I suppose that the option is not in the distributed binaries (or at least, I was not able to use it). I downloaded the source and used qmake and make as described. I've got this error

make[2]: Leaving directory '/home/cardanobile/Dokumente/stefano/chess/gitProjects/cutechess-master/projects/lib'
cd gui/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/cardanobile/Dokumente/stefano/chess/gitProjects/cutechess-master/projects/gui/gui.pro -o Makefile ) && make -f Makefile 
Project ERROR: Unknown module(s) in QT: svg
Makefile:87: recipe for target 'sub-gui-make_first-ordered' failed
make[1]: *** [sub-gui-make_first-ordered] Error 3
make[1]: Leaving directory '/home/cardanobile/Dokumente/stefano/chess/gitProjects/cutechess-master/projects'
Makefile:42: recipe for target 'sub-projects-make_first' failed
make: *** [sub-projects-make_first] Error 2

Am I doing something wrong? I have Qt 5.4.1 installed:

cardanobile@cardanobile-B75MA-P45:~/Dokumente/stefano/chess/gitProjects/cutechess-master$ qmake -v
QMake version 3.0
Using Qt version 5.4.1 in /usr/lib/x86_64-linux-gnu

**Comment by ilaripih** [comment]
The option is actually included in the cutechess beta binaries. Here's the 64-bit Linux version: http://koti.mbnet.fi/~ilaripih/bin/cutechess-cli-0.8.0b2-linux64.tar.gz

The compilation fails because you're trying to compile the whole cutechess project (lib, cli and gui) and the gui project requires Qt's SVG module (libqt5svg5-dev on Ubuntu).

**Comment by Stefano80** [comment]
It works, thank you very much!

**Comment by ilaripih** [comment]
Great to hear. I'll leave this issue open, because it would also be useful to redirect an engine's stderr output to cutechess' debug and/or stderr output.
