### ISSUE TITLE
question about pgn openings

### ISSUE THREAD

**Issue by gahtan-syarif** [cutechess/cutechess#812]
I notice that when specifying `plies=16` for this pgn:
```
[Result "1/2-1/2"]

1. e4 Nc6 2. Nf3 d5 3. exd5 Qxd5 4. Nc3 Qd8 5. Nb1 Qd5 6. Ng1 Qd8 7. Nf3 Qd5 8. Nc3 Qa5 1/2-1/2
```
cutechess doesnt parse the full 16 plies but rather stops at `7. Nf3`. This is obviously because `7. Qd5` is a 3fold repetition. Now is this a design decision from cutechess side or is it a bug? as technically a 3fold repetition can still be played on and is not a mandatory draw so i dont see a problem with parsing the full 8 moves

**Comment by alwey** [comment]
As far as I know, cutechess cannot not parse beyond ends. The parser als invokes a **move generator** in context of legality checks. If the move under examination is not within the list of generated legal moves, then it is illegal. And after game end move generation could become unpredictable. We have to take into account that cutechess handles multiple game variants.

**Comment by gahtan-syarif** [comment]
I see, thanks for the clarification

**Comment by ilaripih** [comment]
Yeah, this is one of those issues that resolving it would quite likely create nasty side effects in multiple places. So I'm closing this one.
