### ISSUE TITLE
Game options widget

### ISSUE THREAD

**Issue by ilaripih** [cutechess/cutechess#82]
This is split from issue #59. We need a widget for setting the following game options in `NewGameDialog`, `NewTournamentDialog` and `SettingsDialog`:

- [x] Variant
- [x] Time control
- [x] Pondering
- [x] Draw and resign adjudication
- [x] Tablebases (ON/OFF for now)
- [x] Opening suite and opening order
- [x] FEN input as an alternative to opening suite
- [x] Validate FEN before trying to start the game
- [x] Opening book and book depth
- [x] Add GameSettingsWidget to SettingsDialog where defaults can be set

**Comment by anil100391** [comment]
With these added options the size of new tournament dialog has grown so much that does not fit the screen. We need a scroll bar in the dialog; probably in other dialogs too.

**Comment by ilaripih** [comment]
I think scrolling can be avoided. Maybe game settings could be a separate tab or the layout could be different. I'll experiment with some options...

**Comment by ilaripih** [comment]
As a quick fix I made the layout more horizontal.

**Comment by ilaripih** [comment]
Finally done.
