### ISSUE TITLE
GUI: engines don't start with current master

### ISSUE THREAD

**Issue by rwst** [cutechess/cutechess#84]
top doesn't show engine processes in GUI with any kind of tournament (eg the default values and two Stockfish slots), while CLI works fine.

**Comment by ilaripih** [comment]
They start on my Linux 64-bit and Windows 64-bit systems. What OS do you use? Do you get any error messages like "Cannot execute command stockfish-6-64.exe"?

**Comment by rwst** [comment]
This is OpenSUSE Leap. No messages on console.

**Comment by ilaripih** [comment]
I meant error messages in an alert box. If cutechess-gui fails to start an engine process it shows an alert box.

Do the engine processes start if you run the game via the "New Game" dialog?

**Comment by rwst** [comment]
Yes, engines start fine from New Game.

**Comment by ilaripih** [comment]
Good to know. And have you successfully run tournaments before, ie. did one of the recent commits break this? And do you know which commit?

Oh and what does the "Tournament" tab in `Window -> Settings` look like? Could it be possible that concurrency is set to less than 1?

**Comment by rwst** [comment]
A good occasion to try the `git bisect` tool.
```
f7462c18bc1712baffaf45412d0b1014d135a001 is the first bad commit
commit f7462c18bc1712baffaf45412d0b1014d135a001
Author: Ilari Pihlajisto <ilari.pihlajisto@mbnet.fi>
Date:   Fri Jul 22 11:35:46 2016 +0300

    gui: concurrency can be controlled live via SettingsDialog

:040000 040000 28857abb87d945f181983188583c6c7f4909a024 065d0b92c54d837237db7fb21b6c787c81e29bfb M   projects
```
The settings show concurrency set to `1`.

**Comment by ilaripih** [comment]
Thanks. So somehow concurrency is set to <= 0 which of course shouldn't happen. Can you put this after line 132 in `projects/gui/src/cutechessapp.cpp`:

`qDebug("Concurrency: %d", concurrency);`

Then you should see the concurrency value in the console when cutechess starts.

**Comment by ilaripih** [comment]
We clearly have a bug in the app settings: there are no default values, so for example concurrency is 0 until the setting is saved in SettingsDialog. We should fix this. But if setting concurrency in SettingsDialog doesn't fix things then we also have another bug.

**Comment by artoj** [comment]
The default setting can be given as the second argument to QSettings::value(). The default value is used when the setting doesn't exist. There's QThread::idealThreadCount() which may be used for the default.

**Comment by ilaripih** [comment]
I think we should use 1 as the default because usually people prefer the engines to use their parallel search, in which case a single engine uses 100% of all cpus.

**Comment by rwst** [comment]
As you thought the output is
```
Concurrency: 0
```

**Comment by ilaripih** [comment]
That suggests that on your system cutechess-gui can't read and/or write the settings. What if change the concurrency setting to 2 for example, then restart cutechess-gui and go back to the Settings dialog. Is concurrency then set to 2?

And what if you go to the Settings dialog, set concurrency to some value and then start a tournament. Are the engine processes started properly?

**Comment by ilaripih** [comment]
Do you by any chance use an NFS-connected filesystem and what is your Qt version?

**Comment by rwst** [comment]
Actually, now that I have once set to `2` (which persisted over sessions) it works, even if set back to `1`. The persistent storage must have had a bad value. How can I reset the state, ie. to when it didn't work? No NFS BTW and the libs linked are
```
        libQt5Svg.so.5 => /usr/lib64/libQt5Svg.so.5 (0x00007f7ddbb37000)
        libQt5PrintSupport.so.5 => /usr/lib64/libQt5PrintSupport.so.5 (0x00007f7ddb8c5000)
        libQt5Widgets.so.5 => /usr/lib64/libQt5Widgets.so.5 (0x00007f7ddb043000)
        libQt5Gui.so.5 => /usr/lib64/libQt5Gui.so.5 (0x00007f7dda918000)
        libQt5Concurrent.so.5 => /usr/lib64/libQt5Concurrent.so.5 (0x00007f7dda712000)
        libQt5Test.so.5 => /usr/lib64/libQt5Test.so.5 (0x00007f7dda4dc000)
        libQt5Core.so.5 => /usr/lib64/libQt5Core.so.5 (0x00007f7dd9e00000)
```
This is libqtcore-5.5.1

**Comment by ilaripih** [comment]
You would have to delete the configuration file: http://doc.qt.io/qt-5/qsettings.html
It should be in one of the locations mentioned in the "Locations Where Application Settings Are Stored" section.

Anyway, I know know how to fix this bug.
