### ISSUE TITLE
Protected branches

### ISSUE THREAD

**Issue by artoj** [cutechess/cutechess#86]
See if protected branches (https://help.github.com/articles/about-protected-branches/) should be taken in to use in the `master` branch. This would protect from accidental history rewrites.

**Comment by ilaripih** [comment]
That's a good idea, especially now that I'm occasionally force pushing stuff to temporary non-master branches.

**Comment by artoj** [comment]
I've enabled branch protection in the master branch. Non fast-forward pushes should be denied.
