### ISSUE TITLE
The command ucinewgame sent during search without a preceding stop

### ISSUE THREAD

**Issue by bmdanielsson** [cutechess/cutechess#88]
Hi,

While adding support for pondering to my engine I encountered some unexpected behaviour by cutechess-cli (version  0.8.2). What happens is that cutechess-cli reports that the engine made an illegal move. This happens some times when I run a gauntlet between the pondering and non-pondering versions of my engine. When I look in the engine log I see the following sequence of commands:

=> go ...
<= bestmove ... ponder ...
=> go ponder ...
<= info
...
=> ucinewgame
=> position ...
=> go ...
<= bestmove ...

My expectation was that since the engine is searching it should receive an stop command before the ucinewgame command. Is this a bug in cutechess-cli or have  misunderstood the UCI specification?

What happens in the scenario above is that my engine ignores ucinewgame and position commands while it's searching so the best move reported is for the previous game.

Best Regards
/Martin

**Comment by ilaripih** [comment]
That looks like a bug, cutechess-cli should've sent `stop` before `ucinewgame`. Have you only been able to reproduce this behaviour when one engine is pondering and the other is not?

How did the game end (checkmate, draw, adjudication)? And what parameters did you pass to cutechess-cli? Also it would be helpful if I could get the complete debug log, you can attach it as a file to a Github message.

**Comment by bmdanielsson** [comment]
So far I have only tested with one engine pondering, so I don't know if it happens when both engines are pondering. In all cases I have seen the game have ended in adjudication.

I use the command below when testing (I'm using windows 10). The first engine is the one with pondering support and the second is the one without.
[logs.zip](https://github.com/cutechess/cutechess/files/401932/logs.zip)


./cutechess-cli.exe -engine proto=uci option.OwnBook=false option.Hash=32 ponder cmd=/c/Users/Martin/Documents/Chess/tournament/engines/miles/Miles.exe ponder ponder dir=/c/Users/Martin/Documents/Chess/tournament/engines/miles -engine proto=uci option.OwnBook=false option.Hash=32 ponder cmd=/c/Users/Martin/Documents/Chess/tournament/engines/miles_base/Miles.exe ponder ponder dir=/c/Users/Martin/Documents/Chess/tournament/engines/miles_base -each tc=1+0.5 -concurrency 1 -repeat -resign movecount=5 score=900 -tournament gauntlet -pgnout output_16-56-59.pgn -rounds 5000 -openings file=8moves_GM_LB.pgn format=pgn

Since I run a gauntlet of 5000 games the log files are huge so I have extracted some sample data. The attached zip file contains two examples of the problem. For each example I have included three consecutive games and the corresponding part of the engine log. In both examples look for the second ucinewgame command in the engine log.

**Comment by ilaripih** [comment]
It seems that you've stripped the communication of the other engine from the debug logs and also removed the timestamps (the integer that starts every line). That makes it difficult to find out if the problem is a sort of race condition where one engine sends `bestmove` before the other is told to ponder.

**Comment by bmdanielsson** [comment]
Here is a new log. I hope it includes all the information you need. The issue happened two times during this test run, see games 29 and 77.

[cutechess.zip](https://github.com/cutechess/cutechess/files/404538/cutechess.zip)

**Comment by ilaripih** [comment]
Thanks, that confirmed my suspicion - engine X sends `bestmove` before engine Y responds to `isready` (followed by `position` and `go ponder`. So cutechess-cli shouldn't even tell engine Y to ponder. I'll fix this ASAP.

**Comment by ilaripih** [comment]
I may have fixed the bug but can't be sure because I couldn't reproduce the issue. Can you test the version attached to this message, or alternatively clone and build the latest master?

[cutechess-cli-beta-win64.zip](https://github.com/cutechess/cutechess/files/404983/cutechess-cli-beta-win64.zip)

**Comment by bmdanielsson** [comment]
Sure. I'll start a test run and let it run over night.

**Comment by bmdanielsson** [comment]
1200+ games and no problems seen. It used to happen about every 200 games so I think we safely say that the bug have been fixed.

**Comment by ilaripih** [comment]
Thanks and great to hear! As this is an important fix we'll release cutechess-cli 0.8.3 soon.
