### ISSUE TITLE
Dockerfiles for building Linux releases

### ISSUE THREAD

**Issue by ilaripih** [cutechess/cutechess#96]
Whether we build AppImage installer or Debian/RPM packages, we should have Dockerfiles for doing so in an environment with minimal dependencies and an old enough base image (eg. Debian Jessie for .deb packages, Centos 6 for .rpm).

- [X] Debian package.
- [X] RPM package.
- [x] .tar.gz package for cutechess-cli.
- [x] Include menu item with icon, example here: https://packages.debian.org/sid/amd64/chessx/filelist

Even though cutechess-cli is included in the .deb and .rpm packages we should still continue to release a .tar.gz package for those who want to run the Linux version on a headless system (without X).

**Comment by probonopd** [comment]
Using wheezy would allow for compatibility with even more (older) target systems. If debs are available, then they can be converted to AppImages relatively similar to [this](https://github.com/probonopd/AppImages/blob/ebfa406f37c8a50743a82453056b227376602195/recipes/demonsaw/Recipe).

**Comment by ilaripih** [comment]
Our Qt dependency target is whatever Debian stable currently has. Wheezy's default repository doesn't have Qt5 (>= 5.3) but I guess we could support Wheezy with backports.

**Comment by probonopd** [comment]
Yes, 5.3.2 seems to be available on https://packages.debian.org/wheezy-backports/qt5-default

**Comment by ilaripih** [comment]
I've updated the Dockerfile to use `debian:wheezy-backports` as the base image.

**Comment by probonopd** [comment]
Thanks, are the resulting deb files available for download somewhere?

**Comment by ilaripih** [comment]
Not yet. But they will be once we're ready to release version 0.9.

**Comment by ilaripih** [comment]
Now the same Debian Wheezy Docker image is used for building both Debian and RPM packages. I've tested the .deb package on older and newer Debian and Ubuntu images and the .rpm package on Centos 6 and Centos 7.
